### ISSUE TITLE
Cross-Origin Request Blocked

### ISSUE THREAD

**Issue by Snooowgh** [EOSIO/eosjs#100]
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://127.0.0.1:8888/v1/chain/get_block. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

**Comment by mlawand** [comment]
try this in your config.ini

try access-control-allow-origin = *

**Comment by chris-allnutt** [comment]
I believe this is something the node has to allow and isn't something eosjs can fix.
