### ISSUE TITLE
How to set the blockBehind when sending transaction

### ISSUE THREAD

**Issue by Albert-Gao** [EOSIO/eosjs#1010]
**Version of EOSJS**
'eosjs':'22.1.0'
'react-native':'0.64.2'

**Context**
I am currently sending a transaction, which works, but wonder if I am doing it wrong or not.

I am using the format from this [document](https://developers.eos.io/manuals/eosjs/v22.0/how-to-guides/how-to-submit-a-transaction)

```javascript
(async () => {
  const transaction = await api.transact({
   actions: [{
     account: 'eosio',
     name: 'buyrambytes',
     authorization: [{
       actor: 'useraaaaaaaa',
       permission: 'active',
     }],
     data: {
       payer: 'useraaaaaaaa',
       receiver: 'useraaaaaaaa',
       bytes: 8192,
     },
   }]
  }, {
   blocksBehind: 3,
   expireSeconds: 30,
  });
})();
```

My only question is how to set the `blockBehind`, currently I am just following the documentation and hard code this to be 3. Does not sound right, what is the suggested way of doing this? Or, by just setting 3 is fine? Thanks

Tried the other approach, setting `expiration`, `ref_block_num`, and `ref_block_prefix`. but got the error of `Number is out of range` from the `checkRange()` function.

**Comment by bradlhart** [comment]
`blocksBehind` is used to setup the Tapos fields that you stated, such as the ref_block_num, ref_block_prefix, etc.  It doesn't necessarily mean that your transaction will be set on that block number.  You can use 3 or higher to avoid your transaction accidentally referencing a non-irreversible block and possibly being subject to a soft fork or you could use the recently added field `useLastIrreversible` instead to be certain that the referenced block will be the most recent irreversible block on your chain.   Likely, `useLastIrreversible` would be best for your use-case.

Feel free to ask any further questions here but assuming the initial question has been answered, I'll close this ticket.

**Comment by Albert-Gao** [comment]
@bradlhart  Thanks so much for this info!

Tried it, however, got an error,

```typescript
[
  "action:",
  {
    "account": "eosio.token",
    "name": "transfer",
    "authorization": [
      {
        "actor": "AAA",
        "permission": "active"
      }
    ],
    "data": {
      "from": "AAA",
      "to": "BBB",
      "quantity": "4.0000 UTX",
      "memo": ""
    }
  }
]
```

With this extra parameter:

``` javascript
{
        blocksBehind: 3,
        expireSeconds: 30,
      }
```

Got this error,
<img width="527" alt="image" src="https://user-images.githubusercontent.com/18282328/129632794-f03b290a-6c04-4b8b-9119-c11605b64807.png">

I do not get it, I did not pass any block time, I thought it is derived at the backend? Meanwhile, `blockAfter` seems always works. What am I missing here? I prefer to use this shiny `useLastIrreversible`, thanks :)

**Comment by bradlhart** [comment]
I'd recommend increasing the `expireSeconds` since your transaction expired.

**Comment by Albert-Gao** [comment]
@bradlhart  Thanks, increased it to 170 solved the problem! any documentation I can read against setting this up? Wanna learn the rules here. :) Thanks
