### ISSUE TITLE
When my contract uses EOS token, it will appear bug.

### ISSUE THREAD

**Issue by xiangxn** [EOSIO/eosjs#108]
error:Table stat is not specified in the ABI

assetCache.lookupAsync(assetSymbol.symbol, currentAccount)
Where "currentAccount" may not be eosio.

**Comment by jcalfee** [comment]
Symbols are unique by contract not by blockchain.  Try using the extended_asset or extended_symbol types in your contract.  This means your going to pass values like `1 EOS@eosio.token` or `EOS@eosio.token` instead of just EOS.

Use the latest eosjs release, these have been under development.

**Comment by jcalfee** [comment]
Asset and Symbol defaults to eosio.token now..  Let me know if you still see an issue.
