### ISSUE TITLE
how to setabi?

### ISSUE THREAD

**Issue by yankunsam** [EOSIO/eosjs#110]
eos.setabi('inita', JSON.parse(abi)). It does not work.

**Comment by yankunsam** [comment]
The error message: sam@sam-machine:~/Public/Eoasis$ cleos get code eosio.token
646929ms thread-0   main.cpp:2493                 main                 ] Failed with error: Out of Range (8)
read datastream of length 1766 over by -85
Error unpacking field type
error unpacking eosio::chain::type_def
Error unpacking field types
error unpacking eosio::chain::abi_def

**Comment by jcalfee** [comment]
published eosjs@12.0.3

**Comment by jcalfee** [comment]
related: https://github.com/EOSIO/eos/commit/ed3f21b37ad27e0c1c48cc618650b3ff50d39b0f#commitcomment-29132987

**Comment by yankunsam** [comment]
Update to 12.0.3. The issue also exst. Can you give me a successful snapshot? Thanks

**Comment by jcalfee** [comment]
I see the issue thanks..  I updated the comment in the EOSIO/eos (link above).

**Comment by yankunsam** [comment]
So it works for eos: master now?

**Comment by jcalfee** [comment]
Still does not work ;-/

**Comment by jcalfee** [comment]
I'm still blocked on this error when re-fetching the contract:
>646929ms thread-0 main.cpp:2493 main ] Failed with error: Out of Range (8)
>read datastream of length 1766 over by -85

**Comment by rcfcu2000** [comment]
Is this still an open issue?

**Comment by rcfcu2000** [comment]
The C++ code is using fc::raw::pack to deal with abi_def:

chain::action create_setabi(const name& account, const abi_def& abi) {
   return action {
      tx_permission.empty() ? vector<chain::permission_level>{{account,config::active_name}} : get_account_permissions(tx_permission),
      setabi{
         .account   = account,
         .abi       = fc::raw::pack(abi)
      }
   };
}

I guess we will have to do the same in js code

**Comment by yankunsam** [comment]
@rcfcu2000 Have you tried the original http rpc? https://eosio.github.io/eos/group__eosiorpc.html

**Comment by jcalfee** [comment]
Sill an issue, here is an update..

I am serializing according to abi_def but it is still having an issue.

I can set an ABI but I can't read it back.. It says "Error unpacking field version" .. I'm loading the ABI directly from the contracts folder and it has the new version string it in: "eosio::abi/1.0" .. Am I reading the error correctly? Here is the full error:

> method: 'throw_datastream_range_error' } http://127.0.0.1:8888/v1/chain/get_code {"account_name":"inita"}
{ Error: {"code":500,"message":"Internal Service Error","error":{"code":8,"name":"out_of_range_exception","what":"Out of Range","details":[{"message":"read datastream of length 14 over by -12","file":"datastream.cpp","line_number":6,"method":"throw_datastream_range_error"},{"message":"Error unpacking field version","file":"raw.hpp","line_number":368,"method":"operator()"},{"message":"error unpacking eosio::chain::abi_def","file":"raw.hpp","line_number":616,"method":"unpack"}]}}

If you try testing it, use github, the updated abi_def is not in the current version (v13.1.0) but will be in the next version..

work-around: deploy or re-deploy the ABI using cleos...

**Comment by jcalfee** [comment]
Summary if I deploy with eosjs it does not fetch the ABI in cleos or eosjs .. deploy with cleos and it fetches the ABI just fine.

**Comment by rcfcu2000** [comment]
After serializing the abi_def,  I think we will need to pack(fc::raw::pack) the bytes like cleos does.

The bytes without packing can be deployed, but it failed to unpack when fetching it back.

**Comment by jcalfee** [comment]
Instead of `bytes` I'm using the `abi_def` struct which does serializes (pack) it in binary.

**Comment by arhag** [comment]
@jcalfee:
The native action handler is [expecting](https://github.com/EOSIO/eos/blob/v1.0.0/libraries/chain/include/eosio/chain/contract_types.hpp#L44) `bytes` (i.e. `vector<char>`) for the `abi` field of the `setabi` action.

`fc::raw::pack` of `vector<char>` [first includes](https://github.com/EOSIO/eos/blob/v1.0.0/libraries/fc/include/fc/io/raw.hpp#L293) a variable-length integer of the size of the data in bytes before the actual data.

So if your `setabi` action payload is simply the 8 byte `account` name followed directly by the binary serialization of `abi_def` (for the `abi` field), then there will certainly be a corruption when cleos later unpacks. Instead the raw data of the binary serialization of `abi_def` should be preceded by the binary encoding of the variable-length integer (`fc::unsigned_int`) of the size (in bytes) of the binary serialization of `abi_def`.

**Comment by jcalfee** [comment]
Thank you @arhag .. the commit above fixes this, it will be in the next release this evening.
