### ISSUE TITLE
There was a problem when I used eosjs updateauth.

### ISSUE THREAD

**Issue by bulangnisi** [EOSIO/eosjs#112]
let eos = eosjs.Localnet(config);

let pubkey = 'EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV';

let auth = { threshold: 1, accounts: [{permission: {actor: "bigMaster", permission: "eosio.code"}, weight: 1}], keys: [{ key: pubkey, weight: 1 }] };

let op_data = {
        account: username,
        permission: 'active',
        parent: 'owner',
        auth: auth
};

eos.updateauth(op_data).then(res => console.log(res)).catch(err => console.error(err));

i got TypeError: Cannot read property 'threshold' of undefined authority.threshold updateauth.data action.data transaction.actions

BUT , When I use the broswer version of eos.js.  this is ok.

**Comment by jcalfee** [comment]
you can't have an upper-case in account names: `bigMaster`

Your code works in nodejs for when I use test accounts and update to an active permission.

**Comment by bulangnisi** [comment]
@jcalfee i try to modify the name, But the same error occurred

Cannot read property 'threshold' of undefined authority.threshold updateauth.data action.data transaction.actions

**Comment by jcalfee** [comment]
```bash
npm install eosjs@12
npm WARN npm@1.0.0 No description
npm WARN npm@1.0.0 No repository field.

+ eosjs@12.0.2
removed 2 packages and updated 3 packages in 7.181s
jcalfee@jcalfee-Inspiron-7548: ~/npm
node
> Eos = require('eosjs'), keyProvider = '5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3', eos = Eos.Localnet({keyProvider}), 1
1
> let pubkey = 'EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV';
undefined
> 
> let auth = { threshold: 1, accounts: [{permission: {actor: "inita", permission: "active"}, weight: 1}], keys: [{ key: pubkey, weight: 1 }] };
undefined
> 
> let op_data = {
... account: 'inita',
... permission: 'active',
... parent: 'owner',
... auth: auth
... };
undefined
> 
> eos.updateauth(op_data).then(res => console.log(res)).catch(err => console.error(err));
Promise {
  <pending>,
  domain: 
   Domain {
     domain: null,
     _events: { error: [Function: debugDomainError] },
     _eventsCount: 1,
     _maxListeners: undefined,
     members: [] } }
> 
> { transaction_id: '76460479a8ec896a5cd0b71e0533e141cad4bd86df04172463a97b88cbea6849',
  broadcast: true,
  transaction: 
   { compression: 'none',
     transaction: 
      { expiration: '2018-05-25T15:34:44',
        ref_block_num: 51427,
        ref_block_prefix: 3101834119,
        net_usage_words: 0,
        max_cpu_usage_ms: 0,
        delay_sec: 0,
        context_free_actions: [],
        actions: [Array],
        transaction_extensions: [] },
     signatures: [ 'SIG_K1_K4P15eWmXpXE9FioY7znRMdg51x4Nwk19ZPDo3QtgN9y8EmV6eUBQERj35JBVLgKhnycTrwKDVKZjSbhzGzDukqFu4ZiZq' ] } }
```

**Comment by bulangnisi** [comment]
@jcalfee thanks ,it work

**Comment by jimoful** [comment]
i will try to test
