### ISSUE TITLE
Versioned releases should have hard locked dependencies

### ISSUE THREAD

**Issue by chris-allnutt** [EOSIO/eosjs#114]
For now we're using resolutions in the package.json to work around this:
```
  "resolutions": {
    "eosjs-ecc": "3.0.2"
  },
```
We had a similar issue with eosjs-keygen that ultimately led to K1 prefixed signatures being used on our frontend while our backend was expecting the old format.

**Comment by jcalfee** [comment]
published eosjs@12.0.3
