### ISSUE TITLE
Duplicate transaction error

### ISSUE THREAD

**Issue by Dylan-Phoon** [EOSIO/eosjs#116]
<img width="1284" alt="screen shot 2018-05-26 at 00 19 15" src="https://user-images.githubusercontent.com/37438950/40569565-9909017e-607a-11e8-80b2-13d3c3ec7c2b.png">

When I make two transactions straight after each other (very quickly), I get duplicate transaction error yet, both transactions seem to go through just fine (balance deducted from account etc.).

Get the same error when using two different accounts and sending one transaction from each account as well.

**Comment by jcalfee** [comment]
Someone on the core team told me they tried to re-create this but could not.  Is this still an issue?  Can you provide more info to repeat the problem?

**Comment by ekkis** [comment]
`cleos push action` offers a --force-unique option.  I'm wondering if this is available on eosjs as I have the same issue

**Comment by ekkis** [comment]
@jcalfee I'm revisiting this issue.  it is common in test suites to want to issue the same transaction twice, to make sure that the backend code handles it properly.  in my particular case, records represent signatures and I want to be able to write them twice, albeit with different dates.  when I make the call to the method, no date is passed, as this is supplied by the method itself, thus the transactions seem like duplicates and error out as such

how can I solve this predicament?

**Comment by ekkis** [comment]
I've tried passing a field in the `data` section of actions passed into `api.transact` like this: `nonce: Math.random()` but it doesn't help

**Comment by jcalfee** [comment]
@tbfleming have you seen this recently?

**Comment by ekkis** [comment]
for the record, I'm using v20.0.0 of eosjs

**Comment by ekkis** [comment]
so I modified the signature to the method to accept an integer, which then I pass a random value to.  that seems to fix the problem but it's a shite way to do it.  still open to input from anyone on this

**Comment by jcalfee** [comment]
It is definitely coming from the network. I don't think it considers the signature when it is finding uniqueness.  You can see the code by searching.  Looks like it maybe the same tx ID and Expiration: 

https://github.com/EOSIO/eos/blob/eb88d033c0abbc481b8a481485ef4218cdaa033a/libraries/chain/transaction_context.cpp#L709
