### ISSUE TITLE
Replace net_usage_words with max_net_usage_words

### ISSUE THREAD

**Issue by yepp4you** [EOSIO/eosjs#117]
https://github.com/EOSIO/eosjs/blob/0159ba444d869614f0c66f1709f4dc3c504e8a5e/src/schema/chain_types.json#L52

**Comment by jcalfee** [comment]
This was changed at some point.  Review the version table in the README to make sure your using eosjs with the correct version of nodeos..

**Comment by jcalfee** [comment]
There are still references to both in the back end code.  The thing that matters is the transaction header serialization definition:

```c++
//transaction.hpp
EOSLIB_SERIALIZE( transaction_header, (expiration)(ref_block_num)(ref_block_prefix)(net_usage_words)(max_cpu_usage_ms)(delay_sec) )
```

**Comment by yepp4you** [comment]
It did so at eojs-api@6.0.1, it seems to be no problem because it is the net_usage_words from the latest version eosjs-api@6.0.2. Thank you.

https://github.com/EOSIO/eosjs-api/blob/57f13f139af3454fb3306c969d9416cebb6c2a66/src/exported-helpers.js#L57
