### ISSUE TITLE
Authorization error

### ISSUE THREAD

**Issue by anil215** [EOSIO/eosjs#120]
I have just updated to dawn 4.2.0 and updated eosjs version 13.0.0. The same code which used to work in dawn 4.1 with its eosjs version is giving authorization error.
![screen shot 2018-05-27 at 4 18 08 am](https://user-images.githubusercontent.com/23135051/40580827-04b46414-6165-11e8-93ae-887ae16c70bc.png)

Any comments where i should change. Woked fine in dawn 4.1

**Comment by jcalfee** [comment]
`options:{json: true}` does not belong, that is not part of the transaction or part of eosjs .. it json: true is used in at least one read-only call to nodeosd.  That does not belong in the actions though..  This is ignored and not causing an error.

The authorization error is probably a version miss-match..  The data that we are signing changed recently.  Double check that your really running 4.2 and eosjs 13.

I just ran the example in the readme on dawn 4.2 and it worked.

**Comment by anil215** [comment]
The problem was the cahinid field in the config for eosjs. Thanks a lot though for your reply.

**Comment by Thomazella** [comment]
@anil215 I'm facing a similar issue. How did you solve it?
