### ISSUE TITLE
I run npm install eosjs -> no eos.js. file generated

### ISSUE THREAD

**Issue by filipniziol** [EOSIO/eosjs#124]
In dawn 3.0 eos.js file was inside /node_modules/eosjs/dist folder.
I run "npm install eosjs" and there is no dist folder.
How to get eos.js file?

**Comment by sss-CRS-sss** [comment]
You need:

**Comment by sss-CRS-sss** [comment]
You need:
1) Install eosjs (npm install..)
2) build eosjs for browser 
go to folder with eosjs source and run command "npm run build_browser"

**Comment by filipniziol** [comment]
Thanks - it did not work on Windows, however went smoothly on Linux

**Comment by jcalfee** [comment]
I have added eos.js to the release tag..
https://github.com/EOSIO/eosjs/releases/tag/v13.0.0

**Comment by filipniziol** [comment]
Thanks! I already found that build browser does not work on Windows, but went smoothly on Linux
