### ISSUE TITLE
Installing EOSJS to empty dir

### ISSUE THREAD

**Issue by Catley94** [EOSIO/eosjs#125]
When I install EOSJS to an empty directory, I get these errors:
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\scp94\Projects\EOS\eosjs\package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\scp94\Projects\EOS\eosjs\package.json'
npm WARN eosjs No description
npm WARN eosjs No repository field.
npm WARN eosjs No README data
npm WARN eosjs No license field.

+ eosjs@13.0.0
added 43 packages in 41.035s

Is this normal?

**Comment by jcalfee** [comment]
What is the first command you ran?

**Comment by Catley94** [comment]
npm install eosjs

**Comment by jcalfee** [comment]
Use `npm init` first..

**Comment by jcalfee** [comment]
I re-created the error so I'll close .. I'm sure you just need npm init..
```js
npm i eosjs
npm WARN saveError ENOENT: no such file or directory, open '/tmp/package.json'
```
