### ISSUE TITLE
eos.contract('eosio.token').then(result => result.create('eosio.token','10000.0000 CUR',{authorization: 'eosio.token'}))

### ISSUE THREAD

**Issue by yankunsam** [EOSIO/eosjs#128]
(node:77342) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: Missing currency stats for asset: CUR@eosio.
token
    at network.getCurrencyStats.then.result (/Users/sam/Public/eosjs/src/asset-cache.js:29:7)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by jcalfee** [comment]
Please upgrade eosjs .. that was a bug and was fixed in v13 and v12

https://github.com/EOSIO/eosjs/commit/9fe586a72960e37e5863c9a8227f0f292dae2c77

```js
+
+    if(account === 'eosio') {
+      account = 'eosio.token'
+    }
+
```

**Comment by yankunsam** [comment]
I used the lasted eosjs(+ eosjs@13.0.0)  Can you update the README that has been tested successfully. Thanks

**Comment by jcalfee** [comment]
Where is the issue in the README?
