### ISSUE TITLE
create account on eosjs 13.0 (dawn4.2)

### ISSUE THREAD

**Issue by sss-CRS-sss** [EOSIO/eosjs#129]
I'm trying to create an account using the code of the previous version:
`eos_obj.transaction(tr => {
        tr.newaccount({
          creator: creator_name,
          name: new_name,
          owner: owner_key,
          active: active_key
        });
        tr.buyrambytes({
          payer: creator_name,
          receiver: new_name,
          bytes: 3100
        });
        tr.delegatebw({
          from: creator_name,
          receiver: new_name,
          stake_net_quantity: '0.0001 '+token_name,
          stake_cpu_quantity: '0.0001 '+token_name,
          transfer: 0
        });
      }, callback
    )`
but got error "assertion failure with message: **must purchase a positive amount**"

**Comment by ItVen** [comment]
Same issue

**Comment by jcalfee** [comment]
It has something to do with the market and `buyrambytes` .. Are you using a testnet?

```c++
   void system_contract::buyrambytes( account_name payer, account_name receiver, uint32_t bytes ) {
      auto itr = _rammarket.find(S(4,RAMCORE));
      auto tmp = *itr;
      auto eosout = tmp.convert( asset(bytes,S(0,RAM)), CORE_SYMBOL );

      buyram( payer, receiver, eosout );
   }


   /**
    *  When buying ram the payer irreversiblly transfers quant to system contract and only
    *  the receiver may reclaim the tokens via the sellram action. The receiver pays for the
    *  storage of all database records associated with this action.
    *
    *  RAM is a scarce resource whose supply is defined by global properties max_ram_size. RAM is
    *  priced using the bancor algorithm such that price-per-byte with a constant reserve ratio of 100:1.
    */
   void system_contract::buyram( account_name payer, account_name receiver, asset quant )
   {
      require_auth( payer );
      eosio_assert( quant.amount > 0, "must purchase a positive amount" );
     // ...
```
