### ISSUE TITLE
Available username characters

### ISSUE THREAD

**Issue by Aluman** [EOSIO/eosjs#137]
Why only this '.12345abcdefghijklmnopqrstuvwxyz' characters available for user name? In result I can't use names like 'user6', 'user7' etc. 
[https://github.com/EOSIO/eosjs/blob/master/src/format.js#L47](https://github.com/EOSIO/eosjs/blob/master/src/format.js#L47)

**Comment by jcalfee** [comment]
This is what is used on the back end.. Names get compressed into a uint64 for efficiency.  So limiting the character set like that gives you more total characters..

**Comment by robertkowalski** [comment]
hm, is it 13 or 12?

https://github.com/EOSIO/eosjs/blob/301654d85ca6ec028739a142f37850e7aad2f835/src/format.js#L66-L75

**Comment by robertkowalski** [comment]
is this the configuration for the main net launch? 

i thought it was exactly 12 chars and excluding the dot. the current code includes dot and has no minimum char limit. also it allows 13 chars.

**Comment by jcalfee** [comment]
13 but the last letter can't be over `j` .. so limiting to 12 is going to be the way to go..
https://github.com/EOSIO/eosjs/blob/v13.0.0/src/format.test.js#L13-L14

**Comment by heifner** [comment]
The exactly 12 chars is enforced in the eosio.system contract:
https://github.com/EOSIO/eos/blob/master/contracts/eosio.system/eosio.system.cpp#L130

It was added along with name bidding to prevent name squatting.
