### ISSUE TITLE
how eosjs get table record by primary key？？ 

### ISSUE THREAD

**Issue by healthwallet** [EOSIO/eosjs#138]
var code='liontable';
        var table='accounteos';
        (this.$gobal.eos.getTableRows(true,code,'liontable',table).then(function (value) {
          console.log(value);
          for( var j = 0; j < value.rows.length; j++) {
              if(value.rows[j].ID == 10)
              {
                console.log(value.rows[j]);
              }
          }

if i write like this ，it can't get data，the primary key of my table is ID（uint_t） 
 (this.$gobal.eos.getTableRows(true,code,10,table).then(function (value)

**Comment by jcalfee** [comment]
Looks like you need a `table_key` after table:
```js
// json, code, scope, table, table_key
eos.getTableRows(true, code, 'liontable', table, tableKey)
```

**Comment by healthwallet** [comment]
I add the table_key para,but i get all of the table ,not the  primary key data ,why ??
thany you.

**Comment by jcalfee** [comment]
Yes, this could be a bug .. A core dev will try to look at it today.

**Comment by jcalfee** [comment]
possibly related: https://github.com/EOSIO/eosjs/issues/138

**Comment by jcalfee** [comment]
possibly related: https://github.com/EOSIO/eosjs/issues/147

**Comment by jcalfee** [comment]
I got some feedback:  "Well seeing how table_key is not used in our software anywhere it can be whatever you want ;)"  .. he says 147 may be the same thing..

I'm thinking it must your implementation in your smart contract.

**Comment by angelol** [comment]
So that answer means it's not currently possible to fetch a database record by ID?

Is there a plan to add this functionality?

Will it also be possible to find by secondary indexes?

**Comment by chris-allnutt** [comment]
@angelol the table in a contract is not a traditional database, you can't query it as such either.  If you have a need to index and search the data I would recommend cacheing the data to a datastore on your end in a traditional db or document db

**Comment by angelol** [comment]
@chris-allnutt Well, it is advertised as a fully featured database. I quote from the [documentation wiki](https://github.com/EOSIO/eos/wiki/Persistence-API#the-eosio-multi-index-api):

> The EOSIO Multi-Index API a is patterned after Boost Multi-Index Containers. This API provides a model for object storage with rich retrieval capabilities, enabling the use of multiple indices with different sorting and access semantics.

So clearly, the functionality is there and can be accessed from within a smart contract. Is there a reason as to why not to expose that functionality via eosjs?

**Comment by angelol** [comment]
I just realized, fetching a database record by ID works when using lower_bound and upper_bound. The name of the key can be given in the table_key parameter.

This works:
`eos.getTableRows({json:true, scope: account, code: contract,  table: table, limit:1, table_key: 'id', lower_bound: id, upper_bound: id+1}).then(res => {
		let row = res.rows[0];
 });
`

**Comment by chris-allnutt** [comment]
I believe that is for use in contracts "The EOSIO Multi-Index API provides a C++ interface to the EOSIO database" . I don't know what would be involved to expose that via RPC but you could ask for it in the eos repository.

**Comment by cipherzzz** [comment]
I agree, this is kindof a pain - I had to end up doing this:
```
getGrades(school_id) {
        this.props.eos.getTableRows({
          "json": true,
          "scope": 'admin',
          "code": 'lottery.code',
          "table": "grade",
          "table_key": 'school_key',
          "lower_bound": school_id,
        }).then(result => {
          const filteredRows = result.rows.filter((grade)=> grade.schoolfk == school_id)  
          console.log(JSON.stringify(filteredRows))
          this.setState({grades: filteredRows})
        }).catch((error) =>{
          this.setState(error)
        })
      }
```

**Comment by cipherzzz** [comment]
@MessyComposer - How do you return data from the smart contract action? I didn't know you could return data from an action and had to query tables via the methods above?

**Comment by jcalfee** [comment]
Release eosjs@16.0.0 adds two parameters to get_table_rows .. `key_type` and `index_position` ..

**Comment by ajose01** [comment]
@jcalfee  I'm still learning how to form the requests. any documentation on how to use key_type / index_position? 🙏

**Comment by samkirton** [comment]
Anyone still struggling with getting rows by or pagination by i64 primary key, please see the answer at #154
