### ISSUE TITLE
FC Exception encountered while processing chain.push_transaction: 3090003 unsatisfied_authorization: provided keys, permissions, and delays do not satisfy declared authorizations

### ISSUE THREAD

**Issue by lingyiliu016** [EOSIO/eosjs#149]
when I run `node pingpong.js` , nodeos process throw errors:
<img width="985" alt="20180531175226" src="https://user-images.githubusercontent.com/27277897/40775990-0bba51d4-64fc-11e8-891a-dde875b357d3.png">
This is my pingpong.js file content:
<img width="952" alt="20180531175341" src="https://user-images.githubusercontent.com/27277897/40776005-1869897c-64fc-11e8-9000-93eece55fee9.png">
This is my smart contract code:
<img width="569" alt="20180531175835" src="https://user-images.githubusercontent.com/27277897/40776058-477527ee-64fc-11e8-80ee-56abd0094076.png">
after I run `node pingpong.js`, error occured!
<img width="989" alt="20180531180045" src="https://user-images.githubusercontent.com/27277897/40776177-929e02b8-64fc-11e8-92a6-73cf25031de1.png">
what's the matter? what should I do?

**Comment by jcalfee** [comment]
Probably a version miss-match .. several changes made the signature hash different.. 

The README version table is working, the Travis builds show more details.. It is probably not your contract though it is versions .. reinstall eosjs etc..

You can check this too:
```js
> Eos.version
'13.0.1'
```

possibly related: https://github.com/EOSIO/eosjs/issues/130

**Comment by jcalfee** [comment]
I confirmed that the default chainId below matches the build from the dawn-v4.2.0 tag in EOSIO/eos...

> 706a7ddd808de9fc2b8879904f3b392256c83104c1d544b38302cc07d9fca477

Also matches the node that starts under `docker/up.sh`

**Comment by leordev** [comment]
Same error here trying to push transactions to Jungle Testnet. The strange thing is that my local single node it works. But we are in the same version: 

- Jungle Testnet 1.0.1
- my local node 1.0.1
- eosjs version 14.1.0

Any ideas? @jcalfee @ansigroup 

You can just try to access http://monstereos-jungle.s3.amazonaws.com/index.html, enter with any Junglenet Account and try to add a new monster. Then will receive: 

```
POST http://dev.cryptolions.io:38888/v1/chain/push_transaction 500 (Internal Server Error)
file:"authorization_manager.cpp"
line_number:405
message:"transaction declares authority '{"actor":"leordeveosio","permission":"active"}', but does not have signatures for it under a provided delay of 0 ms"
method:"check_authorization"
```

From `cleos` it works perfectly. (and also eosjs with my local single node)

**Comment by ItVen** [comment]
I have same err:
[push_transaction error] '{"code":500,"message":"Internal Service Error","error":{"code":3090003,"name":"unsatisfied_authorization","what":"provided keys, permissions, and delays do not satisfy declared authorizations","details":[{"message":"transaction declares authority '{\"actor\":\"banker\",\"permission\":\"active\"}', but does not have signatures for it under a provided delay of 0 ms","file":"authorization_manager.cpp","line_number":405,"method":"check_authorization"}]}}', transaction 'a4251a5be4700d7a765800000000014011c8d3d10a918e00809286a96cd44501000000005c05a73900000000a8ed323208000000005c05a73900'
write-api.js:692:23

**Comment by minami-choi** [comment]
I have same error
write-api.js:737 [push_transaction error] '{"code":500,"message":"Internal Service Error","error":{"code":3090003,"name":"unsatisfied_authorization","what":"provided keys, permissions, and delays do not satisfy declared authorizations","details":[]}}', transaction 'e8103f5b2f7c4ffbb890000000000100a6823403ea3055000000572d3ccdcd01e06843663a29305500000000a8ed323229e06843663a293055f063c55429a9b663010000000000000000454f53000000000877616e6e6162697400'

**Comment by bkawk** [comment]
Same issue reported here https://github.com/EOSIO/eosjs/issues/248
