### ISSUE TITLE
Please make an official release of v13.1.0 with build eos.js file

### ISSUE THREAD

**Issue by noisy** [EOSIO/eosjs#153]
Tokenika prepared a tool for a community: _Secure EOS Block Producers Voting_

https://github.com/tokenika/secure-bp-voting

Our goal was to prepare a minimalistic and simple to audit tool, which would allow people to vote for block producers. 

Previously we were using `eos.js` file directly from github release page, like this:

    <script src="https://github.com/EOSIO/eosjs/releases/download/v13.0.0/eos.js"></script>

Thanks to that, no one would need to trust us, that we didn't altered locally build version of `eos.js`

Last release do not contain `eos.js` file:

![selection_532](https://user-images.githubusercontent.com/201263/40815421-a99b2c76-6546-11e8-8757-aadca74cc9d9.png)

@jcalfee could you update latest release **or maybe point out to other official source (CDN) where latest release is hosted?

**Comment by jcalfee** [comment]
Added: https://github.com/EOSIO/eosjs/releases/tag/v13.1.0

I'll make sure this gets done on future releases .. thanks.
