### ISSUE TITLE
How should I set access-control-allow-headers

### ISSUE THREAD

**Issue by yankunsam** [EOSIO/eosjs#156]
No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080'

**Comment by chris-allnutt** [comment]
@yankunsam add the AC headers to your endpoint, or disable CORS for local testing.

**Comment by yankunsam** [comment]
@chris-allnutt  Thanks. Can you give me an example? I am not familiar with it.

**Comment by jcalfee** [comment]
There are lots of how tos on the web .. There are other cors  issues in this repo too ..  https://github.com/EOSIO/eosjs/issues/67
