### ISSUE TITLE
chain_id mismatch

### ISSUE THREAD

**Issue by nsjames** [EOSIO/eosjs#158]
eosjs: `14.0.0`
EOSIO: `1.0.0`

I am getting an assertion error about a wrong chain id, however the expected id in the assertion is incorrect for the given chain, and transactions sent to the chain validate and are accepted regardless of the error.

```
AssertionError {name: "AssertionError", actual: "01750cf763fbac963c344639d96ce503eadbf045aa7e4da67813290673112fd7", expected: "cf057bbfb72640471fd910bcb67639c22df9f92470936cddc1ade0e2f2e7dc4f",
```

Here is the actual `getInfo({})` result from the network panel in chrome:

```
{
    ....
    chain_id:"01750cf763fbac963c344639d96ce503eadbf045aa7e4da67813290673112fd7"
    head_block_id:"0000c0c329a4b79f59d47d168c9f840407a6eac0f593083a698467ddb1b63758",
    ....
}
```

![image](https://user-images.githubusercontent.com/10360675/40871577-cfda7198-6646-11e8-8709-c6f6862fa911.png)

![image](https://user-images.githubusercontent.com/10360675/40871585-e127fae2-6646-11e8-9de9-f6caa640dc73.png)

**Comment by jcalfee** [comment]
Are you constructing Eos somewhere else without specifying the chainId you want to use?  Maybe you have an instance that is correct and that is the one your using to transact with..

Strange, the chainId I'm using comes from the docker v1.0.0 image and there is no assertion errors in the [log]](https://travis-ci.org/EOSIO/eosjs/builds/387083502?utm_source=github_status&utm_medium=notification).

**Comment by nsjames** [comment]
Ah yes, indeed.
I think this should be bypassable. 

As a general workflow I use two instances of eosjs, one which only reads and one which only writes. The read-only instance never actually needs to validate the chain id and fetching the info simply to build the constructor adds network overhead.

**Comment by nsjames** [comment]
Perhaps it could check for the existence of the `chainId` in the options and only assert if non-empty.

**Comment by jcalfee** [comment]
```js
> eosReadOnly = Eos.modules.api()
{ getCurrencyBalance: [Function],
  getCurrencyStats: [Function],
  getProducers: [Function],
  getInfo: [Function],
  getBlock: [Function],
  getAccount: [Function],
  getCode: [Function],
  getTableRows: [Function],
  abiJsonToBin: [Function],
  abiBinToJson: [Function],
  getRequiredKeys: [Function],
  pushBlock: [Function],
  pushTransaction: [Function],
  pushTransactions: [Function],
  getActions: [Function],
  getControlledAccounts: [Function],
  getKeyAccounts: [Function],
  getTransaction: [Function],
  createTransaction: [Function],
  api: { createTransaction: [Function: createTransaction] } }

```

**Comment by jcalfee** [comment]
changed to warning: https://github.com/EOSIO/eosjs/commit/d775cabf13872dbde1e175eb6712ea0377c5140a
