### ISSUE TITLE
Exception when updating permission in EOS 1.0.1 with eosjs 14.1 AND eosjs 14.1.1

### ISSUE THREAD

**Issue by theponpon** [EOSIO/eosjs#160]
The attached code will produce the following error message:

 TypeError: Cannot read property 'threshold' of undefined authority.threshold updateauth.auth action.data transaction.actions
index.js:121

[test_permissions.txt](https://github.com/EOSIO/eosjs/files/2065521/test_permissions.txt)

**Comment by ycryptx** [comment]
@theponpon  getting the same error

**Comment by shishi614** [comment]
new version must be require deploy eosio.token

**Comment by jcalfee** [comment]
These fields were removed:
>recovery: 'eosio',
>            deposit: '0 EOS'}

See newaccount in the README..

Look at the usage for updateauth:

```js
> eos.updateauth()
CONTRACT
eosio

FUNCTION
updateauth

PARAMETERS
{
    "account": "account_name",
    "permission": "permission_name",
    "parent": "permission_name",
    "auth": "authority"
}

EXAMPLE
{
    "account": "",
    "permission": "",
    "parent": "",
    "auth": {
        "threshold": 0,
        "keys": [
            {
                "key": "EOS6MRy..",
                "weight": 0
            }
        ],
        "accounts": [
            {
                "permission": {
                    "actor": "",
                    "permission": ""
                },
                "weight": 0
            }
        ],
        "waits": [
            {
                "wait_sec": 0,
                "weight": 0
            }
        ]
    }
}

```

**Comment by jcalfee** [comment]
By the way, if any array is empty you can omit it ..

**Comment by theponpon** [comment]
"auth" instead of "data"!
It works now! I feel stupid!
Thanks a lot for helping me find my mistake!

Regards

Pierre
