### ISSUE TITLE
how to get the eosjs error ???

### ISSUE THREAD

**Issue by healthwallet** [EOSIO/eosjs#161]
try {
          this.$gobal.eos.transaction("liontoken",con=>{
            con.transfer("liontoken","eosio","10 LON","transfer")

          }).then(function (value){
            console.log(value);
            return value;
          });
        }
        catch (e) {
          console.log(e);
        }

Error: {"code":500,"message":"Internal Service Error","error":{"code":3060002,"name":"account_query_exception","what":"Account Query Exception","details":[{"message":"Fail to retrieve account for eosio.token","file":"chain_plugin.cpp","line_number":561,"method":"get_abi"}]}}
    at eval (webpack-internal:///./node_modules/eosjs-api/lib/apigen.js:115:23)
  (anonymous function)	
  callback	
  (anonymous function)	
Uncaught (in promise) Error: {"code":500,"message":"Internal Service Error","error":{"code":3060002,"name":"account_query_exception","what":"Account Query Exception","details":[{"message":"Fail to retrieve account for eosio.token","file":"chain_plugin.cpp","line_number":561,"method":"get_abi"}]}}
  (anonymous function)	

**# console output error,how to get the error in program,the catch and value can't get???**

**Comment by MrToph** [comment]
I would also like to know this. Did you figure it out?

**Comment by jcalfee** [comment]
```js
this.$gobal.eos.transaction("liontoken",con=>{
        con.transfer("liontoken","eosio","10 LON","transfer")

      }).then(function (value){
        console.log(value);
        return value;
      }).catch(function (e) {
      console.log(e);
    })
```
