### ISSUE TITLE
In what situation declaring variables without keyword is acceptable?

### ISSUE THREAD

**Issue by wintercounter** [EOSIO/eosjs#163]
As I was going through the examples and I noticed that variables are being declared without keyword (var/const/let). In what situation is that considered as a viable solution or what is the exact reason/purpose behind this decision? I'm a JS developer since 15 years now and never heard/saw anything about this being a good practice. I know in NodeJS it'll have it's own module scope (execution context), still this is a very, very **BAD PRACTICE**.

**Comment by jcalfee** [comment]
you can re-run the commands without getting any errors

**Comment by wintercounter** [comment]
??

**Comment by chris-allnutt** [comment]
@wintercounter if you would like to contribute adding usage where you feel it is valuable we are open to accepting pull requests to improve our examples
