### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by quocle108** [EOSIO/eosjs#168]
Hi all,

I tried to get Block Infor following README.md instruction. But there is an issue. Anyone know how to solve it?

> Failed to load http://127.0.0.1:8888/v1/chain/get_info: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by yepp4you** [comment]
config.ini

**Comment by quocle108** [comment]
I used Docker and also tried to modify the config.ini in Docker folder. But the issue still happen
