### ISSUE TITLE
npm run build_browser fails

### ISSUE THREAD

**Issue by filipniziol** [EOSIO/eosjs#171]
Could you add eos.js file to package?

**Comment by PIshaaa** [comment]
You can add eosjs by command : `npm install eosjs --save`.

so, it will be added to package.json

**Comment by filipniziol** [comment]
Not sure how it should help but it did not

**Comment by filipniziol** [comment]
When running npm run build_browser I get a bunch of errors

> eosjs@14.1.1 build_browser /home/filipniziol/eosjs
> npm run build && mkdir -p dist && browserify -o dist/eos.js -s Eos lib/index.js


> eosjs@14.1.1 build /home/filipniziol/eosjs
> babel --copy-files src --out-dir lib

/usr/bin/env: ‘node’: No such file or directory

npm ERR! Linux 4.13.0-41-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! eosjs@14.1.1 build: `babel --copy-files src --out-dir lib`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the eosjs@14.1.1 build script 'babel --copy-files src --out-dir lib'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the eosjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel --copy-files src --out-dir lib
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs eosjs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls eosjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/filipniziol/eosjs/npm-debug.log

npm ERR! Linux 4.13.0-41-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build_browser"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! eosjs@14.1.1 build_browser: `npm run build && mkdir -p dist && browserify -o dist/eos.js -s Eos lib/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the eosjs@14.1.1 build_browser script 'npm run build && mkdir -p dist && browserify -o dist/eos.js -s Eos lib/index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the eosjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build && mkdir -p dist && browserify -o dist/eos.js -s Eos lib/index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs eosjs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls eosjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/filipniziol/eosjs/npm-debug.log

**Comment by angelol** [comment]
You need to install node.js

**Comment by filipniziol** [comment]
Node.js is istalled. To be honest: I managed to run the script only inside docker container. On Ubuntu 16.04 does not work. I believe you should check whether it works on the systems you claim it to work or to update the instructions.

**Comment by angelol** [comment]
Sorry Filip, in the beginning of your messages, it clearly says "/usr/bin/env: ‘node’: No such file or directory", which means node is not or at least not properly installed.

**Comment by filipniziol** [comment]
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the eosjs package,

**Comment by fundurian** [comment]
same error, please help, i tried 
1. nodejs -v
- it say v4.2.6
2. apt-get install nodejs
Reading package lists... Done
Building dependency tree       
Reading state information... Done
nodejs is already the newest version (4.2.6~dfsg-1ubuntu4.1).
nodejs set to manually installed.
The following package was automatically installed and is no longer required:
  grub-pc-bin
Use 'apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 8 not upgraded.

then i tried again and still fail, please help

**Comment by jcalfee** [comment]
eos.js is added to the github releases tab:
https://github.com/EOSIO/eosjs/releases

We will also be setting up a CDN deployment..
