### ISSUE TITLE
question: how to WATCH for events/logs similar to web3

### ISSUE THREAD

**Issue by kasperfish** [EOSIO/eosjs#175]
Hi I want to update the gui when something happens on the blockchain.  In web3 I can do "watch". How does this work with eosjs? I can probably do this with a poll function but prefer something built in...
Is this the way I should implement this?
`setInterval(function(){ eos.getActions('CONTRACT_ACCOUNT_NAME').then(...) }, 1000);`

**Comment by jcalfee** [comment]
Correct, it is getActions but you also need to enable filter-on in nodeosd..  This is wide open and will use RAM but should be OK in development:  `--filter-on "*"`
