### ISSUE TITLE
Getting 2x the same error returned from invalid transactions.

### ISSUE THREAD

**Issue by kasperfish** [EOSIO/eosjs#177]
I'm getting 2 duplicate error messages returned from invalid transactions. I'm able to catch one of the two but the the other seems to be uncatchable. 
![image](https://user-images.githubusercontent.com/5130772/41195723-59018e1a-6c33-11e8-9254-4b5a52eee7f6.png)

![image](https://user-images.githubusercontent.com/5130772/41195728-6d64082e-6c33-11e8-8ab6-326495123199.png)

**Comment by jcalfee** [comment]
This should turn it off: 
```js
config.logger: {
    error: () => {}
}
```
https://github.com/eosio/eosjs-api#configuration

**Comment by kasperfish** [comment]
thanks for the suggestion but it doesn't seem to help.
![image](https://user-images.githubusercontent.com/5130772/41196419-fbe6362e-6c3f-11e8-988e-dbc7568f7956.png)

**Comment by jcalfee** [comment]
The logger is only 1/2 implemented .. I need go in and standardize it so it applies to logging in all packages.  I'll reference this ticket on those changes.

**Comment by jcalfee** [comment]
The most efficient way to turn off a logging level is to use null.  Re-direct by providing a function.

`config.logger: {error: null}`

released: eosjs@14.2.0
