### ISSUE TITLE
Base field in action abi type is ignored

### ISSUE THREAD

**Issue by sim31** [EOSIO/eosjs#18]
You can use inheritance in EOS abi, like so:
```
 structs: [
    {
      "name": "action1",
      "base": "",
      "fields": {
        "field1": "string",
        "field2": "string"
      }
    },{
       "name": "action2",
       "base": "action1",
       "fields": {
         "field3": "account_name",
       }
   ]
   "actions": [
    "action_name": "action1",
      "type": "action1"
    },{
      "action_name": "action2",
      "type": "action2"
    }
   ]
```
I would expect to be able to use contract with this abi like this:
```
eos.contract('contr').then( c => { c.action2("1", "2", "3" });

```
But then I get this error:
```
Uncaught TypeError: action2 is expecting 1 parameters but 3 where provided
```

**Comment by jcalfee** [comment]
npm release eosjs@6.1.1

**Comment by jcalfee** [comment]
Please test the upgrade with `npm i eosjs@6.1.1` or `npm i eosjs@prerelease` .. I have not tagged it as latest yet..

**Comment by sim31** [comment]
Now it complains that it's expecting 2 parameters instead of 3 (before it was expecting 1). Also shouldn't calling function with no parameters print usage information? I get unknown type error when I try to do that with contract actions.

**Comment by jcalfee** [comment]
Version eosjs@6.1.4 released..

**Comment by NewETown** [comment]
@jcalfee not sure if this is related, every time I try to access the "currency" contract I'm seeing this (previous 6.0.x did not give me this error)

Unhandled promise rejection (rejection id: 1): Error: [
    "Expecting string in transfer.fields.0",
    "Expecting string in transfer.fields.1",
    "Expecting string in transfer.fields.2",
    "Expecting string in transfer.fields.3",
    "Expecting string in issue.fields.0",
    "Expecting string in issue.fields.1",
    "Expecting string in account.fields.0",
    "Expecting string in account.fields.1",
    "Expecting string in currency_stats.fields.0",
    "Expecting string in currency_stats.fields.1",
    "Missing [object Object] in transfer.fields.0",
    "Missing [object Object] in transfer.fields.1",
    "Missing [object Object] in transfer.fields.2",
    "Missing [object Object] in transfer.fields.3",
    "Missing [object Object] in issue.fields.0",
    "Missing [object Object] in issue.fields.1",
    "Missing [object Object] in account.fields.0",
    "Missing [object Object] in account.fields.1",
    "Missing [object Object] in currency_stats.fields.0",
    "Missing [object Object] in currency_stats.fields.1"
]

**Comment by kesar** [comment]
I am having the same issue than the previous post in my contracts with string type

**Comment by jcalfee** [comment]
Please try with the latest eosjs release and eosd dawn2..  I just tested the currency contract and it is working now.

**Comment by jcalfee** [comment]
It is for 2.x only .. I'll update https://github.com/EOSIO/eosjs/issues/25 as I get 3.x working..

**Comment by jcalfee** [comment]
Fixed in dawn3 .. it is being tested now, for now here are the directions:

https://github.com/EOSIO/eosjs/issues/25#issuecomment-371855546

Also be sure to view the README.md from the dawn3 branch..
