### ISSUE TITLE
is there any working demo how to use scatter with eosjs ?

### ISSUE THREAD

**Issue by alzozov** [EOSIO/eosjs#180]
Need to call eosjs contract actions using Scatter identity: user logins with scatter and browser can interuct through this identity through eosjs. Any example demo?

**Comment by jcalfee** [comment]
What do you mean by this?
>interuct through this identity through eosjs

**Comment by k26dr** [comment]
github.com/LibertyBlock/eos-voting

**Comment by chris-allnutt** [comment]
@alzozov scatter is its own product, I believe it uses eosjs internally but I'm unaware of any api's it exposes in the browser.

**Comment by jcalfee** [comment]
Here is a working sight and demo:
https://youtu.be/18UfWKxnSYM
