### ISSUE TITLE
Error 3010011: Invalid packed transaction

### ISSUE THREAD

**Issue by lingyiliu016** [EOSIO/eosjs#184]
I wrote a function to deploy contract on blockchain.
Code shows as bellow(js file of deploying contract).
<img width="1069" alt="20180611201957" src="https://user-images.githubusercontent.com/27277897/41231197-de378634-6db4-11e8-8d89-37e4e7460676.png">
Here is my contract ping.cpp
<img width="544" alt="20180611202218" src="https://user-images.githubusercontent.com/27277897/41231281-2ca33822-6db5-11e8-8cc7-87224cbabedb.png">
when I deploy the contract on blockchain, No exception occur! But when I push action by cleos ,error occured!
details as follow!
<img width="1160" alt="20180611202754" src="https://user-images.githubusercontent.com/27277897/41231553-f70a27e2-6db5-11e8-8499-417dc19d6056.png">
what's wrong in js file?

**Comment by jcalfee** [comment]
Your `Eos.version` is old..  Check the version table in the README ..
