### ISSUE TITLE
Signing of transactions

### ISSUE THREAD

**Issue by anil215** [EOSIO/eosjs#185]
I am using eosjs for my application which involves performing some txs. I did setup my local node and broadcasting txs through it which are working correctly. My question here is whether the signing and serialisation of txs being done locally and then the signed tx is broadcasted though the node whose httpEndpoint i provided ? The private key is not exposed to the network right. I am pretty sure the second thing is not happening but would be pretty helpful if you could provide some links to the source code to prove it.

Thanks a lot .

**Comment by chris-allnutt** [comment]
@anil215 it is signed locally and then transmitted the key never leaves your browser.

**Comment by jcalfee** [comment]
Here is the one and only place of serialization and signing ..  
https://github.com/EOSIO/eosjs/blob/v14.1.1/src/write-api.js#L406-L419

The signing is implementation is plug-able.  Here is the default.  Keep in mind the sign function comes from eosjs-ecc: `const {sign} = ecc`..

https://github.com/EOSIO/eosjs/blob/v14.1.1/src/index.js#L201

Let me know if you have any more questions..

**Comment by wannabit-jayb** [comment]
@jcalfee Do you know any java version of eosjs-ecc?
I am trying to implement signing transaction and sending the signed transaction to one of the BP nodes in java.

**Comment by chris-allnutt** [comment]
@wannabit-jayb there is no java version we know of.

**Comment by jcalfee** [comment]
Java can run many language like javascript, not sure if it maps everything though like the crypto apis..
