### ISSUE TITLE
Ensure that your packed transaction JSON follows the following format!

### ISSUE THREAD

**Issue by lingyiliu016** [EOSIO/eosjs#187]
When I set the contract on blockchain in version eos@dawn4.0, and call the action of the contract, everything was normal. but when I set the same contract on blockchain in version EOS1.0, There is nothing wrong. But when I call action on EOS1.0, errors occured!
<img width="1162" alt="20180613120211" src="https://user-images.githubusercontent.com/27277897/41329676-a167be4c-6f01-11e8-875b-27ff6e562e03.png">
what should I do? I don't know how solve this issue.

**Comment by jcalfee** [comment]
upgrade eosjs .. looks like you figured it out
