### ISSUE TITLE
asking for assist - encodeName undefined in browser

### ISSUE THREAD

**Issue by gpmn** [EOSIO/eosjs#190]
asking for help!
I build eosjs as instruction : npm run build_browser
but my code got such error when call encodeName,
I tried these:
    eos.format.encodeName 
    format.encodeName
    encodeName
how to use encodeName in browser versoin?

**Comment by jcalfee** [comment]
https://github.com/EOSIO/eosjs/blob/v14.1.1/dist/index.html#L4

```js
Eos.modules.format.encodeName('alice')
```

**Comment by jcalfee** [comment]
Notice the E in `Eos` is capitol ..  encodeName is static and does not need a configured instance of eos ..

**Comment by gpmn** [comment]
solved, Haha!
Thank you!
