### ISSUE TITLE
Better support for offline transactions

### ISSUE THREAD

**Issue by jcalfee** [EOSIO/eosjs#191]
- [x] Nullifying the httpEndpoint can be used to disable code such as the chainId test..  This would be the preferred configuration for cold-storage for example.
- [x] `eos.transaction` should allow passing of transaction headers with a priority over config.transactionHeaders

**Comment by jcalfee** [comment]
finished, waiting for new release

**Comment by ridewindx** [comment]
Waiting for release, eagerly.

**Comment by jcalfee** [comment]
After the logging is fixed..  I see one more thing.

**Comment by jcalfee** [comment]
released: eosjs@14.2.0
