### ISSUE TITLE
local node state and unconfirmed data

### ISSUE THREAD

**Issue by robertkowalski** [EOSIO/eosjs#192]
Hi folks,

I wonder what the best practice is in this common use case. I have a contract which stores basic data. Let's say a candy store. 

I issue `100 CANDY`, give it `user1` and transfer it to my Candystore contract. This happens on a **local node connected to the main net**

Ok, so my candystore contract accepts the 100 CANDY and stores them in a table.

When I run a get table now i get the result from my local node, which is not confirmed by the netowrk yet.

How can i ensure that something like getTableRows will return data that ne network confirmed and not just local data? Are there best practices?

**Comment by jcalfee** [comment]
@heifner can you confirm, does get_table_rows only operate on the last irreversible block?  
Reference: https://github.com/EOSIO/eos/blob/c55061b52acda38b969c23e77ebc02d1d3de56be/plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp#L286

@robertkowalski this is organic candy right?

**Comment by jcalfee** [comment]
I'm informed get table does not operate on the last irretrievable block and that there is no good solution for this right now.  It is however being worked on..

**Comment by robertkowalski** [comment]
thanks! of course they are! organic and vegan:

--- 
# raw chocolate balls

- 50g blended cashews
- 50g blended almonds
- 8 dats
- 2 tsp cocoa, non sugared and oil removed (the real cocoa) -- i usually take 1 tsp cocoa and 1 tsp carob
- cocos flakes for rolling (optional)

blend and mix everything well. roll small balls. I usually add 1 tbsp chia seeds and 1tbsp cocos oil, but this is optional.

tip: blend dats and nuts seperately, i just broke my blender :D

**Comment by jcalfee** [comment]
I have created a request to get updates on this .. you can follow here: https://github.com/EOSIO/eos/issues/4191
