### ISSUE TITLE
listbw api

### ISSUE THREAD

**Issue by crazybits** [EOSIO/eosjs#194]
does eosjs support the following cleos api? if not ,when could eosjs support this api

`./cleos system listbw`

**Comment by jcalfee** [comment]
Yes .. cleos is calling get_table_rows here:
```js
   list_bw_subcommand(CLI::App* actionRoot) {
      auto list_bw = actionRoot->add_subcommand("listbw", localized("List delegated bandwidth"));
      list_bw->add_option("account", account, localized("The account delegated bandwidth"))->required();
      list_bw->add_flag("--json,-j", print_json, localized("Output in JSON format") );

      list_bw->set_callback([this] {
            //get entire table in scope of user account
            auto result = call(get_table_func, fc::mutable_variant_object("json", true)
                               ("code", name(config::system_account_name).to_string())
                               ("scope", account.to_string())
                               ("table", "delband")
            );
```
You have to have the system contract deployed (this is true probably on all testnets and the mainnet):
```bash
cleos set contract eosio contracts/eosio.system -p eosio@active
```
Then this should be the same call (replace inita):
```js
eos.getTableRows(true, 'eosio', 'inita', 'delband')
```

Let me know if you have to tweak `getTableRows` in any way.  This command not very well understood.  Here is the command again with the defaults:
```js
eos.getTableRows(true, 'eosio', 'inita', 'delband', '', '0', '-1', 10)
```

**Comment by chris-allnutt** [comment]
I believe @jcalfee answer properly handles this request.  Closing for now @crazybits feel free to open this back up if it doesn't resolve your problem.
