### ISSUE TITLE
Browser Support

### ISSUE THREAD

**Issue by JKing-B16** [EOSIO/eosjs#199]
I'm trying to get this running in a browser, but I keep running into errors in the dependencies like:

global is not defined 
in randombytes/browser.js

Is there a trick to making this work? My current target is an Angular 6 application.

**Comment by jcalfee** [comment]
I'm using a recent enough version of randombytes.  Maybe your browser does not support es2015..

This looks like the discussion for that issue:
https://github.com/crypto-browserify/randombytes/issues/5

**Comment by JKing-B16** [comment]
I'm trying to use the eosjs library in an Angular 6 project. I'm testing in Chrome 67. So far I've added the following to the index.html:
`<script> var global=window; </script>`

That fixes the issue above, but only breaks cipher-base which relies on the `Transform` function of _stream_, which causes the _inherit_ method to throw the following error:

`Uncaught TypeError: Cannot read property 'prototype' of undefined`

I think the issue revolves around the crypto libraries making use of NodeJS modules that are not available in the browser. It looks like _browserify_ attempts to add support for many of these modules, but I can't determine how to integrate them into a webpack based library like Angular.

**Comment by JKing-B16** [comment]
I think I located the issue. I was simply trying to use _eosjs_ via _npm_, however, the npm build is purely for _nodejs_ environments. I added eosjs as a submodule of my project and ran:
`npm run build_browser`
This got me an *eos.js* file that I could link into my project to communicate with my local node. I still have more debugging to do, but I believe this is the right way forward.
It would be nice to have a way to include _eosjs_ in a browser project directly with `npm install` at some point in the future.

**Comment by jcalfee** [comment]
Npm generally packages work with a app stack (webpack, browsersify, etc) .. Npm has all es2015 code though in ./lib but it is separate files.  In the github releases tab I publish eos.js on each release.

In the future we will publish a hashed CDN build too..

**Comment by wushbin** [comment]
Hi, @JKing-B16 
I encounter the same problem as yours. 
How did you solve it?

**Comment by jcalfee** [comment]
I use `npm run build_browser` to create eos.js and publish it to npm .. Here is an example on how to use it:

https://github.com/eosio/eosjs#usage

**Comment by dominic-healid** [comment]
@jcalfee how about for v20?

**Comment by jcalfee** [comment]
I'm not actively working on this now .. I did find this though: https://github.com/EOSIO/eosjs/commit/d30d238f4ac4de0d882c15fa928073b6d1c239db
