### ISSUE TITLE
my dapp's eosjs report chainId mismatch, is it seriously?

### ISSUE THREAD

**Issue by gpmn** [EOSIO/eosjs#201]
I set httpEndpoint as 'http://mainnet.genereos.io'

with command:
'cleos  --wallet-url http://127.0.0.1:8900  -u http://mainnet.genereos.io get info'

report it's chainid is :
"chain_id": "aca376f206b8fc25a6ed44dbdc66547c36c6c33e3a119ffbeaef943642f0e906",

but eosjs blame these :
--------------------------------------------------------------------------
WARN: chainId mismatch, signatures will not match transaction authority. expected cf057bbfb72640471fd910bcb67639c22df9f92470936cddc1ade0e2f2e7dc4f !== actual aca376f206b8fc25a6ed44dbdc66547c36c6c33e3a119ffbeaef943642f0e906
(anonymous) @ eos.js:977
Promise resolved (async)
checkChainId @ eos.js:975
createEos @ eos.js:669
Eos @ eos.js:624
getCredit @ eosmod.js:182
updateCredit @ index.html:476
(anonymous) @ index.html:242
dispatch @ jquery-3.3.1.min.js:2
y.handle @ jquery-3.3.1.min.js:2

**Comment by gpmn** [comment]
solved， just grep and replace it with actual one

**Comment by jcalfee** [comment]
See [usage](https://github.com/eosio/eosjs#usage) .. you can provide the chainId when you create EOS..
