### ISSUE TITLE
How do I get the original arguments from the data in the transaction

### ISSUE THREAD

**Issue by ylic2018** [EOSIO/eosjs#202]
## Now, I have the following data:

>
    {
    "compression": "none",
    "transaction": {
        "expiration": "2018-06-17T12:16:44",
        "ref_block_num": 5998,
        "ref_block_prefix": 241312377,
        "net_usage_words": 0,
        "max_cpu_usage_ms": 0,
        "delay_sec": 0,
        "context_free_actions": [],
        "actions": [
            {
                "account": "eosio",
                "name": "newaccount",
                "authorization": [
                    {
                        "actor": "aaaaaaaaaaaa",
                        "permission": "active"
                    }
                ],
                "data": "608c31c618638c3170ce39e79c73ce3901000000010002c0dab2c9c52ff2050982aa5d773b8c786bb7e4590eca916f4bbdee6c9b7f87080100000001000000010002c0dab2c9c52ff2050982aa5d773b8c786bb7e4590eca916f4bbdee6c9b7f870801000000"
            },
            {
                "account": "eosio",
                "name": "buyrambytes",
                "authorization": [
                    {
                        "actor": "aaaaaaaaaaaa",
                        "permission": "active"
                    }
                ],
                "data": "608c31c618638c3170ce39e79c73ce3900100000"
            },
            {
                "account": "eosio",
                "name": "delegatebw",
                "authorization": [
                    {
                        "actor": "aaaaaaaaaaaa",
                        "permission": "active"
                    }
                ],
                "data": "608c31c618638c3170ce39e79c73ce39010000000000000001454f5300000000010000000000000001454f530000000000"
            }
        ],
        "transaction_extensions": []
    },
    "signatures": [
        "SIG_K1_K5i7vUMWT8hwFoUz4Va8WbzZNZoMP1DN886fefWyKJ7NeDVAZEQqajiNc6eX24f1qdAqnJQkvCawNCgEUrgzRomFY74Gfr"
    ]
}

## Now, I need to use eosjs to get the original arguments from data. Such as:

>
           newaccount:{
                creator: 'aaaaaaaaaaaa',
                name: 'bbbbbbbbbbbb',
                owner: 'EOS6MRZJCu9qCFRhNZZ6jZHJdMN5NVJWHFchGgYdYUT7YeBmgpq51',
                active: 'EOS6MRZJCu9qCFRhNZZ6jZHJdMN5NVJWHFchGgYdYUT7YeBmgpq51'
            }
            buyrambytes:{
                payer: 'aaaaaaaaaaaa',
                receiver: 'bbbbbbbbbbbb',
                bytes: 4096
            }
            delegatebw:{
                from: 'aaaaaaaaaaaa',
                receiver: 'bbbbbbbbbbbb',
                stake_net_quantity: '0.1 EOS',
                stake_cpu_quantity: '0.1 EOS',
                transfer: 0
            })

**Comment by ylic2018** [comment]
@jeremi @dbrock @tholder @spoon16 @datchley

**Comment by chris-allnutt** [comment]
If there is an abi for the contract then you should get it back out the sam as it went in.  Otherwises @jcalfee is there a way @ylic2018 can use fcbuffer to decode the data?

**Comment by jcalfee** [comment]
Yes, I keep trying to move away from hex in that data field, there has been bugs and there is a complication on my end.  In the mean time you can do this for each data field:

```js
eos.fc.fromBuffer('newaccount', data)
```
This also works on your contract after fetching it:
```js
constract.fc.fromBuffer('myaction', data)
```
Here are the examples:
https://github.com/eosio/eosjs#fcbuffer

**Comment by ylic2018** [comment]
@chris-allnutt @jcalfee  Thank you. It's all right.

**Comment by crazybits** [comment]
@jcalfee any way to unpack the proposal tx?

**Comment by chris-allnutt** [comment]
@crazybits best way is to run a node with the MongoDB plugin so you can query the original block.  I believe the history API is being deprecated and using an http endpoint would not include inline actions either which would be necessary if your contract was calling actions on another contract.  The MongoDB plugin stores block contents in JSON so you wouldn't need to unpack them.

**Comment by jcalfee** [comment]
@crazybits `eos.fc.fromBuffer('transaction', data)`
