### ISSUE TITLE
How can I register an account using any public httpEndpoint

### ISSUE THREAD

**Issue by oxfn** [EOSIO/eosjs#204]
How can I register an account using any public httpEndpoint?
For example, https://mainnet.eoscannon.io

Here is what I am trying

```
const eos = Eos({
    chainId: 'aca376f206b8fc25a6ed44dbdc66547c36c6c33e3a119ffbeaef943642f0e906',
    httpEndpoint: 'https://mainnet.eoscannon.io',
    broadcast: true,
    debug: false,
    sign: true,
    expireInSeconds: 60,
    keyProvider: [ 5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3 ], // <- ?????????
});
//const creator = 'eoscannonchn'; // <- ????????
const creator = 'eosio'; // <- ????????
const { PrivateKey, PublicKey } = Eos.modules.ecc;
const d = await PrivateKey.randomKey();
const privkey = d.toWif();
const pubkey = d.toPublic().toString();
await eos.transaction((tr) => {
    tr.newaccount({
        creator,
        name: accountName,
        owner: pubKey,
        active: pubKey,
    });
    tr.buyrambytes({
        payer: creator,
        receiver: accountName,
        bytes: 8192,
    });
});
```

Previously I've tried this at own mainnet node with eosio PK, but without success.

Possibly, I'm getting something wrong and misunderstanding some concepts of EOS, then sorry for dumb question. If so, **please point me to some adequate explanation**

**Comment by crazybits** [comment]
you need you build server side api which could help to create account

**Comment by oxfn** [comment]
@crazybits Do you mean to use my own node? The main question is **where to get creator name and private key**? "eosio" does not seem to be the case

**Comment by iWtbAbh** [comment]
@oxfn If you want to create new account:
1. you must have a account in mainnet 
2. you must provide the private key of the account in keyProvider 
like:
keyProvider: [you account  private key]
const creator = 'your account name'; // <- ????????

**Comment by jcalfee** [comment]
Yea, you have to have an account or buy one from someone.  I'm not aware of a service yet, but it can be as easy as shapeshift where you setup a name and a password then send them some other token or currency to pay for and any small fee they charge..

**Comment by oxfn** [comment]
@crazybits @iWtbAbh @jcalfee Thank you! Finally we've got an account )
