### ISSUE TITLE
Multiple signature in one request using eosjs

### ISSUE THREAD

**Issue by sehgal12** [EOSIO/eosjs#205]
I have written a smart contract in which several action require multiple signature in one request. How to get the transaction signed by say user and admin and push to to the blockchain using eosjs?

**Comment by nsjames** [comment]
You can check out this code if you're using Scatter,
https://github.com/EOSEssentials/Scatter/blob/master/readme.md#multi-part-signatures-involving-the-application-and-an-identity

You can also pass multiple keys into keyProvider or multiple awaited promises into signProvider which converge as a single array
