### ISSUE TITLE
Export module abiToFcSchema

### ISSUE THREAD

**Issue by nsjames** [EOSIO/eosjs#207]
I'm using this inside of Scatter to cache and re-initialize fcbuffer from cached abis. 
Since the `abiToFcSchema` is not exported I'm pulling that function into my code, it would be great if eosjs could export that for use.

**Comment by nsjames** [comment]
https://github.com/EOSIO/eosjs/blob/master/src/abi-cache.js#L46

**Comment by jcalfee** [comment]
Great idea .. I need to so this for cold storage / offline environments so they can bring their own ABI..

**Comment by jcalfee** [comment]
There is an example in the unit test at the bottom https://github.com/EOSIO/eosjs/commit/7d8ba2ac84ddcd1897b63eed4a8d5d9b822404f3

**Comment by nsjames** [comment]
https://github.com/EOSIO/eosjs/blob/master/src/abi-cache.js#L38
You know I love you right? <3

**Comment by jcalfee** [comment]
Here is an example in the README:  https://github.com/EOSIO/eosjs#offline-or-cold-storage-contract

this is released as v15.0.1
