### ISSUE TITLE
Reducing overhead

### ISSUE THREAD

**Issue by nsjames** [EOSIO/eosjs#208]
There's quite a lot of overhead when preparing a transaction which might be able to be minimized by caching prior results within the same call:

![image](https://user-images.githubusercontent.com/10360675/41663792-ecb5953a-74ac-11e8-8d45-7fb884020fdd.png)

4 get_info requests -> 1.2s ( 300ms each )
2 get_code requests -> 1.5s ( 750ms each )

**Comment by jcalfee** [comment]
True .. maybe a timed expiration is a good idea .. get_info should be called only once per transaction and transactions can have multiple actions.  Maybe the actions should cache the ABI for 60 seconds or for at least for the duration of a single transaction.

**Comment by jcalfee** [comment]
Is this performing better now that I'm pulling only the ABI (without the code)?
