### ISSUE TITLE
Suddenly started getting an error on eosjs with Scatter

### ISSUE THREAD

**Issue by eosauthority** [EOSIO/eosjs#210]
Error: Transaction failed.[ "Missing block_timestamp_type in eosio_global_state.fields.last_producer_schedule_update", "Missing block_timestamp_type in eosio_global_state.fields.last_name_close" ] in { "name": "uint64", "checksum160": "fixed_bytes20", "checksum256": "fix........ 

The system was working before, started showing this error just now after the new Scatter update. Was asked by the Scatter team to file a bug here. Let me know if you need anything else.

![image](https://user-images.githubusercontent.com/38717729/41745975-b016435a-75a0-11e8-8cc4-61bc2e027a9d.png)

**Comment by jcalfee** [comment]
Looks like this is a older version of eosjs (and perhaps an older version of scatter) .. Is scatter up-to-date?

**Comment by nsjames** [comment]
Also, can you post the code to get that so I can try to reproduce?

**Comment by eosauthority** [comment]
It used to work for a couple of weeks here, suddenly started getting the errors above
https://eosauthority.com/vote
Just click on the buttons to be given the error at the last step.

**Comment by nsjames** [comment]
When is the last time you updated that eosjs?

Is there a link to the code for that site?

**Comment by eosauthority** [comment]
Thanks @nsjames, that was the issue, updated eosjs weeks ago.

Is there anyway I could just use the eosjs version on scatter without a separate one on the website? Will reduce a point of failure?

**Comment by jcalfee** [comment]
@nsjames keep in mind Eos.version is the value in package.json version .. Somehow this may integrate with your docs or perhaps a warning if you get a new version of scatter it could expect a min version of eosjs.

This is probably off topic, I'll mention just in case.  I plan to deploy eos.js and publish hash like this:
https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity
