### ISSUE TITLE
When push an action that parameter is uint32[]

### ISSUE THREAD

**Issue by yankunsam** [EOSIO/eosjs#213]
It will report "what":"eosio_assert_message assertion failure

➜  oasis-eos node test.js
TypeError: Illegal value: 0 (not an integer) newteam.players = ["0","1"] action.data = {"owner":"user1","banker":"eosio.token","players":["0","1"],"scoresum":0,"cost":"0.0000 SYS","stake":"2.0000 SYS","gameid":0} transaction.actions = [{"account":"eosio","name":"newteam","authorization":[{"actor":"user1","permission":"active"}],"data":{"owner":"user1","banker":"eosio.token","players":["0","1"],"scoresum":0,"cost":"0.0000 SYS","stake":"2.0000 SYS","gameid":0}}]
    at ByteBuffer.module.exports.ByteBufferPrototype.writeUint8 (/Users/sam/Public/oasis-eos/eosjs/node_modules/bytebuffer/dist/bytebuffer-node.js:604:23)
    at Object.appendByteBuffer (/Users/sam/Public/oasis-eos/eosjs/node_modules/fcbuffer/lib/types.js:506:42)
    at Object.appendByteBuffer (/Users/sam/Public/oasis-eos/eosjs/node_modules/fcbuffer/lib/types.js:353:16)
    at Object.appendByteBuffer (/Users/sam/Public/oasis-eos/eosjs/node_modules/fcbuffer/lib/struct.js:110:20)
    at action.data.appendByteBuffer (/Users/sam/Public/oasis-eos/eosjs/src/structs.js:516:11)
    at Object.appendByteBuffer (/Users/sam/Public/oasis-eos/eosjs/node_modules/fcbuffer/lib/struct.js:108:15)
    at Object.appendByteBuffer (/Users/sam/Public/oasis-eos/eosjs/node_modules/fcbuffer/lib/types.js:353:16)
    at Object.appendByteBuffer (/Users/sam/Public/oasis-eos/eosjs/node_modules/fcbuffer/lib/struct.js:110:20)
    at toByteBuffer (/Users/sam/Public/oasis-eos/eosjs/node_modules/fcbuffer/lib/fcbuffer.js:284:8)
    at Function.toBuffer (/Users/sam/Public/oasis-eos/eosjs/node_modules/fcbuffer/lib/fcbuffer.js:271:22)

**Comment by jcalfee** [comment]
As a fix: Looks like `newteam.players = ["0","1"]` should be `newteam.players = [0,1]` ..

Since it is a uint32 it is not expecting strings.  If it were over 52 bits (uint64 or int64) it would expect strings.  Maybe eosjs could allow string numbers in this case.

**Comment by AdamBylin** [comment]
{account: "eosio", name: "voteproducer",…}
account:"eosio"
authorization
:[{actor: "gy4dkmjzhege", permission: "active"}]
data:"a0986aff49988867a01861f9519b88670780a932d3e5a9d835104208c1386c3055500f9bee3975305590293dd37577305510eaf1dd44c33055e0b3dbe632ec30551092a6114dc33155"
name:"voteproducer"
context_free_actions:[]
delay_sec:0
expiration:"2018-06-22T13:23:04"
max_cpu_usage_ms:0
net_usage_words:0
ref_block_num:
21221
ref_block_prefix
1845345093
transaction_extensions
========================result===================================
{"code":500,"message":"Internal Service Error","error":{"code":3050003,"name":"eosio_assert_message_exception","what":"eosio_assert_message assertion failure","details":[]}}
===============================================================
I get same error when i vote with proxy

**Comment by chris-allnutt** [comment]
What's the unpacked data? I know that error will occur if producer names aren't in alphabetical order.

**Comment by AdamBylin** [comment]
var proxy = ""; //work
but it is work with nothing change only empty the proxy

**Comment by jcalfee** [comment]
Not the same error .. but I can confirm the packed data has sorted producers.  
```js
> p1=eos.fc.fromBuffer('voteproducer', 'a0986aff49988867a01861f9519b88670780a932d3e5a9d835104208c1386c3055500f9bee3975305590293dd37577305510eaf1dd44c33055e0b3dbe632ec30551092a6114dc33155')
{ voter: 'gy4dkmjzhege',
  proxy: 'gy4dqojtg4ge',
  producers:
   [ 'argentinaeos',
     'eosasia11111',
     'eosbeijingbp',
     'eosbixinboot',
     'eosgalaxybp1',
     'eosisgravity',
     'eoswancloud1' ] }
> assert.equal(p1.producers.sort(), p1.producers)
undefined
```
By the way @AdamBylin, you can just send your callback to eos.transaction as the last parameter..  

Do you see a stack trace anywhere?  This may be something in voting.cpp..

**Comment by AdamBylin** [comment]
![image](https://user-images.githubusercontent.com/5262725/41780834-72ca4f50-7668-11e8-99a1-e8118c9a4fd8.png)

Mate,still not work

**Comment by jcalfee** [comment]
@AdamBylin unrelated, but the callback is not an "option" it goes after the option parameter just like a standard callback.

**Comment by AdamBylin** [comment]
![image](https://user-images.githubusercontent.com/5262725/41781181-6deb5442-7669-11e8-96de-8b90383058fe.png)
 
like this?

**Comment by AdamBylin** [comment]
work without proxy

**Comment by AdamBylin** [comment]
It is my problem that 
1. agent is not registered（regproxy）.
2 cannot vote for producers and proxy at same time 
![image](https://user-images.githubusercontent.com/5262725/41817965-cc0d7860-77d7-11e8-88a5-961aafca7be8.png)

Thank you for your help

**Comment by yankunsam** [comment]
@jcalfee  actions: [
      {
        account: 'eosio',
        name: 'newteam',
        authorization: [{
          actor: 'user1',
          permission: 'active'
        }],
        data: {
          "owner": "user1",
          "banker": "eosio.token",
          "players": [0,3],
          "scoresum": 0,
          "cost": "0.0000 SYS",
          "stake": "2.0000 SYS",
          "gameid": 0
        }



It didn't work.

**Comment by jcalfee** [comment]
@yankunsam You should probably deploy your contract under an account other than 'eosio' .. Their could be special cases on that account.  Also, please include an error if this does not work under a non-eosio account.  I'm rooting for user1 by the way..

**Comment by yankunsam** [comment]
non eosio is  right and also the right schema with smart contrac. It works now , Thanks.
