### ISSUE TITLE
api error while creating a new account in eosjs

### ISSUE THREAD

**Issue by manankinj** [EOSIO/eosjs#221]
api error => undefined http://195.29.45.119:80/v1/chain/push_transaction {"compression":"none","transaction":{"expiration":"2018-06-25T06:12:27","ref_block_num":27028,"ref_block_prefix":3349965107,"net_usage_words":0,"max_cpu_usage_ms":0,"delay_sec":0,"context_free_actions":[],"actions":[{"account":"eosio","name":"newaccount","authorization":[{"actor":"tester","permission":"active"}],"data":"000000005c95b1ca0040c85353848c9701000000010002c0ded2bc1f1305fb0faac5e6c03ee3a1924234985427b6167ca569d13df435cf0100000001000000010002c0ded2bc1f1305fb0faac5e6c03ee3a1924234985427b6167ca569d13df435cf01000000"},{"account":"eosio","name":"buyrambytes","authorization":[{"actor":"tester","permission":"active"}],"data":"000000005c95b1ca0040c85353848c9700200000"},{"account":"eosio","name":"delegatebw","authorization":[{"actor":"tester","permission":"active"}],"data":"000000005c95b1ca0040c85353848c97a0860100000000000453595300000000a086010000000000045359530000000000"}],"transaction_extensions":[]},"signatures":["SIG_K1_...."]}
{ Error: {"code":500,"message":"Internal Service Error","error":{"code":3050003,"name":"eosio_assert_message_exception","what":"eosio_assert_message assertion failure","details":[]}}

**Comment by jcalfee** [comment]
the nodeos `--verbose-http-errors` may help in the future
