### ISSUE TITLE
eosjs 15.0.3 failed when initializing an eosjs instance 

### ISSUE THREAD

**Issue by woshidama323** [EOSIO/eosjs#222]
root/testlendtest/node_modules/eosjs/lib/structs.js:140
    throw new Error(JSON.stringify(errors, null, 4));
    ^

Error: [
    "Unrecognized type or struct block_timestamp_type.timestamp",
    "Missing block_timestamp_type in eosio_global_state.fields.last_producer_schedule_update",
    "Missing block_timestamp_type in eosio_global_state.fields.last_name_close"
]
    at module.exports (/root/testlendtest/node_modules/eosjs/lib/structs.js:140:11)
    at createEos (/root/testlendtest/node_modules/eosjs/lib/index.js:98:18)
    at Eos (/root/testlendtest/node_modules/eosjs/lib/index.js:42:10)
    at Object.<anonymous> (/root/testlendtest/app.js:27:7)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)

**Comment by jcalfee** [comment]
upgrade eosjs .. block_timestamp_type was added later

**Comment by woshidama323** [comment]
I've upgraded the latest eosjs from npm package website .but still failed . you mean i need to get them from github master branch ?

**Comment by jcalfee** [comment]
No, npm is fine .. block_timestamp_type has been in chain_types.json for some time now..  Sometimes versions can get hung up especially on some operating systems that don't handle files well.  Can you double-check your version like this:
```js
> Eos.version
'15.0.3'
```
and this
```bash
$ npm ls eosjs
eosjs@15.0.3 
```

**Comment by woshidama323** [comment]
yes it indeed is 15.0.3
root@EOSServer:/usr/local/lib/node_modules# npm list eosjs
/usr/local/lib
└── eosjs@15.0.3

**Comment by jcalfee** [comment]
If your getting this error just trying to create the instance then your installation is probably busted.

**Comment by woshidama323** [comment]
could you help to point me out if the code is correct ?  I have intall the eosjs for several times but still doesn't work.

var Eos = require('eosjs');
console.log(Object.getOwnPropertyNames(Eos));   //this line works well 

var keyProvider = '5KcRYqfA7VyySKxKL1rwX9u3s9gLwzqRRbManBq5AU7XVVS35H3'
eos = Eos({keyProvider}) .      // if I delete this line the program worked well.

**Comment by jcalfee** [comment]
What version of node to you have..  This works for me:

```bash
$ npm i ../eosjs/eosjs-15.0.3.tgz
$ node -v
v10.4.0
```

```js
node
> var Eos = require('eosjs');
undefined
> console.log(Object.getOwnPropertyNames(Eos)); //this line works well
[ 'length',
  'name',
  'prototype',
  'version',
  'modules',
  'Testnet',
  'Localnet' ]
undefined
> 
> var keyProvider = 'private key xxxxxxxx'
undefined
> eos = Eos({keyProvider}); console.log(Object.getOwnPropertyNames(eos)); //this line works well
[ 'getCurrencyBalance',
  'getCurrencyStats',
  ..
  'modules' ]
undefined
```
