### ISSUE TITLE
To Sign a transaction over cleos requires for "chain-id", but eosjs sign without this param.

### ISSUE THREAD

**Issue by jooyyy** [EOSIO/eosjs#225]
I get two different signed result in this two way, for example：
```
cleos sign [TransTextJson] -k XXXXXX -c XXXXXXX

ecc.Signature.sign([TransTextJson], [PrivateKey])
```
it seems that chain-id is a required input for sign operate.

**Comment by jcalfee** [comment]
Correct ..

I recently added some usage examples at the top of the README .. Please let me know if this is not crystal clear and I'll clarify:

https://github.com/EOSIO/eosjs#usage

**Comment by jcalfee** [comment]
Actually, I'm assuming you want to use eosjs .. If not, you need to consider steps like this to convert the json to binary, hash it, then sign with the chain ID and a place holder for packed context free data:

https://github.com/EOSIO/eosjs/blob/master/src/write-api.js#L438-L452
