### ISSUE TITLE
Please update documentation

### ISSUE THREAD

**Issue by xwartz** [EOSIO/eosjs#226]
Hi,

I really like the package. However, I have a really hard time using the package. Whenever I need something specific, I get stuck and spend hours trying to figure out what is this.

For example: 

getAccount()
```js
ram_quota: 69053,
total_resources: {
  cpu_weight: "0.7588 EOS",
  net_weight: "0.6216 EOS",
  owner: "xxxx",
  ram_bytes: 69053,
}
```

What is the difference between ram _ quota and ram _ bytes?

**Comment by jcalfee** [comment]
ram_bytes is the one used in the system contract under the account.   That is the main one users will be looking at.  ram_quota is used in get_account_limits which I suspect is a block producers limit on all the accounts..

https://github.com/EOSIO/eos/search?q=get_account_limits&unscoped_q=get_account_limits


Your going to have to look at the code on some of this if you don't find docs.
