### ISSUE TITLE
Complete example of how to create a new account on the Jungle testnet using JS?

### ISSUE THREAD

**Issue by ntheile** [EOSIO/eosjs#227]
Can somebody help with a complete example of how to create a new account on the Jungle testnet?

Below is the code I have so far, but i get a 500 error:

This is the code:
Any ideas?

<pre>
let eosConfig = {
    chainId: '038f4b0fc8ff18a4f0842a8f0564611f6e96e8535901dd45e43ac8691a1c4dca', // Jungle Testnet  http://dev.cryptolions.io:38888/v1/chain/get_info
    keyProvider: ['5J5iLj....'], // <----- ????? is this an existing account private key that has ram cpu and bandwidth already purchased?
    httpEndpoint: 'http://dev.cryptolions.io:38888', // jungle testnet
    expireInSeconds: 60,
    broadcast: true,
    debug: true, 
    sign: true
}
let eos = Eos(eosConfig)
let pubkey = "EOS51..."; 
accountName = "mynewuser";

eos.getInfo((error, result) => { console.log("EOS ====> ", error, result) })

eos.transaction(tr => {

    tr.newaccount({
        creator: 'existingaccount',
        name: accountName,
        owner: pubkey,  // <------ ????? Is this  the public key the of the new user account that was generate by a wallet tool or the eosjs-keygen
        active: pubkey  
    });

    tr.buyrambytes({
        payer: 'existingaccount',
        receiver: accountName,
        bytes: 3000 // <------ ????? how much should i give
    });

    tr.delegatebw({
        from: 'existingaccount',
        receiver: accountName,
        stake_net_quantity: '1 EOS', // <------ ????? how much should i give
        stake_cpu_quantity: '1 EOS', // <------ ????? how much should i give
        transfer: 0
    });

}).then( (resp) =>{
    console.log("EOS resp ", resp);
});

</pre>     

This is the error  I get

<pre>
POST http://dev.cryptolions.io:38888/v1/chain/push_transaction 500 (Internal Server Error)
apigen.js:120 api < error 	 undefined http://dev.cryptolions.io:38888/v1/chain/push_transaction {"compression":"none","transaction":{"expiration":"2018-06-27T05:57:48","ref_block_num":37061,"ref_block_prefix":2153978782,"net_usage_words":0,"max_cpu_usage_ms":0,"delay_sec":0,"context_free_actions":[],"actions":[{"account":"eosio","name":"newaccount","authorization":[{"actor":"blockusign","permission":"active"}],"data":"00c0640e6b88683ca056f35abdd47063010000000100020fef8b61c601d36f480..."},{"account":"eosio","name":"buyrambytes","authorization":[{"actor":"blockusign","permission":"active"}],"data":"00c0640e6b88683ca056f35abdd47063b80b0000"},{"account":"eosio","name":"delegatebw","authorization":[{"actor":"blockusign","permission":"active"}],"data":"00c0640e6b88683ca056f35abdd47063320000000000000000454f5300000000320000000000000000..."}],"transaction_extensions":[]},"signatures":["SIG_K1_K9er4dePbgW8kw...."]}

apigen.js:121 Error: {"code":500,"message":"Internal Service Error","error":{"code":3050003,"name":"eosio_assert_message_exception","what":"eosio_assert_message assertion failure","details":[]}}
    at apigen.js:95
</pre>

**Comment by jcalfee** [comment]
>keyProvider: ['5J5iLj....'], // <----- ????? is this an existing account private key that has ram cpu and bandwidth already purchased?

Yes, this will need to match an the active key or owner key (probably the active) of the newaccount.creator ..


>        owner: pubkey,  // <------ ????? Is this  the public key the of the new user account that was generate by a wallet tool or the eosjs-keygen

Yes, it is any public key, just make sure you have the private key..

>bytes: 3000 // <------ ????? how much should i give

It looks like all accounts have about 2.93 Kb of ram.. https://eostracker.io/accounts/citicardseos
You can buy / sell ram later too.

Most accounts are staking .01 or .02 EOS .. one had as low as .0001 .. You can re-run the delegatebw with new values later if you find out you need more or less later.
https://eostracker.io/accounts/alimabibieos

I would make a request of the jungle net and ask them to add this new parameter: `nodeos --verbose-http-errors` .. This will cause the error your seeing to have something in the "details: []" stack array.

Also, try adding the zeros to your amounts: change `1 EOS` to `1.0000 EOS` for example..

Make sure you also try with a recent version of eosjs .. `debug: true,` was changed to `verbose: true,` .. Only use verbose if you want to see all of the API traffic.  Only use debug if your need to track the binary serialization.

**Comment by ntheile** [comment]
thanks @jcalfee . it works now, you da man! . I simply changed debug to verbose and added the decimals.

Here is the working code:

<pre>
let eosConfig = {
    chainId: '038f4b0fc8ff18a4f0842a8f0564611f6e96e8535901dd45e43ac8691a1c4dca', // Jungle Testnet  http://dev.cryptolions.io:38888/v1/chain/get_info
    keyProvider: ['5J5iLj....'], // <----- existing account (active) private key that has ram cpu and bandwidth already purchased
    httpEndpoint: 'http://dev.cryptolions.io:38888', // jungle testnet
    expireInSeconds: 60,
    broadcast: true,
    debug: true, 
    sign: true
}
let eos = Eos(eosConfig)
let pubkey = "EOS51...";  // <------ the public key the of the new user account that was generate by a wallet tool or the eosjs-keygen
accountName = "mynewuser"; // <---- the new account you are creating

eos.getInfo((error, result) => { console.log("EOS ====> ", error, result) })

eos.transaction(tr => {

    tr.newaccount({
        creator: 'existingaccount',
        name: accountName,
        owner: pubkey,  // <------ the public key the of the new user account that was generate by a wallet tool or the eosjs-keygen
        active: pubkey  
    });

    tr.buyrambytes({
        payer: 'existingaccount',
        receiver: accountName,
        bytes: 5000 // <------  less might work, but 5Kb worked for me
    });

    tr.delegatebw({
        from: 'existingaccount',
        receiver: accountName,
        stake_net_quantity: '1.0000 EOS', 
        stake_cpu_quantity: '1.0000 EOS', 
        transfer: 0
    });

}).then( (resp) =>{
    console.log("EOS resp ", resp);
});

</pre>

**Comment by goga-m** [comment]
Greetings, 

I am trying to create a new account following the above example but I keep receiving a "balance object not found" error 

Here is the sample code that I use:

`const creator = 'dkubpsnzaewh' // existing account in jungle testnet
const creatorWif = '5HrkduVcADgJPsx16R5s8YEDjH3ZazR8FxPece3dn1grGn4kvaR'
const newAccount = 'tbzmgqciupxn'
const newAccountPubkey = 'EOS8c1gTXoiQyQrPsa6AVYB2uRW8vib9ncpuR4gG3ZMMrhDcZLa6T'

const config = {
  chainId: '038f4b0fc8ff18a4f0842a8f0564611f6e96e8535901dd45e43ac8691a1c4dca',
  keyProvider: creatorWif,
  httpEndpoint: 'http://193.93.219.219:8888', // Jungle testnet
  expireInSeconds: 60,
  verbose: true,
  broadcast: true,
  sign: true
}

const eos = Eos(config)

eos.transaction(tr => {
  tr.newaccount({
    creator: creator,
    name: newAccount,
    owner: newAccountPubkey,
    active: newAccountPubkey
  })

  tr.buyrambytes({
    payer: creator,
    receiver: newAccount,
    bytes: 5000
  })

  tr.delegatebw({
    from: creator,
    receiver: newAccount,
    stake_net_quantity: '1.0000 EOS',
    stake_cpu_quantity: '1.0000 EOS',
    transfer: 0
  })
})
.then(console.log)
`
The error:
`{ Error: {"code":500,"message":"Internal Service Error","error":{"code":3050003,"name":"eosio_assert_message_exception","what":"eosio_assert_message assertion failure","details":[{"message":"assertion failure with message: no balance object found","file":"wasm_interface.cpp","line_number":930,"method":"eosio_assert"},{"message":"pending console output: ","file":"apply_context.cpp","line_number":61,"method":"exec_one"}]}}
`
This seems to be a general error message that it not only related to to new account creation.

**Comment by goga-m** [comment]
@jcalfee my bad, thanks!

**Comment by trungtt1981** [comment]
@goga-m 
@jcalfee 
Any update on this kind of error?
I've encountered the same error!!

Thanks for any reply

**Comment by jcalfee** [comment]
"balance object not found" ?   That means you have no money.  Send some funds to the account.
