### ISSUE TITLE
Keys functions

### ISSUE THREAD

**Issue by On1x** [EOSIO/eosjs#23]
Needed functions for:
* Private random key generation;
* Public key from private;
* Checking private key conformity with public key.

**Comment by On1x** [comment]
Oh, seems there is another eosjs for keys https://github.com/EOSIO/eosjs-keygen

**Comment by jcalfee** [comment]
All three can be done with this one: https://github.com/eosio/eosjs-ecc

npm i eosjs-ecc

**Comment by mohit-lala** [comment]
eosjs-ecc not working for jungle testnet 2
