### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by pengchaoling** [EOSIO/eosjs#232]
I use react and eosjs to develop my dapp,

the console point out message:

Failed to load http://127.0.0.1:8888/v1/chain/get_code: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:8080' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by chris-allnutt** [comment]
You need to allow CORS in your config on nodeos

**Comment by pengchaoling** [comment]
how to allow CORS in my config ?   @chris-allnutt

**Comment by pengchaoling** [comment]
think you.  I find it in config.ini  @chris-allnutt

**Comment by pengchaoling** [comment]
thank you. i  find the config  in config.ini

**Comment by jcalfee** [comment]
access-control-allow-origin=*

**Comment by grigio** [comment]
are there public api with `--access-control-allow-origin=*` ?

**Comment by jcalfee** [comment]
See "other endpoint" in the comment .. 
https://github.com/EOSIO/eosjs#usage
