### ISSUE TITLE
is there any Logical Api for paging?

### ISSUE THREAD

**Issue by epochchaser** [EOSIO/eosjs#233]
Hi. i am struggling with paging function using chain.json.

i can fetch records using api below ->

"get_table_rows": {
    "brief": "Fetch smart contract data from an account.",
    "params": {
      "json": { "type": "bool", "default": false},
      "code": "name",
      "scope": "name",
      "table": "name",
      "table_key": "string",
      "lower_bound": {"type": "string", "default": "0"},
      "upper_bound": {"type": "string", "default": "-1"},
      "limit": {"type": "uint32", "default": "10"}
    },
    "results": {
      "rows": {
        "type": "vector",
        "doc": "one row per item, either encoded as hex String or JSON object"
      },
      "more": {
        "type": "bool",
        "doc": "true if last element"
      }
    }
  }

but i haven't found any solution for paging.
and i tried many possible options with lower_bound, upper_bound but it didn't work.

Is there any API for paging or any recommend solution?
Thank you.

**Comment by jcalfee** [comment]
Possibly related: https://github.com/EOSIO/eosjs/issues/224

**Comment by epochchaser** [comment]
Thank you for reply.
i solved using lower_bound, upper_boud, limit combination.
