### ISSUE TITLE
get_code dice error  

### ISSUE THREAD

**Issue by AdamBylin** [EOSIO/eosjs#234]
![image](https://user-images.githubusercontent.com/5262725/42135603-ad016316-7d7f-11e8-9877-c12670d0f78e.png)

{"code":500,"message":"Internal Service Error","error":{"code":0,"name":"exception","what":"unspecified","details":[]}}

**Comment by chris-allnutt** [comment]
Crypto-lions dev port is 18888 not 38888  eosjs does not develop nodeos, and we would need a more detailed server report data in order to diagnose if this was an issue with eosjs.  Doing a quick account info look directly on cryptolions it appears the "dice" account does not exist.
