### ISSUE TITLE
How to add options ?

### ISSUE THREAD

**Issue by anil215** [EOSIO/eosjs#235]
I was trying to do a standard eos transaction via eosjs , but i was unable to find an example on how to add options like setting the expiration, adding the don't broadcast etc. The format i am using currently is this.
![screen shot 2018-07-03 at 3 04 10 pm](https://user-images.githubusercontent.com/23135051/42211968-6b9619e0-7ed2-11e8-8128-a61823cc5a0f.png)

**Comment by jcalfee** [comment]
Expiration and broadcast can do into the config in the constructor: `eosClient = Eos(config)` ..
https://github.com/EOSIO/eosjs#configuration
