### ISSUE TITLE
eos.contract issue

### ISSUE THREAD

**Issue by crazybits** [EOSIO/eosjs#237]
the following error would be encountered while use the sample 1 approach, but sample 2 works fine, btw,`KeyProvider.getKeys()` return a promise
> api < error          { message: 'transaction declares authority \'{"actor":"bob","permission":"active"}\', but does not have signatures for it under a provided delay of 0 ms, provided permissions [{"actor":"dice","permission":"eosio.code"}], and provided keys []',

sample 1
```
	async withdraw(to, asset) {
		let eos = Eos({
			keyProvider: KeyProvider.getKeys()
		})
		return eos.contract(contractDeployAcct).then(contract => contract.withdraw(to, asset))
	}
```

sample 2
```
async withdraw(to, asset) {
		eos = Eos({
			keyProvider: KeyProvider.getKeys()
		})

		return eos.transaction(
			{
			  actions: [
				{
				  account: contractDeployAcct,
				  name: 'deposit',
				  data: {
					from: from,
					a: asset,
				  },
				  authorization: [{
					actor: from,
					permission: 'active'
				  }]
				}
			  ]
			}
		  )
	}
```

**Comment by jcalfee** [comment]
getKeys returns key paths and private keys... KeyProvider needs just private keys.  You can map them to the correct array.

https://github.com/EOSIO/eosjs-keygen/blob/master/API.md#keypathprivate--object

But what you probably want to do is link them directly:
https://github.com/EOSIO/eosjs-keygen/blob/master/API.md#keystorekeyproviderparam--arraypubkeywif

**Comment by jcalfee** [comment]
see: https://github.com/eosio/eosjs-keygen#usage
