### ISSUE TITLE
Is it mandatory to cache the abi?

### ISSUE THREAD

**Issue by kesar** [EOSIO/eosjs#24]
trying to run something like: (6.1.6)

```
node.transaction({
    scope: ['inita', settings.rpc.account],
    messages: [
        {
            code: settings.rpc.account,
            type: 'tip',
            authorization: [{
                account: settings.rpc.account,
                permission: 'active'
            }],
            data: {
                from_twitter: "kesarito",
                to_twitter: "kesarito2",
                quantity: "0x0000000000000001"
            }
        }
    ]
});
````
getting:

Abi 'twitbot' is not cached, call abiAsync('twitbot') message.data transaction.messages

```
var options = {
    broadcast: true,
    sign: true,
    scope: ['inita', settings.rpc.account],
    messages: [
        {
            code: settings.rpc.account,
            type: 'tip',
            authorization: [{
                account: settings.rpc.account,
                permission: 'active'
            }],
            data: {
                from_twitter: "kesarito",
                to_twitter: "kesarito2",
                quantity: 1
            }
        }
    ]
};

node.contract(settings.rpc.account).then(function (result) {
    result.transaction(options);
});
```

Also fails getting:

Error: Required uint64 tip.2 message.data transaction.messages

Running it like:

```
var options = {
    broadcast: true,
    sign: true,
    scope: ['inita', 'twitbot'],
    authorization: [{
        "account": "twitbot",
        "permission": "active"
    }]
};

var msg = {
    "from_twitter": "kesarito",
    "to_twitter": "kesarito2",
    "quantity": "1"
}

node
    .contract('twitbot', options)
    .then((contract) => {
    contract.tip(msg)
});

```

I get: 

(node:29281) UnhandledPromiseRejectionWarning: TypeError: contract.tip is not a function

In command line this works:

eosioc push action twitbot tip '{"from_twitter": "kesarito", "to_twitter": "kesarito2", "quantity": 1}' --permission twitbot@active

ABI:

```
{
  "types": [],
  "structs": [{
      "name": "account",
      "base": "",
      "fields": [{
          "name": "twitter_account",
          "type": "name"
        },{
          "name": "balance",
          "type": "uint64"
        }
      ]
    },{
    "name": "tip",
    "base": "",
    "fields": [
       {"name":"from_twitter", "type":"name"},
       {"name":"to_twitter", "type":"name"},
       {"name":"quantity", "type":"uint64"}
    ]
 },{
     "name": "withdraw",
     "base": "",
     "fields": [
       {"name":"to_eos", "type":"account_name"},
       {"name":"from_twitter", "type":"name"}
     ]
   }
  ],
  "actions": [{
      "name": "tip",
      "type": "tip"
    },{
      "name": "withdraw",
      "type": "withdraw"
    }
  ],
  "tables": [{
      "name": "account",
      "index_type": "i64",
      "key_names": [
        "twitter_account"
      ],
      "key_types": [
        "name"
      ],
      "type": "account"
    }
  ]
}
```

**Comment by jcalfee** [comment]
It is mandatory to download the ABI and it will automatically cache.  I don't have to cache it.

**Comment by kesar** [comment]
> b) eosioc tells me you may be using dawn 3 so this may be related.. There are many changes. I'll start adding support next week. If you need a work-around, try using the dawn2 build tag.

Yeah, I am using https://github.com/EOSIO/eos/releases/tag/DAWN-2018-01-31-ALPHA probably its because of that! 👍If you want the code for testing you can find it: ( https://github.com/kesar/twitbot/tree/master/contracts/twitbot ) it works fine from command line.


Isn't possible to upload contracts without abi ? I guess it needs to be supported a contract without abi as well.

**Comment by jcalfee** [comment]
>Isn't possible to upload contracts without abi ? I guess it needs to be supported a contract without abi as well.
Perhaps, I can see a scheduled event used in this way.  But If a contract does not have an ABI, there are no action methods to call so the eos.contract lookup method would have no use anyways.  So the ABI is required for the eos.contract lookup so it will have one or more actions to call.

**Comment by jcalfee** [comment]
a) npm eosjs@6.1.8 will lookup the ABI for each message when you provide a full transaction.
b) tracked under another ticket: https://github.com/EOSIO/eosjs/issues/25

Now, back to abi caching .. I'm going to look at the dawn 3 get_code API and see if that changed.  What I really need is a get_abi and a immutable flag, this way I know to automatically re-fresh the cache frequency if the abi is mutable.  I assume you have no issues with memory right?  I'm thinking I can cache all ABIs but I need to refresh in some cases.

**Comment by kesar** [comment]
> a) npm eosjs@6.1.8 will lookup the ABI for each message when you provide a full transaction.

👍  awesome. I'm gonna test it :)

**Comment by kesar** [comment]
yeah, transaction now doesnt return the abi cache issue. 👍 

I'm getting something different not related to this issue, perhaps you can also throw some light? The type is uint64, but passing ``` quantity: 1  ``` it doesnt work. Any idea how should I send a uint64 format ?

Thanks!

**Comment by jcalfee** [comment]
Use a string, if the number is not quoted javascript will change your number to be about 53 bits even if the number is larger..

**Comment by kesar** [comment]
> Use a string, if the number is not quoted javascript will change your number to be about 53 bits even if the number is larger..

It seems that its not doing it, perhaps an issue in the fcbuffer?: I changed it to quantity: "1"

Error: Required uint64 tip.2 message.data transaction.messages
    at validateInt (/Users/kesar/PhpstormProjects/twitbot/app/node_modules/fcbuffer/lib/types.js:677:11)
    at Object.fromObject (/Users/kesar/PhpstormProjects/twitbot/app/node_modules/fcbuffer/lib/types.js:444:7)
    at Object.fromObject (/Users/kesar/PhpstormProjects/twitbot/app/node_modules/fcbuffer/lib/struct.js:144:34)
    at messageDataFromObject (/Users/kesar/PhpstormProjects/twitbot/app/node_modules/eosjs/lib/structs.js:428:29)
    at Object.fromObject (/Users/kesar/PhpstormProjects/twitbot/app/node_modules/fcbuffer/lib/struct.js:141:15)
    at Object.fromObject (/Users/kesar/PhpstormProjects/twitbot/app/node_modules/fcbuffer/lib/types.js:320:28)
    at Object.fromObject (/Users/kesar/PhpstormProjects/twitbot/app/node_modules/fcbuffer/lib/struct.js:144:34)
    at /Users/kesar/PhpstormProjects/twitbot/app/node_modules/eosjs/lib/write-api.js:553:34
    at /Users/kesar/PhpstormProjects/twitbot/app/node_modules/eosjs/lib/write-api.js:699:7
    at /Users/kesar/PhpstormProjects/twitbot/app/node_modules/eosjs-api/lib/exported-helpers.js:65:7

**Comment by jcalfee** [comment]
Did you go back to dawn2?  You may need dawn3 updates, I'm working on that now..

**Comment by kesar** [comment]
Oh ok! so that would be the problem, I will test your dawn3 when you are done :) 

I will close this issues as the ABI thing is solved! Thanks 🙏
