### ISSUE TITLE
`build_browser` script does not do what documentation says

### ISSUE THREAD

**Issue by MrToph** [EOSIO/eosjs#241]
Hi, the doc says:

```
git clone https://github.com/EOSIO/eosjs.git
cd eosjs
npm install
npm run build_browser
# builds: ./dist/eos.js load with ./dist/index.html
```

But it doesn't build `./dist/eos.js`, instead it compiles a bunch of files from `src` to `lib`.
Therefore the `dist/index.html` file doesn't work because there is a hard-coded ` <script src="eos.js"></script>` inside.

There should be an easy way to use this module in the browser. I suggest shipping it with `npm` already.

**Comment by jcalfee** [comment]
I am shipping it now to NPM and there is a new usage example here:
 https://github.com/EOSIO/eosjs#usage

I have updated the readme.. thank you ..
