### ISSUE TITLE
Getting accounts associated with private/public key

### ISSUE THREAD

**Issue by andriytyurnikov** [EOSIO/eosjs#244]
I scrolled through pieces of docs and source and still don't understand
How to get a list of associated accounts with PrivateKey

**Comment by jcalfee** [comment]
Did you find it?  You have to convert the private key to a public key so you can use this method:
```js
pubkey = Eos.modules.ecc.privateToPublic(wif)
eos.getKeyAccounts(pubkey)
```
usage:
```js
> eos.getKeyAccounts()
USAGE
getKeyAccounts - undefined

PARAMETERS
{
  "public_key": "public_key_type"
}

RETURNS
{
  "account_names": "account_name[]"
}
```
