### ISSUE TITLE
Creating an account with EOSjs in the browser gives unsatisfied_authorization error

### ISSUE THREAD

**Issue by bkawk** [EOSIO/eosjs#248]
The exact Error & Logs... 

![screen shot 2018-07-11 at 22 15 26](https://user-images.githubusercontent.com/14357697/42577906-f8cc7ea4-8557-11e8-85c1-8945bf99ece2.png)

The code adapted directly from eosjs readme...
```
  _start() {
    this._connect()
    .then((eos) => {
      return this._makeAccount(eos)
    })
    .then((result) => {
      console.log("-- Result")
      console.log(result)
    })
    .catch((err) => {
      console.log("-- Error")
      console.log(err)
    })
  }


  _connect(){
    return new Promise((resolve) => {
      
      const keyProviderVal = this.shadowRoot.querySelector('#keyProvider').value;
      const keyProvider = [keyProviderVal];
      const httpEndpoint = "https://nodes.get-scatter.com:443";
      const broadcast = true;
      const sign = true;
      const chainId = "aca376f206b8fc25a6ed44dbdc66547c36c6c33e3a119ffbeaef943642f0e906";
      const expireInSeconds = 60;
      const verbose = true;

      console.log("-- CONNECTING")
      console.log('keyProvider: ' + keyProvider)
      console.log('httpEndpoint: ' + httpEndpoint)
      console.log('broadcast: ' + broadcast)
      console.log('sign: ' + sign)
      console.log('chainId: ' + chainId)
      console.log('expireInSeconds: ' + expireInSeconds)
      console.log('verbose: ' + verbose)

      const eos = Eos({keyProvider, httpEndpoint, broadcast, sign, chainId, expireInSeconds, verbose})
      resolve(eos);
    })
  }



  _makeAccount(eos) {
    return new Promise((resolve, reject) => {

      const creator = this.shadowRoot.querySelector('#creatorAccountName').value;
      const name = this.shadowRoot.querySelector('#newAccountName').value;
      const owner = this.shadowRoot.querySelector('#ownerPublicKey').value;
      const active = this.shadowRoot.querySelector('#activePublicKey').value;
      const bytes = 7900;
      const stake_net_quantity = '0.1000 EOS';
      const stake_cpu_quantity = '0.1000 EOS';
      const transfer = 0;

      console.log("-- MAKE ACCOUNT")
      console.log('creator: ' + creator)
      console.log('name: ' + name)
      console.log('owner: ' + owner)
      console.log('active: ' + active)
      console.log('bytes: ' + bytes)
      console.log('stake_net_quantity: ' + stake_net_quantity)
      console.log('stake_cpu_quantity: ' + stake_cpu_quantity)
      console.log('transfer: ' + transfer)

      eos.transaction(tr => {
        tr.newaccount(creator, name, owner, active)
        tr.buyrambytes(creator, name, bytes)
        tr.delegatebw(creator, name, stake_net_quantity, stake_cpu_quantity, transfer)
      })
      .then((response) => {
        resolve(response)
      })
      .catch((err) => {
        reject(err)
      })
    })
  }
```
I am running the latest version of eosjs
I have tried multiple endpoints
this is the creator account I'm using https://eospark.com/MainNet/account/helloeosblox

I have isolated the code here: https://github.com/EOSBlox/isolatedCreateAccountIssue/blob/master/create-account-check.js

And it is deployed here: https://eoslaunch.app/create

**Comment by jcalfee** [comment]
I'm trying to test this out .. I'm getting this error from `https://mainnet.eoscanada.com`:

>'the transaction was unable to complete by deadline, but it is possible it could have succeeded if it were allowed to run to completion'

**Comment by bkawk** [comment]
Hey @jcalfee thanks for taking a look at this, I have just updated the code with more logging, if you have time maybe take a fresh copy?

**Comment by jcalfee** [comment]
You will see a console log warning if the chainId does not match.

**Comment by bkawk** [comment]
Yeah Ive checked and double checked the chainId ill remove it from the below 3 lines in about 6 hours, for now its doing no harm
```
tr.newaccount({creator, name, owner, active, chainId})
tr.buyrambytes({payer, receiver, bytes, chainId})
tr.delegatebw({from, receiver, stake_net_quantity, stake_cpu_quantity, transfer, chainId})
```

**Comment by jcalfee** [comment]
the chainId does into the main Eos consttructor .. because you use the same eos on the same chan you should not provide it again..
`eos = Eos({chainId}), eos.xyz().`

**Comment by bkawk** [comment]
ok ill remove it now from the tr objects

**Comment by abourget** [comment]
Hi there.. we whitelist endpoints for CORS.. just so people ask and we know where things come from.

Which domain are you looking to whitelist ?

**Comment by bkawk** [comment]
@abourget its not a questions of whitelisting, its about configuring your proxy correctly, I've worked through this with the guys over at EOS New York, and they have agreed to let the other BP's know the specifics, if you guys aren't friends then a quick google for your proxy name + CORS + Preflight will garnish you with the answers!

**Comment by jcalfee** [comment]
I went back and ran the same newaccount transaction above but using the wrong WIF.  That gave me the signature error.  So this implies that the signature is passing for me because when I used the correct WIF I got the other error "unable to complete by deadline" .. This makes since that a node would verify the signature first before using up CPU cycles so that would be more resistent to dos attacks.

To be complete, I should test in the browser with a CORS enabled endpoint.  I'm thinking the signature will pass and it may work though.

**Comment by abourget** [comment]
@bkawk by whitelisting, I meant configuring my proxy.

We front our nodes with a custom built proxy and we whitelist the domains on which we enable cross origin POSTs. That's why I am asking which domain you would like me to whitelist.

We don't plan on enabling cross origin calls for "*", not until we've gathered data about usage and use cases through issues like this one.

I appreciate the offer to help, but the team here masters all aspects of HTTP.

**Comment by bkawk** [comment]
@abourget if you can add https://eoslaunch.app/ and https://www.eosblox.com/ that would be great.

**Comment by bkawk** [comment]
I can confirm that the issue was me using the wrong key, the active key worked and created the account! https://eospark.com/MainNet/account/payeoslaunch
