### ISSUE TITLE
TypeError: Unknown struct 'setprods' for contract 'eosio'

### ISSUE THREAD

**Issue by tuhuiyan** [EOSIO/eosjs#250]
I deployed eosio.bios contract.I want to set producers:
var producers = [..........];
var eos = Eos(config);
        eos.contract('eosio',function(err,mycontract){
            if (err){
                callback(err,"");
            }else{
                mycontract.**setprods**({"schedule": producers}, options, function(err,res){
                    if (err){
                        callback(err,res);
                    }else{
                        callback(null,res.transaction_id);
                    }
                });
            }
        });

And I get this error:
TypeError: Unknown struct 'setprods' for contract 'eosio', locate this struct or provide serialized action.data action.data = {"schedule":XXX

But if I change the lib/schema/eosio_system.json:
"**set_producers**": {
    "base": "",
    "action": {
      "name": "setprods",
      "account": "eosio"
    },
    "fields": {
      "schedule": "producer_key[]"
    }
  },

change into : 

"**setprods**": {
    "base": "",
    "action": {
      "name": "setprods",
      "account": "eosio"
    },
    "fields": {
      "schedule": "producer_key[]"
    }
  },

it works!
why?

**Comment by chris-allnutt** [comment]
The bios contract doesn't have producer voting.  If you want to replicate mainnet functionality i recommend looking at the tutorial script to bootstrap your node https://github.com/EOSIO/eos/tree/master/tutorials/bios-boot-tutorial
