### ISSUE TITLE
npm publish

### ISSUE THREAD

**Issue by yankunsam** [EOSIO/eosjs#252]
1) offline transactionHeaders callback:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promi
se, ensure it resolves.

**Comment by jcalfee** [comment]
Usually this does not time-out, there could be a glitch in the backed..

See "Use async/wait:" .. I understand a async function to be like a promise function already.

https://stackoverflow.com/questions/44149096/for-async-tests-and-hooks-ensure-done-is-called-if-returning-a-promise-en#45858343
