### ISSUE TITLE
Format for Deploying WASM from the browser

### ISSUE THREAD

**Issue by bkawk** [EOSIO/eosjs#253]
When Using file reader in the browser I'm reading in the wasm file with 

```
  _readWasmFile(event) {
      const file = event.target.files[0];
      let reader = new FileReader();
      reader.readAsBinaryString(file);
      reader.onload = () => {
          this.sendWasm = reader.result;
      };
}
```

Before calling

```
eos.setcode('myaccount', 0, 0, this.sendWasm) 
```

Do I need to hex encode it before sending it? or should i be reading it as an array Buffer? The error I get below doesnt give me much to go on

 
![screen shot 2018-07-13 at 22 25 48](https://user-images.githubusercontent.com/14357697/42698864-b3619584-86f1-11e8-89c9-73a424986ee1.png)

nor does the docs..

https://github.com/EOSIO/eosjs#deploy

The question has also been posted here
https://eosio.stackexchange.com/questions/1458/what-format-should-be-used-to-set-code-from-the-browser

**Comment by bkawk** [comment]
I learnt from stack exchange that the "code 10" indicates that the contract has already been deployed!

**Comment by jcalfee** [comment]
I wonder why you are not getting good error messages back..
