### ISSUE TITLE
How to get total supply for "eosio.token" contract?

### ISSUE THREAD

**Issue by epochchaser** [EOSIO/eosjs#255]
Hello.
When i try to fetch something with eos.contract(contractName) API,
i could get this types of result. => {abi: {…}, schema: {…}, structs: {…}, types: {…}, fromBuffer: ƒ, …}
but there is no info about supply.

can you please give me some information about it?

**Comment by jcalfee** [comment]
```bash
$ cleos -u https://mainnet.eoscanada.com get table eosio.token EOS stat
{
  "rows": [{
      "supply": "1004320865.0254 EOS",
      "max_supply": "10000000000.0000 EOS",
      "issuer": "eosio"
    }
  ],
  "more": false
}
```

**Comment by jcalfee** [comment]
The supply was set after deployment and is stored in a table.

**Comment by epochchaser** [comment]
thanks for help!!
i solved it with currencystat!
