### ISSUE TITLE
how to get the amount of ram when I buy ram with 2 EOS. use the method of buyram

### ISSUE THREAD

**Issue by songsongMr** [EOSIO/eosjs#257]
actually,all the records of buy and sell ram is records of eos transfer .how to get the amount of ram when I buy ram with 2 EOS. use the method of buyram

**Comment by jcalfee** [comment]
not sure .. anyone?

**Comment by songsongMr** [comment]
Since the memory price is always changing, it would be inaccurate or wrong for me to calculate the amount of memory I get if I calculate with the price of memory and the number of EOS

**Comment by jcalfee** [comment]
I'll just go through what I know incase it helps...

All this logic starts in the `eosio.system` contract.  There are two options: buyram or buyrambyes.  In this case the system contract is just an interface so the logic lies in other native code.

There is a website that attempts to calculate the price too..

It is in delegate_bandwidth.cpp
```cpp
   /**
    *  This action will buy an exact amount of ram and bill the payer the current market price.
    */
   void system_contract::buyrambytes( account_name payer, account_name receiver, uint32_t bytes ) {
      auto itr = _rammarket.find(S(4,RAMCORE));
      auto tmp = *itr;
      auto eosout = tmp.convert( asset(bytes,S(0,RAM)), CORE_SYMBOL );

      buyram( payer, receiver, eosout );
   }
```
The price is calculated in `convert` where the code sends bytes and gets the EOS out.  Then buyram deducts a fee you mentioned:

https://github.com/EOSIO/eos/blob/d7a6fd10ac0ab34595068f339f8b3d24a06f1db3/contracts/eosio.system/delegate_bandwidth.cpp#L105-L118

So now back to `convert` to answer how to find market price..  When the system contract eosio.system.cpp is constructed it sets a price from a global `free_ram` variable by inserting a row into the _rammarket list (emplace).  That gets things started.  Now, when convert is called we need to figure out what object that really is.

This line of code `rammarket              _rammarket;` lead me to this: 
```c++
typedef eosio::multi_index<N(rammarket), exchange_state> rammarket;
```

The `convert` function is in exchange_state (eosio/eos/contracts/exchange/exchange_state.cpp)

convert_from_exchange is the case above .. This is at the point where you might plug in numbers to see if your getting the same results as your transaction.

In the exchange_state.hpp this looks interesting:
```c++
   /**
    *  Uses Bancor math to create a 50/50 relay between two asset types. The state of the
    *  bancor exchange is entirely contained within this struct. There are no external
    *  side effects associated with using this API.
    */
   struct exchange_state //...
```

**Comment by songsongMr** [comment]
Thank you for your information @jcalfee

**Comment by jcalfee** [comment]
This is a very interesting white paper: https://storage.googleapis.com/website-bancor/2018/04/01ba8253-bancor_protocol_whitepaper_en.pdf
