### ISSUE TITLE
tr.newaccount    fail  :  [ERR_ASSERTION]: Invalid public key  

### ISSUE THREAD

**Issue by rehylas** [EOSIO/eosjs#261]
**my code:**
pubkey = 'EOS5B2sXhg52iqzhGYBr2sbsUbimacqSSRptYXPgtYyM3grPNyjLw'
`        let res = eos.transaction(   tr => {
            tr.newaccount(
                {
                    creator: CREATE_USER ,
                    name: name,
                    owner: own_pubkey,
                    active: active_pubkey
                }
            )
        }
        ).then( (res  )=>{}

**exception:**
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
undefined
{ AssertionError [ERR_ASSERTION]: Invalid public key
    at Object.PublicKey (E:\work\系统开发项目\区块链\code\ncc\eosjs\node_modules\eosjs-ecc\lib\key_public.js:32:12)
    at E:\work\系统开发项目\区块链\code\ncc\eosjs\lib\index.js:210:38
    at Array.map (<anonymous>)

**`eosjs-ecc\lib\key_public.js    code , line 202  - 210 :**
            console.log('%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%');
            console.log(key);
            keys = keys.map(function (key) {
              try {
                // normalize format (WIF => PVT_K1_base58privateKey)
                return { private: ecc.PrivateKey(key).toString() };
              } catch (e) {
                // normalize format (EOSKey => PUB_K1_base58publicKey)
                return { public: ecc.PublicKey(key).toString() };   //line 210
              }

**random happen  this error**

**Comment by jcalfee** [comment]
Your code defines pubkey but uses own_pubkey and active_pubkey ..

You might need to buy ram and cpu as is done here:
https://github.com/eosio/eosjs#new-account

New account is a bit tricky but it does eventually work..

**Comment by chris-allnutt** [comment]
@rehylas I would recommend adding a linter to your dev environment as it would help catch small issues like this.
