### ISSUE TITLE
errors are not handleable - unhandled promise rejections

### ISSUE THREAD

**Issue by robertkowalski** [EOSIO/eosjs#262]
hi james, it seems the error with unhandled promise rejections reappeared.

it happens when the eos node returns an error and also if you do not have a connection to the node.

to easily reproduce turn off the eos node and make a simple call to a contract.

result:

```
(node:5666) UnhandledPromiseRejectionWarning: FetchError: request to http://localhost:8888/v1/chain/get_table_rows failed, reason: connect ECONNREFUSED 127.0.0.1:8888
    at ClientRequest.<anonymous> (/Users/robert/candyshop/node_modules/node-fetch/index.js:133:11)
    at ClientRequest.emit (events.js:127:13)
    at Socket.socketErrorListener (_http_client.js:394:9)
    at Socket.emit (events.js:127:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:152:19)
(node:5666) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

**Comment by robertkowalski** [comment]
interestingly, the issues, are logged as errors, but are not catchable via `.catch` or callback with the current apis:

```
api < error 	  http://localhost:8888/v1/chain/get_table_rows {"code":"candyshop","scope":"foo.b","table":"sweets","limit":200,"json":true}
{ FetchError: request to http://localhost:8888/v1/chain/get_table_rows failed, reason: connect ECONNREFUSED 127.0.0.1:8888
    at ClientRequest.<anonymous> (/Users/robert/candyshop/node_modules/node-fetch/index.js:133:11)
    at ClientRequest.emit (events.js:127:13)
    at Socket.socketErrorListener (_http_client.js:394:9)
    at Socket.emit (events.js:127:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:152:19)
  name: 'FetchError',
  message: 'request to http://localhost:8888/v1/chain/get_table_rows failed, reason: connect ECONNREFUSED 127.0.0.1:8888',
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED' }
```

**Comment by jcalfee** [comment]
I see ouch..  This part of the code has not changed in a while so it is probably not version related.  I tested with the node up at first then taking it down, also with the node down the entire time.  I can always catch the error.

If you provided a custom logger and its throws an error that should be safe too but that would be another thing to check..

```js
eos.contract('candyshop').then((contract) => { console.log('yay') }) .catch((err) => { console.log('ouch') })
api > post 	 http://127.0.0.1:8888/v1/chain/get_abi {"account_name":"candyshop"}
Promise {
  <pending>,
  domain:
   Domain {
     domain: null,
     _events:
      { removeListener: [Function: updateExceptionCapture],
        newListener: [Function: updateExceptionCapture],
        error: [Function: debugDomainError] },
     _eventsCount: 3,
     _maxListeners: undefined,
     members: [] } }
> api < error 	  http://127.0.0.1:8888/v1/chain/get_abi {"account_name":"candyshop"}
{ FetchError: request to http://127.0.0.1:8888/v1/chain/get_abi failed, reason: connect ECONNREFUSED 127.0.0.1:8888
    at ClientRequest.<anonymous> (/home/james/eosjs/eosjs/node_modules/node-fetch/index.js:133:11)
    at ClientRequest.emit (events.js:182:13)
    at ClientRequest.EventEmitter.emit (domain.js:442:20)
    at Socket.socketErrorListener (_http_client.js:382:9)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  name: 'FetchError',
  message:
   'request to http://127.0.0.1:8888/v1/chain/get_abi failed, reason: connect ECONNREFUSED 127.0.0.1:8888',
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED' }
ouch
```

![image](https://user-images.githubusercontent.com/204121/42945448-0e5e9640-8b2e-11e8-95ab-fd197b5ec672.png)

**Comment by robertkowalski** [comment]
> I can always catch the error.

hmmm i agree, its logging an error. not sure if we are on the same page:

the problem is that it **just** logs, but the promise is never rejected, which means my `.catch` is never called. 

in practice that means for my program it looks like the promise if always fullfilled, even when there was an error. for error handling, i then just have log output on the console.

**Comment by robertkowalski** [comment]
thx for checking james, the error comes from calling the constructor when the eos node is down

maybe eosjs should throw sync in case of an error there:

```js
try {
  const eos = Eos({})
} catch (e) {
  console.log(e) // node down? maybe error code has some information...
}
```


or there could be something like this in future versions:

```js
const eos = Eos({ init: false })
// no connection to external servers is made
eos.start(cb)
// now making chain calls and returning errors to callback / promise

```

**Comment by jcalfee** [comment]
Will it work to simply turn off logging?  It is just checking the chainId for the purpose of warning you if it does not match.  That is not required.  You will still get all the other errors in the catch block..

```js
Eos({logger: {error: null}})
```

**Comment by gaboesquivel** [comment]
perhaps adding unhandledrejection event handler 

```js 
if(window){
  window.addEventListener("unhandledrejection", function (event) {
  console.warn("WARNING: Unhandled promise rejection. Shame on you! Reason: "
               + event.reason)
  })
}else{
 require('make-promises-safe)
}

```

**Comment by chris-allnutt** [comment]
@gaboesquivel adding an unhandled rejection at the window level could conflict with implementation code that utilized the library.  If I have one in my application and eosjs also has one which one wins?

**Comment by jcalfee** [comment]
The error above is not unhandled, it was just being logged and causing confusion.  I believe Robert something in his code.

So, since it is expected that the user catch all errors (and they will see the unhandled error if they forget), I think it is better to move the errors to the "verbose" flag ..  This will avoid the case that seems to be more common now where they user needs to turn off the error log ..

So, "verbose: true" will print API requests and errors (and potentially javascript will bark about unhandled).  And "verbose: false" will turn off API and error logging but javascript will still bark about unhandled errors.

**Comment by gaboesquivel** [comment]
@chris-allnutt yeah. 

@jcalfee sounds good.
