### ISSUE TITLE
http://ayeaye.cypherglass.com:8888 unreachable

### ISSUE THREAD

**Issue by cAstraea** [EOSIO/eosjs#264]
Hello. 
Think this node in unreachable at the moment ? http://ayeaye.cypherglass.com:8888
All requests failing
Anyone knows what the status is on this ? 
Cheers

**Comment by chris-allnutt** [comment]
Ask cypherglass, eosjs is not affiliated or directly involved with them.

**Comment by jcalfee** [comment]
@cAstraea please let me know if you find an alternative .. I'm looking for this as well.

**Comment by cAstraea** [comment]
This is what they reported currently.

Hi! This is an old TESTNET end point from before Mainnet. We are not currently participating in the testnet while we shuffle our dedicated infrastructure. We’ll broadcast our new endpoint in a week or two for the testnet, many thanks for the note @reloadro

Heh dunno really :) There's some block producer that participating in the jungle testnet https://jungle.eosmonitor.dutcheos.io/
