### ISSUE TITLE
Issue when pushing multiple transactions

### ISSUE THREAD

**Issue by eosbet-io** [EOSIO/eosjs#270]
When I push multiple transactions the first transactions pushes and is executed without any problems. All other transactions get the error:
```
 UnhandledPromiseRejectionWarning: 
Error: {"code":500,"message":"Internal Service Error","error":{"code":13,"name":"St9exception",
"what":"could not insert object, most likely a uniqueness constraint was violated",
"details":[{"message":"could not insert object, most likely a uniqueness constraint was violated: ",
"file":"wasm_interface.cpp","line_number":1326,"method":"send_deferred"},
{"message":"","file":"apply_context.cpp","line_number":62,"method":"exec_one"}]}}
```

This happens with both eos.transaction({...args}) as well as eos.transaction({...args},{broadcast:false}).then(assemble all transactions into an array and use eos.pushTransactions on the array of unpushed transactions.

Seems like an issue with the library. These transaction objects are unique, and the actions, signatures and hashes are differing amongst all the transactions. (ie: not cleos error `Error 3040008: duplicate transaction`)

Thanks for any help.

**Comment by chris-allnutt** [comment]
That error is coming from the node not eosjs.  I would recommend retesting with cleos to track down the issue with the contract.

**Comment by eosbet-io** [comment]
You're right. The error was a deferred transaction primary key conflict when we were pushing a large amount of transactions as once (which is why is only showed up with this script). Thank you for the help!
