### ISSUE TITLE
Getting the following when trying to push a custom action to the cotnract deployed under eosio.token

### ISSUE THREAD

**Issue by surabhil** [EOSIO/eosjs#271]
I added some new actions to the eosio.token standard contract and deployed it under eosio.token account name. It works fine with cleos but with eosjs it gives the following error. 
```
TypeError: Unknown struct 'approve' for contract 'eosio.token', locate this struct or provide serialized action.data action.data
```
Note: this only happens for eosio.token. Doesnt happen for any other custom contracts.

**Comment by chris-allnutt** [comment]
Is this on a local node?  eosio.token isn't a standard user account and can only be updated with producer consensus.

**Comment by surabhil** [comment]
Yes, its a local node.

**Comment by chris-allnutt** [comment]
Did you deploy a new abi with the contract?

What happens if you call get_abi on the account?

Are those structs in the abi returned?

**Comment by surabhil** [comment]
Yes, the new structs are returned but because the schema eosio_token,json in src/schema doesnt have those structs, its failing.

**Comment by surabhil** [comment]
Yes it works under a different account. I am running version 15.0.0

**Comment by jcalfee** [comment]
It looks like "approve" is a helper in cleos .. Try printing the json from cleos to be sure it matches your eosjs code.. It is common to disable broadcast in cleos too (add `-Dj` flags).

>auto approve_producer = actionRoot->add_subcommand("approve", localized("Add one producer to list of voted producers"));

**Comment by jcalfee** [comment]
I see .. You are correct, it has a cache and that ends up on the eos.* instance .. You can however pull the contract anyways so you can get your custom abi actions:
```js
const token = eos.contract('eosio.token')
token.customAction()
```
Hope that helps..
