### ISSUE TITLE
how to change transcation permission

### ISSUE THREAD

**Issue by xntop** [EOSIO/eosjs#273]
const rawTx = await eosjsInstance.transaction(tr => {
            tr.buyrambytes({
                payer: payer,
                receiver: receiver,
                bytes: bytes
            })
        }, {authorization: '1111@owner'});

but the rawTx action permission is still active, how to change the action permission by using transaction function.

**Comment by jcalfee** [comment]
try:
```js
    const rawTx = await eosjsInstance.transaction(tr => {
        tr.buyrambytes({
            payer: payer,
            receiver: receiver,
            bytes: bytes
        }, {authorization: '1111@owner'})
    });
```

**Comment by xntop** [comment]
thanks,  it works
