### ISSUE TITLE
typescript ?

### ISSUE THREAD

**Issue by gaboesquivel** [EOSIO/eosjs#278]
While working on #276 I noticed there are some function with different return values. In `format.js` I found two `DecimalPad` https://github.com/EOSIO/eosjs/pull/276/commits/80c3f6f0d4af69e527174c714aea8bc455de60dc and `parseAsset` https://github.com/EOSIO/eosjs/pull/276/commits/3ef13f3743be9b358c02f47263995eae16201279.

I think this project should be as robust as it can possibly be, so perhaps adding TypeScript is good idea. 

PR #276 already enforces ESLint [eqeqeq](https://eslint.org/docs/rules/eqeqeq) which reduces this type of problem a bit. That's how I found those bugs.

**Comment by chris-allnutt** [comment]
Typescript is not something we want to pursue at this time.
