### ISSUE TITLE
Is private key send to the mainnet/testnet I am connected to or the transactions are signed locally?

### ISSUE THREAD

**Issue by kartik-koinex** [EOSIO/eosjs#279]
When I initialise an eos instance and provide my private key to it, does it sendss the key to network at any point of time or is it just used to sign the transactions locally?

**Comment by jcalfee** [comment]
no never..  transactions are converted to binary locally and signed locally

**Comment by chris-allnutt** [comment]
Closing.  @jcalfee ‘s response cover it.
