### ISSUE TITLE
Error building with 6.1.8 on create-react-app, works with 6.1.6

### ISSUE THREAD

**Issue by wpwood** [EOSIO/eosjs#28]
When building a React application created with `create-react-app` and adding eosjs 6.1.8 as a dependency, building the app (`npm run build`) results in the following error:
```
root@blockone:~/block.one# npm run build

> block.one@0.1.0 build /root/block.one
> react-scripts build

Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 

 	./node_modules/eosjs/lib/write-api.js:98 

Read more here: http://bit.ly/2tRViJ9

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! block.one@0.1.0 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the block.one@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-03-11T14_53_14_563Z-debug.log
```

This is happening because the compiled version of eosjs 6.1.8 (shipped via npm) still has an `async` keyword in the ES5 version of the code. The line in question is https://github.com/EOSIO/eosjs/blob/3dbee2426626c1ebe8c8bd3fe585eb1362457aac/src/write-api.js#L82

Forcing the build to use eosjs 6.1.6 fixes the issue.

**Comment by jcalfee** [comment]
eosjs@6.1.9
