### ISSUE TITLE
eosjs transfer error

### ISSUE THREAD

**Issue by joeylin** [EOSIO/eosjs#280]
![image](https://user-images.githubusercontent.com/2030833/43434242-722d6b3c-94ad-11e8-98c5-56d15d0ecc69.png)
I got below error, I try several times, I can not find what goes wrong
`{"code":500,"message":"Internal Service Error","error":{"code":3050003,"name":"eosio_assert_message_exception","what":"eosio_assert_message assertion failure","details":[{"message":"assertion failure with message: unable to find key","file":"wasm_interface.cpp","line_number":930,"method":"eosio_assert"},{"message":"pending console output: ","file":"apply_context.cpp","line_number":61,"method":"exec_one"}]}}
`

**Comment by jcalfee** [comment]
Very vague message from the back-end .. ;( .. Did you create and issue the IPOS asset?  You have to do both before you can transfer.  There is an example in this repo in docker/up.sh ..
