### ISSUE TITLE
eos.setcode('hello', 0, 0, wasm, abi) get error code: 65533 

### ISSUE THREAD

**Issue by AdamBylin** [EOSIO/eosjs#281]
![image](https://user-images.githubusercontent.com/5262725/43462969-065e261e-950a-11e8-83a1-97620ed316f0.png)

**Comment by jcalfee** [comment]
You should probably run the example in the README by hand and make sure the data types are the same.  It will probably help you to have a working example to inspect.  Generally a Buffer and Array will work as the same..

**Comment by AdamBylin** [comment]
thx , a Buffer is work.
