### ISSUE TITLE
How to use `eosjs` with multiple dynamic keys provider

### ISSUE THREAD

**Issue by navcsdev** [EOSIO/eosjs#282]
My case, when an account call my action in my contract they will provide `keyProvider` then I must re-create `eosjs` with new `keyProvider`.

Do we have another way to solve it ? 🙇

**Comment by jcalfee** [comment]
Pass a function: `keyProvider = () => dynamicKeys`

**Comment by pearsonbee** [comment]
@jcalfee same problem for me, would you please tell how to do that? or is there an example available? thanks so much!

**Comment by jcalfee** [comment]
See [configuration](https://github.com/eosio/eosjs#configuration) keyProvider..
>  If a function is provided, this function is called for each transaction.

```js
let userProvidedKey = null
eos = Eos({keyProvider: ()=> userProviderKey})

// set the key
userProvidedKey=privateKey1
await eos.action('user' ..)

// change the key
userProvidedKey=privateKey2
await eos.action('user2' ..)
```

I could add a feature and accept the keyProvider here too:
```js
// proposed, does not work
await eos.action('user2' .., {keyProvider: privateKey2})
```

The proposed change it probably better, it does not leave the varible `userProvidedKey` layout around..

**Comment by pearsonbee** [comment]
@jcalfee great job, I'am so appreciate that and will follow this guide. thank you very much!

**Comment by KunkaYU** [comment]
@jcalfee  so appreciate！ but maybe there is a spell mistake in 'userProviderKey/userProvidedKey'

**Comment by jcalfee** [comment]
Where is the spelling mistake?

**Comment by IgorPeresunko** [comment]
> Pass a function: `keyProvider = () => dynamicKeys`

How can I do it in `eosjs@beta` ?

**Comment by iKest** [comment]
Scatter use new Proxy class for inject custom keyprovider.
