### ISSUE TITLE
Question: Does eosjs support React Native?

### ISSUE THREAD

**Issue by Nanofortress** [EOSIO/eosjs#286]
Hello I am new into developing app with eosio. I am trying to develop a mobile app that uses blockchain involving creating and verifying account. I am wondering does anyone know if eosjs can be used on React Native? Or is there another tool that can build mobile apps that you recommend? Any thought is appreciated, thanks!

**Comment by MarcelBlockchain** [comment]
check out https://github.com/EvaCoop/eosjs-react-native

it's not perfect yet

**Comment by antbaobao** [comment]
@MarcelBlockchain this module is working in ios, but when I use this module in android, it makes the app broken, any help? thanks

**Comment by MarcelBlockchain** [comment]
@antbaobao open a new issue and share what the error looks like. There you get an answer from the creators:
https://github.com/EvaCoop/eosjs-react-native/issues?q=is%3Aopen+is%3Aissue

**Comment by lXSPandora** [comment]
@antbaobao 
i found this one im trying to figure out how to use it but it seems to work! 
https://github.com/espritblock/react-native-eos

**Comment by bitromedian** [comment]
> @MarcelBlockchain this module is working in ios, but when I use this module in android, it makes the app broken, any help? thanks

I have the same issue on Android. An exception occurs during initializing new object. It seems like due to the commit e54586e172294d2e30378e475b556276cdcb16ac.

**Comment by jcalfee** [comment]
Just want to make sure this is still open source..
https://github.com/espritblock/react-native-eos/issues/3

**Comment by espritblock** [comment]
[espritblock/react-native-eos](https://github.com/espritblock/react-native-eos)
I updated the version and added the development notes to see readme

**Comment by amolmaid** [comment]
@espritblock 
So does it works with the React Native apps which were created using `react-native Expo projects` i.e Expo dependant projects ?

**Comment by MarcelBlockchain** [comment]
no

**Comment by espritblock** [comment]
> @espritblock
> So does it works with the React Native apps which were created using `create-react-native-app cli` i.e Expo dependant projects ?

I haven't tried it on Expo, you can have a try.

**Comment by Velua** [comment]
I've found this project a little easier to integrate, https://github.com/Game-X-Coin/eosjs-rn#readme

**Comment by eedsilva** [comment]
@Velua did you get it to work?

**Comment by MarcelBlockchain** [comment]
check out react-native-eos from Eva, probably the best solution used in production.

https://github.com/EvaCoop/react-native-eos
