### ISSUE TITLE
Public EOSJS API /v1/history/get_transaction broken if txid is an `action` transaction

### ISSUE THREAD

**Issue by grigio** [EOSIO/eosjs#287]
With the latest update I can't find a public API to get details about a transaction that I know it exist, sometimes I get the CORS error, sometimes I get this.. Some days ago it worked

```
{"code":400,"message":"Bad Request","error":{"code":3040011,"name":"tx_not_found","what":"The transaction can not be found","details":[{"message":"Transaction efec8d264dfce6f8d26f8f8101283308cb9ac78aaf89bc4db35ff5f79bfe3fcf not found in history and no block hint was given","file":"history_plugin.cpp","line_number":396,"method":"get_transaction"}]}}
```

**Comment by grigio** [comment]
another website affected by this
![screenshot from 2018-08-06 12-21-56](https://user-images.githubusercontent.com/8074/43715969-a35ee440-9982-11e8-8ce9-704252ff8eda.png)

**Comment by jcalfee** [comment]
The key part of the error is: "tx_not_found" .. It is an error from the API..

**Comment by jcalfee** [comment]
It could of course be something in the database .. In that case, there will likely be an issue here: http://github.com/eosio/eos ..

**Comment by grigio** [comment]
@jcalfee I think it's releated with history plugin in the backend, I tried several public apis and I get the same error. Other deployed sites stopped to work.

**Comment by grigio** [comment]
Found a working API.. I hope they will not upgrade it `curl  https://api1.eosasia.one/v1/history/get_transaction -d '{"id":"efec8d264dfce6f8d26f8f8101283308cb9ac78aaf89bc4db35ff5f79bfe3fcf"}'`
