### ISSUE TITLE
eosjs catching error in promise provides no useful data

### ISSUE THREAD

**Issue by altShiftDev** [EOSIO/eosjs#290]
```
    txPusher (tx) {
      eos.pushTransaction(tx)
        .then(response => {
          console.log(response)
          this.responseData = response
        })
        .catch(e => {
          console.log(e)
          this.responseData = e
        })
    }
```
I'll get useful data back if the transaction succeeds but if it fails, all I'm able to process out of my `.catch` is this:

```
{
  "status": 400,
  "statusText": ""
}
```
And even those two fields are unreliable... But I can see the API is spitting out a ton of useful info I could present to the user to let them know why their transactions are failing but it doesn't seem to be accessible from catch. Like even `message:"expired transaction"` would be great.

Here's the full error I see in console:
```
{  
   message:"expired transaction 76d1fe45f88b57134a6495762edca7a7ccf2436663ff6364e27e5dfed7810649",
   file:"producer_plugin.cpp",
   line_number:357,
   method:"on_incoming_transaction_async"
}https://jungle.eosio.cr:443/v1/chain/push_transaction{  
   "compression":"none",
   "transaction":{  
      "expiration":"2018-08-06T02:39:54",
      "ref_block_num":60533,
      "ref_block_prefix":1681592108,
      "net_usage_words":0,
      "max_cpu_usage_ms":0,
      "delay_sec":0,
      "context_free_actions":[  

      ],
      "actions":[  
         {  
            "account":"eosio.token",
            "name":"transfer",
            "authorization":[  
               {  
                  "actor":"altshiftdev1",
                  "permission":"active"
               }
            ],
            "data":"10b64a79b98673340000000000000000102700000000000004454f530000000000"
         }
      ],
      "transaction_extensions":[  

      ]
   },
   "signatures":[  
      "SIG_K1_JyfSKRXuSUZgioMVeMWfo52pF7fqS48W5JrMi4QfxAjnokLGK1rH2HC6jupJNPcCtbHtieiEYt7xCmZqZPFGbWL12QL8Qo"
   ]
}
```

**Comment by jcalfee** [comment]
Here is how I handle pushTransaction ..  The `callback(error)` sends the error to the user's callback or Promise (depending on which one they used).
```js
                } else {
                  network.pushTransaction(packedTr, function (error, processedTransaction) {
                    if (!error) {
                      callback(null, Object.assign({
                        broadcast: true,
                        transaction: packedTr,
                        transaction_id: transactionId
                      }, processedTransaction));
                    } else {
                      if (config.logger.error) {
                        config.logger.error('[push_transaction error] \'' + error.message + '\', transaction \'' + buf.toString('hex') + '\'');
                      }
                      callback(error.message);
                    }
                  });
                }
              }).catch(function (error) {
                if (config.logger.error) {
                  config.logger.error(error);
                }
                callback(error);
              });
```

In the case of expired tx exception like the one you gave above you get an error string from the server:
```js
eos.transfer('jamescjungle', 'eosio', '1.0000 JUNGLE', '', {broadcast: true}).then(r=>console.log(r)).catch(err => {console.error('error=>', err)})
```
`error=> {"code":400,"message":"Bad Request","error":{"code":3040005,"name":"expired_tx_exception","what":"Expired Transaction","details":[{"message":"expired transaction 0163c67c77f7c5378d7a5e5564300261cb2802ddefe64bf8d68d86236141dd60","file":"producer_plugin.cpp","line_number":357,"method":"on_incoming_transaction_async"}]}}`

**Comment by altShiftDev** [comment]
Hi James,
My problem is I can't actually access any details of that error. 90% of that string is garbage to the user, what could reasonably be displayed and understood would be either `"name":"expired_tx_exception"` or `"what":"Expired Transaction"`

Can you actually access error.error.name or .what? If you can, I'd love to see how you assign those to a variable for displaying to the user.

**Comment by jcalfee** [comment]
I think your going to need to build it out, something like this:
```js
const userError = []
try {
  const obj = JSON.parse(error)
  obj.error.details.forEach(d => {userError.push(d.message)}
  if(userError.length === 0) {
    userError.push(obj.error.what)
  }
} catch(err) {
  console.error(err)
}
if(userError.length === 0) {
  userError.push('Unknown error, this has been reported')
  // upload error
}
show(userError.join(', '))
```

API end-points have to enable "details" using a flag to nodeosd, so count on that array being empty.

**Comment by altShiftDev** [comment]
@jcalfee 
Ya, you're right it has to be done the hard way. For future reference and to help anyone else trying to make sense of the errors here's the main issue:

**Error:** {"code":400,"message":"Bad Request","error":{"...

The errors don't actually come back as string if you use a promise, the browser detects them as an object of some invalid type due to the prefix "Error: " (bolded above). If you convert all of it to a string, and remove the offending party, it magically becomes a valid json that can be iterated through.

Here's my latest code based on Jame's above:

```
    txPusher (tx) {
      eos.pushTransaction(tx)
        .then(response => {
          console.log('Pushed', response)
          this.responseData = response
          this.txid = response.transaction_id
        })
        .catch(e => {
          console.log(e)
          const userError = []
          try {
            console.log('e', typeof e) // detected as type: object, although not a proper json...
            let cleanErr = e.toString().replace('Error: ', '')
            const obj = JSON.parse(cleanErr)

            obj.error.details.forEach(d => {
              userError.push(d.message)
            })
            console.log('userError', userError)

            //  No "to" account name provided in the transaction:
            // ["assertion failure with message: to account does not exist", "pending console output: "]

            // 'to' account provided but non-existant:
            // ["assertion failure with message: to account does not exist", "pending console output: "]

            // tx expired
            // ["expired transaction a6d97488cbbce2fd05765faaec3ff6e992dad6f09529e832456de025221540dd"]

            // not authorized to send 'from' as account doesn't exist 
            // ["action's authorizing actor 'altshiftdevz' does not exist"]

            // unauthorized since you don't own this account but it does exist
            // ["transaction declares authority '{"actor":"999invalid","permission":"active"}', but does not have signatures for it under a provided delay of 0 ms, provided permissions [], and provided keys ["EOS63GHmouu1tSqm4x17nrW9BvkECRnVUYLWY1Epn62rgBMC8Tdz1"]"]

            // insufficient funds
            // ["assertion failure with message: overdrawn balance", "pending console output: "]
          }
          catch (err) {
            console.error('Catch', err)

            if (userError.length === 0) {
              userError.push('Unknown error, this has been reported')
            }
            console.log(userError.join(', '))
          }
        })
```

As you might have noted in my comments I started collecting a small database of error and what they mean in English. I intend to regex these and provide my own translated versions which are more user-friendly whenever possible. Also of note here is there's usually a 2nd details object which simply says "pending console output: " which I'm sure is going to occasionally swap places with the useful string at position [0] to annoy me so additional validation will be needed.

Technically this issue could be closed... but I'd rather it wasn't until more effort has been made to resolve the two problems found here:

1. More effort placed in making errors more human readable and friendly.
2. Valid json in error output so JavaScript processing can be done humanely and more reliably.
3. Removal of extra garbage like: "pending console output"

Lowering the effort required for devs to make better user experiences will in turn lower the technical barriers presented to new users who already believe EOS is difficult/confusing/technical. While I'm making an effort to parse this garbage, regex it and translate that to human-speak, I really don't want to and I imagine a lot of others won't even bother. This just means end-users won't know what went wrong with their transactions and increases their frustration with EOS.

**Comment by jcalfee** [comment]
Many of the code and error messages are here:
https://github.com/EOSIO/eos/blob/v1.1.4/libraries/chain/include/eosio/chain/exceptions.hpp

Translations will probably be done using the code or message, we can find out more by looking in the EOSIO/eos to see.  I did not see any translation tickets yet.  But it would be good to know how this should be done even if the app is only one language (so it will be compatible).  I imagine another npm module could be created that would handle these errors so one can be selective about language, verbiage and size.
