### ISSUE TITLE
Support of symbol_code abi type

### ISSUE THREAD

**Issue by sim31** [EOSIO/eosjs#295]
EOSIO has `symbol_code` type in the abi. Basically it's just a symbol name without precision. It's `symbol_name` (uint64_t) type inside contract (don't know why the inconsistency with naming).

I tried to take this type as a parameter to an action. It works fine through cleos - you pass it as a string to push action command and it works as expected.

When I tried to use that action through eosjs however it expected some integer type. Would be great if I could pass a string and it would do conversion as necessary.

**Comment by jcalfee** [comment]
Released eosjs@16.0.2

**Comment by sim31** [comment]
Great! it works now, thanks.
