### ISSUE TITLE
Support case: action.name==setabi & action.data is hex string

### ISSUE THREAD

**Issue by masonhunk** [EOSIO/eosjs#296]
Hi,

When signing a transaction containing actions of "setabi", some unexpected error may  happen.

Reproduce:

1) The action.data contains two fields: account, abi. abi is read from some .abi file.
2) use fc buffer to serialize abi field to hex(v1/chain/abi_json_to_bin will accept hex instead of json object so in my code I have to do this). 
3) use eos rpc: v1/chain/abi_json_to_bin to serialize above action.data to a HEX string.
4)create a transaction with above action. And sign it.

In the serialization process of step 4, the hex format of data is firstly converted back to json like this in eosjs/lib/structs.js/actionDataFromObject:

{
    "account":"aaron",
    "abi":"00fecde9..."
}

it is important that the abi is still in hex format. Then in eosjs/lib/structs.js/setabi.abi.appendByteBuffer, the object.abi is passed into abi serializer:

      var b2 = new ByteBuffer(ByteBuffer.DEFAULT_CAPACITY, ByteBuffer.LITTLE_ENDIAN);
      ser.appendByteBuffer(b2, object.abi);
      
      b.writeVarint32(b2.offset); // length prefix
      b.append(b2.copy(0, b2.offset), 'binary');

The above code works for the case when the object.abi is a JSON object instead of hex string. I think we should adjust the code like this:

      var ser = structLookup('abi_def', 'eosio');

      var b2 = new ByteBuffer(ByteBuffer.DEFAULT_CAPACITY, ByteBuffer.LITTLE_ENDIAN);

      if(typeof object.abi == 'object'){
        ser.appendByteBuffer(b2, object.abi);
      }
      else{ //in case that the object.abi is a hex string.
        var buf = new Buffer(object.abi, 'hex');
        b2.append(buf);
      }
            b.writeVarint32(b2.offset); // length prefix
      b.append(b2.copy(0, b2.offset), 'binary');

**Comment by jcalfee** [comment]
Released eosjs@16.0.2

**Comment by masonhunk** [comment]
@jcalfee 

Good job!
