### ISSUE TITLE
Missing support for custom symbol

### ISSUE THREAD

**Issue by trungtt1981** [EOSIO/eosjs#298]
The EOSIO build script `eosio_build.sh` nicely supports to build the EOS software with custom symbol via the option `-s`.

However, the library `eosjs` is missing an option to set such a custom symbol. 
Indeed, the API `newaccount()` knows only the `EOS` symbol and thus it will lead to the failed transaction if interacting with the nodeos built with custom symbol other than `EOS`.

**Comment by jcalfee** [comment]
Is this the same issue?

https://github.com/EOSIO/eosjs/issues/258

**Comment by jcalfee** [comment]
EOSIO/eosjs-ecc#30

Released in eosjs@16.0.2 and eosjs-ecc@4.0.3
