### ISSUE TITLE
Restrictions when creating an account

### ISSUE THREAD

**Issue by AndriiKr** [EOSIO/eosjs#3]
I want to use emails or numeric id as usernames but there are restrictions while account creating like this: 'A name can be up to 13 characters long' or 'Invalid character' except '.12345abcdefghijklmnopqrstuvwxyz'. Any way to bypass that?

**Comment by jcalfee** [comment]
No, that is a restriction on the blockchain.  It greatly improved the performance when it was added so it is best to work with it..

**Comment by dskvr** [comment]
@AndriiKr Usernames are Base32, those restrictions cannot be bypassed.

**Comment by jcalfee** [comment]
Close to Base32 .. only goes up to the number 5 .. the 13th character is restricted too, it can't go further than `j` (so don't use k-z)..

https://github.com/EOSIO/eosjs/blob/master/src/format.test.js#L12-L13
