### ISSUE TITLE
eosjs - unable to set the contract using front end method call

### ISSUE THREAD

**Issue by amolmaid** [EOSIO/eosjs#300]
Hi,

   I am working on a _dAPP_ whose front end is in _reactJS_ and currently getting the **.abi** and **.wasm** files from backend _nodeJS_ via an API response; and trying to set the contract on user's account by taking permission/signature from scatter at front end.

**1. Please find my code snippet bellow,**
![publish contract code](https://user-images.githubusercontent.com/7837458/43957433-777e4df2-9cc5-11e8-8474-86517e7ce1f0.png)

**2. After accepting the scatter permission I am getting this error,** ( I am using binaryen too)
![binerian error](https://user-images.githubusercontent.com/7837458/43957469-8a69b8ca-9cc5-11e8-8f3d-e95183dc5658.png)

**3. Nodeos showing following error,**
![nodeos error set contract](https://user-images.githubusercontent.com/7837458/43957477-93857c64-9cc5-11e8-95bd-bf65ed3dddfa.png)

**Note** - <h3>I tried the same thing by providing the keys with _binaryen_ also, but it flags the same error msg. </h3>

**Comment by jcalfee** [comment]
the log says:
```
authroization = 
Object
  data: [numbers]
  type: Buffer
```
So that looks like a typo..

The option is called `{binaryen}` not `{binaryen1}`..  That is needed and used only if the very beginning of your smart contract data starts with `(module` ..


Although setcode works with a buffer, I do wonder if HEX might help.  You can try with `result.data.wasm.data.toString('hex')` ..

Lets see more details just about the wasm data your sending, that is what the error is about.  You can try creating Eos with `Eos({forceActionDataHex: false, ..})` so you can more easily see what is getting submitted.

**Comment by amolmaid** [comment]
Hi @jcalfee ,

   Thanks for your response, 

   I did correct the typo,  and tried again; And now tried to see if there is any difference in file's content type.  
when I read the file in back end and send it in json, its basically converts the buffer type file to JSON.stringify(wasm) format.
   So It was still failing to convert it back to the buffered format which we need to pass to eosScatter.setCode() method. Also the JSON.parse(wasm) don't work on received data in front end.

**Please check the following results' screen shots**
**1. Front end code**
![2 front endfrom 2018-08-13 16-01-15](https://user-images.githubusercontent.com/7837458/44027314-a6697272-9f13-11e8-9a5b-aedcd9e7ce1f.png)

**2. Front end failing**
![browserm 2018-08-13 16-00-27](https://user-images.githubusercontent.com/7837458/44027326-b114c082-9f13-11e8-968f-578231cdbfb6.png)

**3. Back end code and output**
![3 backend rom 2018-08-13 16-04-44](https://user-images.githubusercontent.com/7837458/44027337-bd002986-9f13-11e8-93d3-4df83470b381.png)

I would be really appreciate if you could guide for this ...
Thanks in advance.

**Comment by amolmaid** [comment]
Hi,

   I was able to solve that one with following line of code
`eosScatter.setcode(account.name, 0, 0, Buffer.from(JSON.parse(JSON.stringify(result.data.wasm)).data), options2).then((res1, error1) =>{ ...... }`
-- Now sure  how did work though, but its actually changing the code of an account checked via cleos.

Thanks.

**Comment by amolmaid** [comment]
Hi,
   I still stuck at setAbi(), does it has overridden method which takes version as parameter or anything ?
I am using this function here
`eosScatter.setabi(account.name, Buffer.from(result.data.abi.data), options3).then((res, error) => {`

![abi from 2018-08-14 13-55-01](https://user-images.githubusercontent.com/7837458/44080624-3b7c42b6-9fca-11e8-9328-de32d86c2d55.png)

**Please guide for the above error**

**Comment by jcalfee** [comment]
Version is the 1st field it tries to parse in the ABI.  Try eosjs@16.0.2, it accepts more object types for the ABI including Buffer (as seen in the error message).

**Comment by amolmaid** [comment]
**I am able to solve these both the problems** using following code snippet.
`eosScatter.setcode(account.name, 0, 0, Buffer.from(result.data.wasm.data), options2).then((res1, error1) => { ............ }`

**and**

`eosScatter.setabi(account.name, JSON.parse(Buffer.from(result.data.abi.data)), options2).then((res, error) => { ................ }`

**Note** : _Make sure you send your WHOLE response from back end in the form of string_

Thanks.
