### ISSUE TITLE
Unknown struct 'functionname' for contract 'eosio', locate this struct or provide serialized action.data action.data

### ISSUE THREAD

**Issue by dominic-healid** [EOSIO/eosjs#304]
I don't understand why I keep getting this kind of error. 

I have deployed the smart contract using the eosio account. Actually when printing the eosio instance I see the functionname that I'm trying to call.

```
eos.contract('eosio').then(eosio => { 
      console.log(eosio);
      return eosio.functionname({"creator": creator, "title": title, "documentPath": dataHash, "proposalType": proposalType, "description": description}, {authorization: 'eosio'});
   });
```

**Comment by jcalfee** [comment]
In the ABI your deploying you need to have `actions: [{name: 'functionname', type: 'some_type_from_structs'}]` and `structs: [{type: 'some_type_from_structs', ...}]`.

`some_type_from_structs` can be called `functionname` too.

**Comment by dominic-healid** [comment]
Do  you have a complete sample code/project for this that I can follow?

**Comment by dominic-healid** [comment]
I think I figured out what was the root. It looks like we cannot use the "eosio" account when accessing it through eosjs, it's just so weird because it works fine on node console. 

```
I deployed my smart contract using eosio account and it didn't work but after creating new account and deployed there the smart contract now works
```

**Comment by jcalfee** [comment]
The functions on the `eos` instance are cached and match EOSIO/eos .. You have to be sure your using `eos.contract(eos => eos.function` ..  If it is not that, there could be something going on in the cpp code and the eosio account.  It is safer to use another account.
