### ISSUE TITLE
how to set account permission by eosjs

### ISSUE THREAD

**Issue by yashvadhvani** [EOSIO/eosjs#305]
cleos set account permission <your-account> active '{"threshold": 1,"keys": [{"key": "<your-key>","weight": 1}],"accounts": [{"permission":{"actor":<contract-account>,"permission":"eosio.code"},"weight":1}]}' owner -p <your-account>
But how to do using eosjs

**Comment by jcalfee** [comment]
Can you get cleos to print the json?

**Comment by jcalfee** [comment]
Basically, pull the existing permission, change only what you need to change, then pass everything back to `updateauth` ..

https://github.com/jcalfee/eosjs-ecc-compression-tweak/blob/master/index.html#L162-L167

**Comment by blackwatertepes** [comment]
Is there a way to create a new permission for an account, without having to resubmit all existing permissions? I'm pretty sure cleos is doing this. I think this is the action we need to hit: https://github.com/EOSIO/eos/blob/master/libraries/chain/authorization_manager.cpp#L179

**Comment by thekevinbrown** [comment]
@c0d3ster, why did this issue get closed? How do we achieve this in eosjs?

**Comment by tbfleming** [comment]
eosjs legacy is no longer supported, so all issues for it were closed. Feel free to ask about v20 in a new issue.
