### ISSUE TITLE
get stats for tokens

### ISSUE THREAD

**Issue by MarcelBlockchain** [EOSIO/eosjs#307]
I found the following in the docs:
> eos.getCurrencyStats(code, symbol) ⇒ getCurrencyStatsResult

I was able to receive all stats for 

> eos.getCurrencyStats('EOS', 'eosio.token') 

as well as all self created tokens on my local test node. I was looking for symbols on the main net and found RIDL, POOR, WIZZ, EETH and ATD. Using their symbols just returned an empty object.
So either these tokens aren't really published yet or using 'eosio.token' is the wrong contract.

Was anybody successful getting stats for main net tokens?

**Comment by jafri** [comment]
Use contracts at https://github.com/eoscafe/eos-airdrops

**Comment by MarcelBlockchain** [comment]
worked! 
So all wallet providers need to have access to all contract names or even their own little database. Is there a package in development to get the most recent ones?
