### ISSUE TITLE
ABI error? - "Error: [     "Missing float32 "

### ISSUE THREAD

**Issue by Dylan-Phoon** [EOSIO/eosjs#309]
When I try to push this transaction:
```javascript
eos.transaction(
{
  actions: [
  {
  account: "mycontract",
  name: "makewithdraw",
  authorization: [{
    actor: "myaccount",
    permission: 'active'
  }],
  data: {
    withdraw_account: "myaccount" //Type: account_name
    target_token_contract: "gemtoken", //Type: string
    amount_of_token: "1.0000 GEM"  //Type: asset
}
  }
  ]
})
```

I get this error:
```
Error: [
    "Missing float32 in make_order.fields.price",
    "Missing float32 in order.fields.price"
]
    at M.exports (eos.min.js:1)
    at i (eos.min.js:1)
    at eos.min.js:1
```
Even though make_order is a type for the params that a function in my contract accepts (its in the ABI), I am not doing anything to do with make_order - the action that I am making is makewithdraw which uses the make_withdraw struct.

I dont get this error when I use cleos to push the action either. 

This is the eosjs version I am using: https://cdn.jsdelivr.net/npm/eosjs@16.0.3/lib/eos.min.js
And here is the part of the ABI in my contract that seems to be causing the error: https://github.com/Dylan-Phoon/eostrader-smart-contract/blob/master/exchange.abi#L21

**Comment by jcalfee** [comment]
Fixed in eosjs@16.0.5

**Comment by Dylan-Phoon** [comment]
@jcalfee Giving the same error but in a different place:
```
Error: [
    "Missing float32 in make_order.fields.price",
    "Missing float32 in order.fields.price"
]
    at e.exports (inject.js:34)
    at u (inject.js:57)
    at inject.js:57
```

**Comment by jcalfee** [comment]
I was able to re-create the issue consistently and see that it got fixed.
