### ISSUE TITLE
how to get ram market information via EOSJS?

### ISSUE THREAD

**Issue by pearsonbee** [EOSIO/eosjs#310]
we get rammarket informaction via cleos command line like this:
$ cleos -u https://api.eosnewyork.io get table eosio eosio rammarket
information returned:
 {                                                                                                     
  "rows": [{                                                                                          
      "supply": "10000000000.0000 RAMCORE",                                                           
      "base": {                                                                                       
        "balance": "28860504208 RAM",                                                                 
        "weight": "0.50000000000000000"                                                               
      },                                                                                              
      "quote": {                                                                                      
        "balance": "3199730.4381 EOS",                                                                
        "weight": "0.50000000000000000"                                                               
      }                                                                                               
    }                                                                                                 
  ],                                                                                                  
  "more": false                                                                                       
}

my problem is : how can I get current RAM market information via EOSJS? thanks a lot!

**Comment by pearsonbee** [comment]
@jcalfee I found it in file "src/schema/eosio.system.abi.json", and I learn how to use it.

**Comment by jcalfee** [comment]
When it comes to block chain read APIs and transactions eosjs .  Everything follows a pattern.

```js
eos.getTableRows() // for help
await eos.getTableRows(false, 'eosio', 'eosio', 'rammarket') // for real
```

**Comment by pearsonbee** [comment]
It help me so well
