### ISSUE TITLE
eosjs compile file

### ISSUE THREAD

**Issue by 414054375** [EOSIO/eosjs#320]
I wanna use "eosjs" to compile .cpp file to .wast file. Is there any other way to do this in web instead of using "eosiocpp" in server? 

How can I use "eosiocpp" lib ?

**Comment by Velua** [comment]
Don't know how myself but why do you wanna just eosjs to compile a .cpp file to .wast ?

**Comment by 414054375** [comment]
@Velua Don't you think deploy a contract in full node server is too complicated ? The compiler lib should seperate from eosio main framework

**Comment by tbfleming** [comment]
Very possible. I just haven't had time to bring it up to date: https://tbfleming.github.io/cib/eos-dawn4.html

Starts up much faster in FF than in Chrome. Other browsers not yet supported.

**Comment by 414054375** [comment]
our team has already developed a demo version of online IDE for EOSJungle Testnet. The url is "[studio.peacelove.io](url)". We use the scatter to provide identity and offline signature and call rpc api of BP nodes to deploy the contract. But it compiles in our nodes for now. If we can finish the online compile in JS it would be a perfect app. Do u have any open source projects or demos which has already made it? @jcalfee @tbfleming

**Comment by tbfleming** [comment]
@414054375 see my above link. It runs clang and binaryen in the browser to compile contracts.

**Comment by jcalfee** [comment]
pizza never gets old
