### ISSUE TITLE
getTableRows in Descending order

### ISSUE THREAD

**Issue by shwuhk** [EOSIO/eosjs#324]
Any way to get table rows in descending order by the key defined?

**Comment by jcalfee** [comment]
Maybe post in https://github.com/EOSIO/eos ?  They should know if the index can be used in reverse order.  I don't know the answer and I don't see a way in the current API.

**Comment by wushbin** [comment]
Hi there, 
I would like to know is there a way that we can get the last k(for example 10) rows in the table?

**Comment by Gammanik** [comment]
I'm not sure it's even possible in cleos. And the system itself I guess doesn't have this kind of option included.

**Comment by znebby** [comment]
Now that this is possible with EOS 1.5.0, it needs to be added to eosjs (along with get ram payer).

**Comment by jeffreyssmith2nd** [comment]
I'm not aware of anyone working on it at the moment, but Pull Requests are always welcome.

**Comment by channprj** [comment]
@jeffreyssmith2nd Please review my pull request. 😊🙏

...and what is difference between [eosjs](https://github.com/EOSIO/eosjs) and [eosjs-api](https://github.com/EOSIO/eosjs-api)?

**Comment by jeffreyssmith2nd** [comment]
`eosjs-api` was used by the original implementation of `eosjs` whereas the new eosjs (version 20) is a complete rewrite that no longer depends on `eosjs-api`.

Merged https://github.com/EOSIO/eosjs/pull/464, closing this issue

**Comment by znebby** [comment]
Awesome, thanks!

@jeffreyssmith2nd since myself and many others are still stuck on eosjs1, if an appropriate pull request of the same feature was made would it be possible to do an eosjs1 patch release?

**Comment by jeffreyssmith2nd** [comment]
Sorry for the delay, I've brought this up with the team and we'll follow up with this issue. 

As a more general note, is there something preventing you from upgrading to v20? We'd welcome issues/PRs for discussion around things that are blocking people from upgrading.

**Comment by znebby** [comment]
@jeffreyssmith2nd honestly the only thing stopping us from upgrading isn't even your fault.

Our app requires Scatter and the scatter chrome extension (which is depreciated) does not support eosjs2.

Unfortunately many thousands of users haven't upgraded to Desktop yet.

In a few months when extension users become negligible, we'll happily upgrade.

**Comment by josephjguerra** [comment]
Hi @znebby We don't plan to address this (or other PRs) on eosjs1. Only v20+ is under active development by our teams. I'd encourage you to work toward upgrading to v20+ and Scatter Desktop or other more secure wallets.

**Comment by avral** [comment]
How to use this now?
Last npm package have't this feature, and ```yarn add https://github.com/EOSIO/eosjs#master``` trows some error 
<img width="540" alt="screen shot 2019-03-02 at 14 04 47" src="https://user-images.githubusercontent.com/10092436/53678022-30355880-3cf4-11e9-98b1-e77e13412726.png">
seems not ready
