### ISSUE TITLE
how to confirm the result of eos.transfer?

### ISSUE THREAD

**Issue by pearsonbee** [EOSIO/eosjs#325]
Hello, @jcalfee , I call eosjs.transfer, and it tell me that the transaction had been broadcasted，
said "result.broadcast==true"，how can I confirm the result of transaction is Ok?  something like
onConfirmation(mined) on ethereum？
thanks！

**Comment by jcalfee** [comment]
I don't have anything automated yet.

This is what I have come up with so far:  It involves requiring for the full transaction using get_transaction with either the full transaction ID or a short version.

**Proposed** nodeos API changes.  Two things should be considered in the nodeos API that will help optimize:

* get_transaction_header (**proposed**) // just the header omitting: actions, context free actions, context free data
* time_until_irreversible  (**proposed**) // don't call get_transaction_header again until at least this much time as elapsed

You can save and re-query using the transaction ID .. But if implemented here I will probably try to use the short version as follows (in-case a user is dealing with a lot of transactions).  This is working in an external script I'm testing:
```js
const postTrx = eos.transfer(..)

const {transaction_id} = postTrx
const {ref_block_num} = postTrx.transaction.transaction
const shortId = transaction_id.substring(0, 8)
const blockNumHint = ref_block_num // A hit gets us close to the real block number

// Save shortId and blockNumHint in storage if required
```

3 seconds later
```js
await new Promise(resolve => setTimeout(() => resolve(), 3 * 1000))

/**
getTransaction parameters
  id: "transaction_id_type", // hex string of a uint32 passes, this may be much longer
  block_num_hint: uint32? // needed if a short 4 byte transaction id is used 
*/
const tr = await eos.getTransaction(shortId, blockNumHint)
const {last_irreversible_block, block_num} = tr

if(last_irreversible_block < block_num) {
   throw new Error('transaction is still reversible')
}
```

Update storage and UI with the new block number after it is irreversible (gets past `if(last_irreversible_block < block_num)`) ..
```js
const shortId = transaction_id.substring(0, 8)
const blockNum = block_num // not a hint anymore, we know the real block number
```

**Comment by jcalfee** [comment]
@heifner  just pointed out we need to figure out how to do this using the MongoDb plugin..

The code above may work for a while, but the history plugin is on schedule to be deprecated: https://github.com/EOSIO/eos/releases/tag/v1.2.0

**Comment by pearsonbee** [comment]
great! I learnt a lot from your reply, It seems that there are no penddings on EOS.
