### ISSUE TITLE
There is a way to use this library with react native?

### ISSUE THREAD

**Issue by lXSPandora** [EOSIO/eosjs#328]

**Comment by syncro2017** [comment]
Yes, this is what we are currently doing, seems to work great

**Comment by jcalfee** [comment]
related: https://github.com/EOSIO/eosjs/issues/286

**Comment by MarcelBlockchain** [comment]
check out react-native-eos from Eva, probably the best solution used in production.

https://github.com/EvaCoop/react-native-eos
