### ISSUE TITLE
EOSJS - any error for a transaction returns same error msg/exception

### ISSUE THREAD

**Issue by amolmaid** [EOSIO/eosjs#329]
I am using eosjs in my dAPP, where I am executing few transactions like **issue** and **transfer**. While doing so lets say I/user does something wrong while doing transfer
- May be he inserts wrong/invalid symbol name, 
- or quantity precision is in-correct
- or transfer quantity exceeds the total available balance
For any of the above action, eosjs returns me the same type of error message,
`{"code":500,"message":"Internal Service Error","error":{"code":3050003,"name":"eosio_assert_message_exception","what":"eosio_assert_message assertion failure","details":[]}}`

While at the same time, **nodeos** returns me the precise error message like,
![exception msg-04 19-54-48](https://user-images.githubusercontent.com/7837458/45037389-80509c80-b07c-11e8-947b-1fb4ff51484f.png)

SO do we have anything which will give me this kind more accurate error message like nodeos, so I can render it on page by which user could correct his mistake ?

**Comment by jcalfee** [comment]
I suspect it might be in here `"details":[]` if the API endpoint had started nodeosd with `--verbose-http-errors` .. I'm not sure what the trade-off is for enabling it and why it is off by default.  

There is some example code parsing details in another issue, we can find it if you need it.

**Comment by amolmaid** [comment]
Ohh great, Thank you for your response, this suffice my need here, I am able to get the precise error msg now.
   So thank you :)

**Comment by clockknock** [comment]
> I suspect it might be in here `"details":[]` if the API endpoint had started nodeosd with `--verbose-http-errors` .. I'm not sure what the trade-off is for enabling it and why it is off by default.
> 
> There is some example code parsing details in another issue, we can find it if you need it.

wow~ thank you again~
