### ISSUE TITLE
how to set up Private EOS Blockchain For Windows ?

### ISSUE THREAD

**Issue by patelankit** [EOSIO/eosjs#331]

**Comment by jcalfee** [comment]
Did you see https://github.com/EOSIO/eosjs/tree/master/docker ?

Windows has shells that make it more standard but I have not tested it so there may be tweaking you need to do..

**Comment by jcalfee** [comment]
The https://github.com/EOSIO/eosjs/tree/master/docker does something like that but it is for a simple minimal blockchain that will with eosjs..  Most likely you'll want this setup:  https://github.com/EOSIO/eosio-project-demux-example

Windows has shells that make it more standard but I have not tested that, mac and linux are more common.

**Comment by lanmower** [comment]
How did this issue remain open for 5 months?

**Comment by tbfleming** [comment]
We don't have staff assigned to close old issues on this repo like we do with the eos repo.
