### ISSUE TITLE
Import keys to wallet using eosjs

### ISSUE THREAD

**Issue by darkholiday** [EOSIO/eosjs#335]
Hello,
I am using eosjs to create accounts, it works fine but its doesn't import the keys to the wallet.
so my question is how to import the generated keys to the wallet using eosjs.

**Comment by jcalfee** [comment]
You'll need another library.  Generally this is done by updating the accounts auth to use a key that already exists in a wallet.  Many wallets use the BIP39 - Mnemonic Code (mnemonic phrase) to generate a key.  You can change the active and optionally the owner key on the account to match this new private key.  That way the user can just backup the mnemonic phrase.

This is not covered in eosjs.  Eosjs would however use a keyProvider and signProvider that accessed a wallet ..
