### ISSUE TITLE
I want to perform 2000 transactions but when i am looping trough the eosjs code it throws an error

### ISSUE THREAD

**Issue by yashvadhvani** [EOSIO/eosjs#336]
The error name is expired_tx_exception and the code for the same is 3040005 please tell me how can I perform these much transactions per seconds. 
I am able to perform 250 transactions per seconds but after that, it is throwing this error.

The code is as follows:

     for (let i = 0; i < 300; i++) {
        contract
                .transfer(
                  {
                    from: "myaccount",
                    to: "myaccount2",
                    quantity: "1.0000 SYS",
                    memo: i
                  },
                  {
                    authorization: ["myaccount@active"]
                  }
                )
                .then(res => {
                  console.log(res);
                  fs.appendFileSync("test.json", JSON.stringify(res));
                })
                .catch(err => {
                  console.log(err);
                });
        }

**Comment by jcalfee** [comment]
Have you tried batching multiple transfers into one transaction?

**Comment by yashvadhvani** [comment]
@jcalfee can you tell me how specifically I can do that it will be more than useful for me

**Comment by jcalfee** [comment]
The transaction may not expire it would be easier to process.  Of course first try to increasing the expiration time.

**Comment by yashvadhvani** [comment]
I tried that it worked but it is quite slow I want quick results I have batched transaction in one transaction but what if I want every transaction to go differently I want transaction id to be allocated in every transaction

**Comment by jcalfee** [comment]
The signature is probably slowing things down.  We would have to look at using a different ecc library in eosjs-ecc ..
