### ISSUE TITLE
provided_keys problem.

### ISSUE THREAD

**Issue by csquan** [EOSIO/eosjs#347]
hello,guys,
when I send a tx,I got log as below:
"transaction declares authority '{"actor":"fzcreator111","permission":"active"}', but does not have signatures for it under a provided delay of 0 ms, provided permissions [], and provided keys ["FZS8AqYq4iHM9T5Mgg8SX8CLn9ZLmsufJH5R1h1YUKJjNq54XH6Pq"]
    {"auth":{"actor":"fzcreator111","permission":"active"},"provided_delay":0,"provided_permissions":[],"provided_keys":["EOS8AqYq4iHM9T5Mgg8SX8CLn9ZLmsufJH5R1h1YUKJjNq54XH6Pq"],"delay_max_limit_ms":3888000000}",but I do not provide EOS8AqYq4iHM9T5Mgg8SX8CLn9ZLmsufJH5R1h1YUKJjNq54XH6Pq,how does it come?

**Comment by csquan** [comment]
is my fault,actually  log is ""transaction declares authority '{"actor":"fzcreator111","permission":"active"}', but does not have signatures for it under a provided delay of 0 ms, provided permissions [], and provided keys ["EOS8AqYq4iHM9T5Mgg8SX8CLn9ZLmsufJH5R1h1YUKJjNq54XH6Pq"]
{"auth":{"actor":"fzcreator111","permission":"active"},"provided_delay":0,"provided_permissions":[],"provided_keys":["EOS8AqYq4iHM9T5Mgg8SX8CLn9ZLmsufJH5R1h1YUKJjNq54XH6Pq"],"delay_max_limit_ms":3888000000}",so I do not know  how EOS8AqYq4iHM9T5Mgg8SX8CLn9ZLmsufJH5R1h1YUKJjNq54XH6Pq comes?

**Comment by csquan** [comment]
in what situation,eosjs provide a random pubkey?

**Comment by jcalfee** [comment]
If the signature is off (the signed transaction hash does not match the transaction hash nodeos calculates) then nodeos will recover a different public key and that will appear random.

I noticed your using delay_max_limit_ms .. https://github.com/EOSIO/eos/pull/5461  .. make sure your on the latest nodeos release/1.2.x .

**Comment by han-so1omon** [comment]
What are common reasons for this? My node is synced and using nodeos v1.7.2. This issue is happening to me when I use Liquidapps DSP.

**Comment by jcalfee** [comment]
Usually it is signing with the wrong key or wrong permission.

**Comment by jcalfee** [comment]
Above, I'm just explaining the wording behind the error.

**Comment by han-so1omon** [comment]
> If the signature is off (the signed transaction hash does not match the transaction hash nodeos calculates) then nodeos will recover a different public key and that will appear random.

To be clear, this usually occurs when the private key or permission is incorrect? In my case I think that the private key and permission is correct.

**Comment by han-so1omon** [comment]
This occurred for me because the chain id was wrong in the rpc call.
