### ISSUE TITLE
Can't create new account

### ISSUE THREAD

**Issue by AlwaysFurther** [EOSIO/eosjs#348]
Hello,
I am trying to create a new account with eosjs but I encounter a problem.
My code is the following

```
const Eos = require('eosjs');
const ecc = require('eosjs-ecc')

const config1 = {
  chainId: "cf057bbfb72640471fd910bcb67639c22df9f92470936cddc1ade0e2f2e7dc4f", // 32 byte (64 char) hex string
  keyProvider: ['5JHmqhxuSHFEESsPDHrwsv8BQrMXrjdoYinnGwocKF9jCKg1ugz'], // WIF string or array of keys..
  httpEndpoint: 'http://127.0.0.1:8888',
  expireInSeconds: 60,
  broadcast: true,
  verbose: false, // API activity
  sign: true
};

options = {
  authorization: 'eosio@active',
  broadcast: true,
    sign: true,
}
// connects to localhost
const eos = Eos(config1);

eos.transaction(tr => {
  tr.newaccount({
    creator: 'eosio',
    name: 'testfromjs',
    owner: 'EOS5tMLLzov5C3tpPTZu18xx4S1vDmsHtXqhmwXotj7EcxP7AUYP7',
    active: 'EOS5tMLLzov5C3tpPTZu18xx4S1vDmsHtXqhmwXotj7EcxP7AUYP7'
  },)
}, options)
```
When I run the script i get the following error:

`(node:7338) UnhandledPromiseRejectionWarning: {"code":500,"message":"Internal Service Error","error":{"code":3090003,"name":"unsatisfied_authorization","what":"Provided keys, permissions, and delays do not satisfy declared authorizations","details":[{"message":"transaction declares authority '{\"actor\":\"eosio\",\"permission\":\"active\"}', but does not have signatures for it under a provided delay of 0 ms, provided permissions [], and provided keys [\"EOS5tMLLzov5C3tpPTZu18xx4S1vDmsHtXqhmwXotj7EcxP7AUYP7\"]","file":"authorization_manager.cpp","line_number":411,"method":"check_authorization"}]}}
(node:7338) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7338) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

My wallet is open and unlock

Thank you for your help

**Comment by jcalfee** [comment]
Assuming there was not a chain ID miss-match error before your error, this means the eosio active key does not match the private key in keyProvider.  Convert the WIF to a public key and get it against the active key in `eos.getAccount('eosio')`.

**Comment by AlwaysFurther** [comment]
Hi @jcalfee 
Thanks for the answer. Really sorry I must be getting tired I was using the private key from another account and not the one of the eosio account as a key provider...

Now it works fine thanks

**Comment by ambrish-dev** [comment]
Hi,

From where i can get keyProvider id
