### ISSUE TITLE
Bug? action struct missmatch.

### ISSUE THREAD

**Issue by kasperfish** [EOSIO/eosjs#349]
When calling an action eosjs searches the abi for a matching struct. But it should search for a struc by action.type instead, not action .name. Most of the time the matching struct has the same name as the action so then its not a problem but when reusing structs in different actions it is a problem.
![image](https://user-images.githubusercontent.com/5130772/45712325-532be000-bb8c-11e8-808c-aadcd6c8aa0d.png)
So I'm calling "stprofileuns" action and eosjs complains that it can't find a struct with name "stprofileuns"...
![image](https://user-images.githubusercontent.com/5130772/45712375-735b9f00-bb8c-11e8-82d9-a0204d40a380.png)
As you can see in the abi, eosjs doesn't use the action.type for finding the correct struct.

**Comment by nsjames** [comment]
It seems this is happening inside of Scatter on this line: 

https://github.com/GetScatter/ScatterDesktop/blob/master/src/plugins/defaults/eos.js#L310

Which only calls does 
``` 
const data = abi.fromBuffer(action.name, action.data);
```

The `action.name` consoles out to `stprofileuns`
and the data in this instance is `00000000001aa36a0477686174`. It seems to not be able to convert it properly.

**Comment by kasperfish** [comment]
yes scatter related I'll close the issue...

**Comment by jcalfee** [comment]
> When calling an action eosjs searches the abi for a matching struct. But it should search for a struc by action.type instead, not action .name. Most of the time the matching struct has the same name as the action so then its not a problem but when reusing structs in different actions it is a problem.

Other way around.  The action name is like the exposed API action name and needs to a valid name (12 in length or shorter).  The type is the internal struct that tells it how to serialize.

Is abi.fromBuffer the eos.fc.fromBuffer?  @nsjames  You need to figure out the type behind the name for the fromBuffer function.

When calling the action it is

**Comment by nsjames** [comment]
It would be `(await eos.contract(contractAccount)).fc;`

I'm trying something like this now 
```
const typeName = abi.abi.actions.find(x => x.name === action.name).type;
const type = abi.structs[typeName];
const data = type.fromByteBuffer(action.data);
```

but getting 
![image](https://user-images.githubusercontent.com/10360675/45717169-c0963b80-bba1-11e8-9df4-b11ce525c2b4.png)

I'll have to keep messing around with it, but it's 100% on my side. I'm surprised this has never come up before.

**Comment by nsjames** [comment]
Nevermind, I'm being ridiculous. 

```
const typeName = abi.abi.actions.find(x => x.name === action.name).type;
const data = abi.fromBuffer(typeName, action.data);
```

Pushing a fix soon.
