### ISSUE TITLE
EDNA - Empty authorization when `sign: false`

### ISSUE THREAD

**Issue by aaroncox** [EOSIO/eosjs#350]
I'm at a loss as to why this is happening, but currently when you set `sign: false` on a transfer using the EDNA contract, the authorization comes back empty. With `sign: true`, it works fine. Below I've included two examples, one using IQ (contract: everipediaiq) and one using EDNA (contract: ednazztokens).

### IQ Transfer Code - Works

```
eos.transaction('everipediaiq', (contract) => {
  contract.transfer(
    'developjesta',
    'solveforanyx',
    '0.001 IQ',
    ''
  );
}, {
  broadcast: false,
  sign: false
}).then((tx) => {
  console.log(tx);
}).catch((err) => {
  console.log(err)
});
```
### IQ Transfer Results - Works

![image](https://user-images.githubusercontent.com/677686/45786734-d78b6b00-bc3f-11e8-9849-9bb2d1376b1a.png)

### EDNA Transfer - Doesn't work

```
eos.transaction('ednazztokens', (contract) => {
  contract.transfer(
    'developjesta',
    'solveforanyx',
    '0.0001 EDNA',
    ''
  );
}, {
  broadcast: false,
  sign: false
}).then((tx) => {
  console.log(tx);
}).catch((err) => {
  console.log(err)
});
```
### EDNA Transfer Results

![image](https://user-images.githubusercontent.com/677686/45786780-191c1600-bc40-11e8-80c8-3fb2279c9d5d.png)

As you can see in the screenshot above, the `authorization` property being returned ends up being an empty array. 

Any thoughts?

**Comment by aaroncox** [comment]
Also just for clarity, the eosjs instance (16.0.8) itself is just a simple configuration:

```
const Eos = require('eosjs');
const eos = Eos({
  httpEndpoint: 'https://eos.greymass.com'
});
```

I tried to find a good jsfiddle type environment so I could create a working code example, but couldn't find one that worked well with eosjs.

**Comment by jcalfee** [comment]
I think the ABI generator did not type the first field correctly.  Eosjs is expecting an `account_name` but it the ABI generator will often put in a `name` instead.  So, just add it manually after the arguments to to each action `contract.transfer('developjesta',    'solveforanyx',    '0.001 IQ',    '', {authorization: 'developjesta'})`.



This is very much a command-line version and does not save anything yet ..  I find it very helpful to work out examples and even use it as my own wallet.  I'll be happy to build this out more if your interested.  I'm incline to go modular and start loading verified code from the blockchain.  Be nice to have Ledger Nano support too.  https://jcalfee.github.io/eos.html  ..
