### ISSUE TITLE
missing authority of eosio

### ISSUE THREAD

**Issue by plazav** [EOSIO/eosjs#351]
Sometimes I am recieving exception "missing authority of eosio" or "code":3090004,"name":"missing_auth_exception"
For example in this case:

```
   await this.eos.transaction({
        actions: [
          {
            account: this.accountName,
            name: 'setpriv',
            authorization: [{ actor: this.accountName, permission: this.permission }],
            data: {
              account: this.accountName,
              is_priv: Number(this.isPriv)
            }
          }
        ]
      })
```

Have tried with active and owner permissions. With scatter and without. On Jungle and on TestNet.

**UPDATE**: replacing account: this.accountName with  account: 'eosio' doesn't help

**Comment by eugeniipol** [comment]
@plazav Hello, have you found the solution?

**Comment by avintoptaros** [comment]
@jcalfee This code has working before updating to version 16

**Comment by plazav** [comment]
@jcalfee This code has working before updating to version 16

**Comment by jcalfee** [comment]
can you just downgrade?  b1 is replacing eosjs with their version (see the README)..

**Comment by iamonuwa** [comment]
@jcalfee this error still persists.

**Comment by jcalfee** [comment]
I'm not working on this version anymore.  I'm not sure that this is a bug.  If it is though, maybe bosjs can help, looks like they are taking it over:

https://github.com/boscore/bosjs/releases/tag/v1.0.3

**Comment by iamonuwa** [comment]
Thank you, I'll check that out
