### ISSUE TITLE
Using eosjs to push action to node, sometimes it will stuck. Can I set timeout parameter?

### ISSUE THREAD

**Issue by littlekfc** [EOSIO/eosjs#352]
Something` like : `var res = await contract.click(****)`
Is there a way to set timeout parameter? The script is about to monitor the status and push action.

**Comment by jcalfee** [comment]
You can pass in fetchOptions (documented in the eosjs-api README) but it does not expose aborting requests.  It looks like aborting is not supported well on browsers:

https://github.com/github/fetch#aborting-requests
https://github.com/eosio/eosjs-api#optionsfetchconfiguration-example

If it is not critical that you know it aborted, you can set your own timeout around the API call.  What API call are you making?

**Comment by jcalfee** [comment]
does this work?
```js
const controller = new AbortController()
var res = await contract.click(****)
// some time later...
controller.abort()
```

**Comment by acoutts** [comment]
I just implemented this custom fetch timeout which seems to work quite well so far:

```typescript
import { JsonRpc, RpcError } from "eosjs"
import fetch from "node-fetch"

// Set timeout value here (450ms by default)
const customFetch = (url: any, options: any, timeout = 450) => {
  return Promise.race([
    fetch(url, options),
    new Promise((resolve, reject) => setTimeout(() => reject(new Error("timeout")), timeout)),
  ])
}

// EOSJS RPC
const rpc = new JsonRpc(env.nodeosEndpoint, { fetch: (customFetch as any) })

export function getAccountInfo(account: string) {
  return new Promise<any | null>((resolve, reject) => {
    log.info(`Fetching account info for: ${account}`)
    rpc.get_account(account).then((data: any) => {
      resolve(data)
    }).catch((e) => {
      if (e instanceof RpcError) {
        log.error(`[getAccountInfo] Error in response while getting account info for ${account}: ${JSON.stringify(e.json, null, 2)}`)
      }
      resolve(null)
    })
  })
}

// await getAccountInfo("useraccount1")
```

**Comment by pluswave** [comment]
An edge issue with this case:
1. when a transaction succeed in server side (mined in blockchain)
1. but fails to get notified to client because of  network issue,
1. so the client doesn't know the txid (can the client get it ? )
1. how can the client check that the transaction is already mined by BP ?
