### ISSUE TITLE
TypeError: This transaction requires a config.keyProvider for signing

### ISSUE THREAD

**Issue by arcynosure** [EOSIO/eosjs#355]
Whenever i try to create an account or a transaction this error is returned 

TypeError: This transaction requires a config.keyProvider for signing

My code is : 

const Eos = require('eosjs');

const eos = Eos();

wif = '5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3'
pubkey = 'EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV'
 
eos.transaction(tr => {
  tr.newaccount({
    creator: 'eosio',
    name: 'myaccount',
    owner: pubkey,
    active: pubkey
  })
 
  tr.buyrambytes({
    payer: 'eosio',
    receiver: 'myaccount',
    bytes: 8192
  })
 
  tr.delegatebw({
    from: 'eosio',
    receiver: 'myaccount',
    stake_net_quantity: '10.0000 SYS',
    stake_cpu_quantity: '10.0000 SYS',
    transfer: 0
  })
})

**Comment by china-yuanzhihao** [comment]
你都没有引用 wif   它指定少签名啊

**Comment by abdulmanan7** [comment]
instead of const eos = Eos(); 
do this
```
const config = {
      chainId: "chainid",
      keyProvider: "Private key",
      httpEndpoint:"http://jungle.cryptolions.io:18888",
      expireInSeconds: 600,
      broadcast: true,
      sign: true
    }
    const eos = Eos(config)
```
