### ISSUE TITLE
IOS support

### ISSUE THREAD

**Issue by cAstraea** [EOSIO/eosjs#37]
Hello. Anyone knows of any standing issues ? 
Seems it's not working on ios(mobile safari) but I have no way to debug what's going on. 
Was working on other browser
Update managed to connected the inspector on my iphone and got this 
ReferenceError: Can't find variable: Eos
![image](https://user-images.githubusercontent.com/13070662/37890370-1370955c-30d9-11e8-9245-3c25ac11ecf3.png)

**Comment by cAstraea** [comment]
Hello , I can't require it in browser.. i just included it with <script src="eos.js"></script> like in the examples here https://unpkg.com/eosjs@6.1.10/dist/
These also fail with the same error.

**Comment by chris-allnutt** [comment]
You still have to hose the eos.js file somewhere, even it it's on your web server and then point the script tag to that destination.

e.g

My server has the following structure
```
/page.html
/eos.js
```
I would include it as follows:
```
<script src="/eos.js"></script>
```

Did you put the whole directory on your server and set the web root to the dist folder?

**Comment by cAstraea** [comment]
Yes it's correct . It's working on desktop browsers only ios mobile throws this error.

**Comment by chris-allnutt** [comment]
Is there any way for you to see a http request for the file, similar to chrome developer tools?  That may help you find out where it's trying to request the file from.

**Comment by cAstraea** [comment]
<img width="1005" alt="screen shot 2018-03-26 at 17 31 39" src="https://user-images.githubusercontent.com/13070662/37912747-d64230a8-311b-11e8-9447-76d85f84d903.png">

Tried from local version also ... 	
	<script src="https://unpkg.com/eosjs@6.1.10/dist/eos.js"></script>

Could try to make a webpack/browserify version but not sure how to do that..

**Comment by jcalfee** [comment]
Try eosjs@6.1.11 ... I adjusted browserify to pack the lib directory (es2015) instead of the src directory (e6).

43213f2add0a34212aff84d6f2068fb123baa216

**Comment by jcalfee** [comment]
Great, I see you left me a heart above!  Ok, sounds like it works I'll close now.
