### ISSUE TITLE
Add browser instructions with CDN link.

### ISSUE THREAD

**Issue by bhazzard** [EOSIO/eosjs#376]

**Comment by chris-allnutt** [comment]
@bhazzard @dskvr we can use this commit hash which is off of the cdn branch we've created 

```<script src="https://cdn.jsdelivr.net/gh/eosio/eosjs@4ea39c037b8016b1f5197654b2c32e29192125c4/dist-web/eosjs-debug.js" integrity="sha384-0nvZuWr1W0MSN5pWlMpm25rItkptSPOA2c6HuvizniLkx5BLn7R9t0LGukX+SCqS" crossorigin="anonymous"></script>```

**Comment by bhazzard** [comment]
After discussing with several developers, there is a preference for building local packages with webpack. So I'm going to close this and wait for community feedback.
