### ISSUE TITLE
How to get public key if i know private key?

### ISSUE THREAD

**Issue by winter38** [EOSIO/eosjs#387]
Is there any way to get public key if i know only private key?

I want to get account info only from private key.
I know, that account name i can get from get_key_accounts, but it need public key.

**Comment by iKest** [comment]
for this you need to install eosjs-ecc pakage. eosjs has no public interface to this module

**Comment by winter38** [comment]
Thank you! just will include https://github.com/eosio/eosjs-ecc for now.
