### ISSUE TITLE
How to build web scripts

### ISSUE THREAD

**Issue by winter38** [EOSIO/eosjs#388]
Hello. I need scripts for web. I want to understand how i can get them.
Can anyone explain how can i build them with some details?  npm run build-web as said in documentation. What i need for that?

For now i took scripts from cdn from closed issue.
```
<script src="https://cdn.jsdelivr.net/gh/eosio/eosjs@4ea39c037b8016b1f5197654b2c32e29192125c4/dist-web/eosjs-debug.js" integrity="sha384-0nvZuWr1W0MSN5pWlMpm25rItkptSPOA2c6HuvizniLkx5BLn7R9t0LGukX+SCqS" crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/gh/eosio/eosjs@4ea39c037b8016b1f5197654b2c32e29192125c4/dist-web/eosjs-jsonrpc-debug.js" integrity="sha384-AkoBqsaf2yj+I0ly591fGwiCOSFzS072ucVxKyKD5xFnlc2mwOjESUTXa4qSEpS/" crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/gh/eosio/eosjs@4ea39c037b8016b1f5197654b2c32e29192125c4/dist-web/eosjs-jssig-debug.js" integrity="sha384-Jj9y5tybhn4VqzCIAXaiNoY1VXpduwh6xgAR4zuSZSSLUACfQG2QLJ+sbI+Youww" crossorigin="anonymous"></script>
```

**Comment by mauhcs** [comment]
I had the same problem. 
The following works for me:

    git clone https://github.com/EOSIO/eosjs.git 
    cd eosjs
    npm install
    npm run build-web 


Now you can import EOSJS script like this:

    <script src='eosjs/dist-web/eosjs-api-debug.js'></script>
    <script src='eosjs/dist-web/eosjs-jsonrpc-debug.js'></script>
    <script src='eosjs/dist-web/eosjs-rpcerror-debug.js'></script>
    <script src='eosjs/dist-web/eosjs-jssig-debug.js'></script>

**Comment by winter38** [comment]
Thank you for explanations!
