### ISSUE TITLE
Does the EOSjs library allow for the swapping of active/owner keys?

### ISSUE THREAD

**Issue by altShiftDev** [EOSIO/eosjs#392]
Is there an API to perform this action through the browser? All of my research points to cleos being the only way but if someone knows how I'd appreciate it, trying to build this into altshiftdev.com for use with the Ledger Nano S.

There's also an open ticket on the stackexchange regarding this question from August: https://eosio.stackexchange.com/questions/1805/is-it-possible-to-call-updateauth-to-change-account-keys-from-within-a-smart-c

**Comment by tbfleming** [comment]
`updateauth` is an action on the `eosio` account. Include it in a transaction.

**Comment by altShiftDev** [comment]
Hi @tbfleming do you have a link to a transaction structure for that `updateauth` call or any documentation?

**Comment by tbfleming** [comment]
Use `-j -d` in cleos to see the transaction structure.
