### ISSUE TITLE
npm run test -----error

### ISSUE THREAD

**Issue by Arielce** [EOSIO/eosjs#395]
**Version of EOSJS**

the newest

**Describe the bug**

> eosjs@20.0.0-beta1 test /Users/ce/eos/eosjs/eosjs
> jest

 RUNS  src/eosjs-jssig.test.ts
 RUNS  src/eosjs-api.test.ts
 RUNS  src/eosjs-jsonrpc.test.ts

Test Suites: 0 of 3 total
Tests:       0 total
Snapshots:   0 total
Time:        1s, estimated 6s
████████████████████████████████████████ts-jest[backports] (WARN) "[jest-config].globals.ts-jest.tsConfigFile" is deprecated, use "[jest-config].globals.ts-jest.tsConfig" instead.
ts-jest[backports] (WARN) Your Jest configuration is outdated. Use the CLI to he FAIL  src/eosjs-api.test.tsfig:migrate <config-file>.
  ● Test suite failed to run

    TypeScript diagnostics (customize using `[jest-config].globals.ts-jest.diagnostics` option):
    src/eosjs-api.test.ts:1:42 - error TS7016: Could not find a declaration file for module 'text-encoding'. '/Users/ce/eos/eosjs/eosjs/node_modules/text-encoding/index.js' implicitly has an 'any' type.
      Try `npm install @types/text-encoding` if it exists or add a new declaration (.d.ts) file containing `declare module 'text-encoding';`

    1 import { TextDecoder, TextEncoder } from "text-encoding";
                                               ~~~~~~~~~~~~~~~
    src/eosjs-api.test.ts:13:5 - error TS7018: Object literal's property 'context_free_actions' implicitly has an 'any[]' type.

    13     context_free_actions: [],
           ~~~~~~~~~~~~~~~~~~~~~~~~
    src/eosjs-api.test.ts:52:5 - error TS7018: Object literal's property 'transaction_extensions' implicitly has an 'any[]' type.

    52     transaction_extensions: [],
           ~~~~~~~~~~~~~~~~~~~~~~~~~~
    src/eosjs-api.test.ts:78:5 - error TS7018: Object literal's property 'context_free_actions' implicitly has an 'any[]' type.

    78     context_free_actions: [],
           ~~~~~~~~~~~~~~~~~~~~~~~~
    src/eosjs-api.test.ts:85:5 - error TS7018: Object literal's property 'transaction_extensions' implicitly has an 'any[]' type.

    85     transaction_extensions: [],
           ~~~~~~~~~~~~~~~~~~~~~~~~~~
    src/eosjs-api.test.ts:129:9 - error TS7034: Variable 'api' implicitly has type 'any' in some locations where its type cannot be determined.

    129     let api;
                ~~~
    src/eosjs-api.test.ts:154:16 - error TS7005: Variable 'api' implicitly has an 'any' type.

    154         expect(api).toBeTruthy();
                       ~~~
    src/eosjs-api.test.ts:158:32 - error TS7005: Variable 'api' implicitly has an 'any' type.

    158         const response = await api.getAbi("testeostoken");
                                       ~~~
    src/eosjs-api.test.ts:163:32 - error TS7005: Variable 'api' implicitly has an 'any' type.

    163         const response = await api.getTransactionAbis(transaction);
                                       ~~~
    src/eosjs-api.test.ts:168:32 - error TS7005: Variable 'api' implicitly has an 'any' type.

    168         const response = await api.getContract("testeostoken");
                                       ~~~
    src/eosjs-api.test.ts:179:20 - error TS7005: Variable 'api' implicitly has an 'any' type.

    179         const tx = api.deserializeTransaction(serializedTx);
                           ~~~
    src/eosjs-api.test.ts:184:32 - error TS7005: Variable 'api' implicitly has an 'any' type.

    184         const response = await api.serializeActions(transaction.actions);
                                       ~~~
    src/eosjs-api.test.ts:190:32 - error TS7005: Variable 'api' implicitly has an 'any' type.

    190         const response = await api.deserializeActions(serializedActions);
                                       ~~~
    src/eosjs-api.test.ts:196:26 - error TS7005: Variable 'api' implicitly has an 'any' type.

    196         const response = api.hasRequiredTaposFields(transaction);
                                 ~~~

 FAIL  src/eosjs-jsonrpc.test.ts
  ● Test suite failed to run

    TypeScript diagnostics (customize using `[jest-config].globals.ts-jest.diagnostics` option):
    src/eosjs-jsonrpc.test.ts:9:15 - error TS2339: Property 'resetMocks' does not exist on type '(input?: string | Request, init?: RequestInit) => Promise<Response>'.

    9         fetch.resetMocks();
                    ~~~~~~~~~~
    src/eosjs-jsonrpc.test.ts:19:15 - error TS2339: Property 'once' does not exist on type '(input?: string | Request, init?: RequestInit) => Promise<Response>'.

    19         fetch.once(JSON.stringify(expReturn), { status: 404 });
                     ~~~~
    src/eosjs-jsonrpc.test.ts:45:15 - error TS2339: Property 'once' does not exist on type '(input?: string | Request, init?: RequestInit) => Promise<Response>'.

    45         fetch.once(JSON.stringify(expReturn));
                     ~~~~
    src/eosjs-jsonrpc.test.ts:96:15 - error TS2339: Property 'once' does not exist on type '(input?: string | Request, init?: RequestInit) => Promise<Response>'.

    96         fetch.once(JSON.stringify(expReturn));
                     ~~~~
    src/eosjs-jsonrpc.test.ts:115:15 - error TS2339: Property 'once' does not exist on type '(input?: string | Request, init?: RequestInit) => Promise<Response>'.

    115         fetch.once(JSON.stringify(expReturn));
                      ~~~~
    src/eosjs-jsonrpc.test.ts:134:15 - error TS2339: Property 'once' does not exist on type '(input?: string | Request, init?: RequestInit) => Promise<Response>'.

    134         fetch.once(JSON.stringify(expReturn));
                      ~~~~
    src/eosjs-jsonrpc.test.ts:153:15 - error TS2339: Property 'once' does not exist on type '(input?: string | Request, init?: RequestInit) => Promise<Response>'.

    153         fetch.once(JSON.stringify(expReturn));
                      ~~~~
    src/eosjs-jsonrpc.test.ts:172:15 - error TS2339: Property 'once' does not exist on type '(input?: string | Request, init?: RequestInit) => Promise<Response>'.

    172         fetch.once(JSON.stringify(expReturn));
                      ~~~~
    src/eosjs-jsonrpc.test.ts:195:15 - error TS2339: Property 'once' does not exist on type '(input?: string | Request, init?: RequestInit) => Promise<Response>'.

    195         fetch.once(JSON.stringify(expReturn));
                      ~~~~
    src/eosjs-jsonrpc.test.ts:218:15 - error TS2339: Property 'once' does not exist on type '(input?: string | Request, init?: RequestInit) => Promise<Response>'.

    218         fetch.once(JSON.stringify(expReturn));
                      ~~~~
    src/eosjs-jsonrpc.test.ts:239:15 - error TS2339: Property 'once' does not exist on type '(input?: string | Request, init?: RequestInit) => Promise<Response>'.

    239         fetch.once(JSON.stringify(expReturn));
                      ~~~~
    src/eosjs-jsonrpc.test.ts:255:15 - error TS2339: Property 'once' does not exist on type '(input?: string | Request, init?: RequestInit) => Promise<Response>'.

    255         fetch.once(JSON.stringify(expReturn));
                      ~~~~
    src/eosjs-jsonrpc.test.ts:271:15 - error TS2339: Property 'once' does not exist on type '(input?: string | Request, init?: RequestInit) => Promise<Response>'.

    271         fetch.once(JSON.stringify(expReturn));
                      ~~~~
    src/eosjs-jsonrpc.test.ts:294:15 - error TS2339: Property 'once' does not exist on type '(input?: string | Request, init?: RequestInit) => Promise<Response>'.

    294         fetch.once(JSON.stringify(expReturn));
                      ~~~~
    src/eosjs-jsonrpc.test.ts:317:15 - error TS2339: Property 'once' does not exist on type '(input?: string | Request, init?: RequestInit) => Promise<Response>'.

    317         fetch.once(JSON.stringify(expReturn));
                      ~~~~
    src/eosjs-jsonrpc.test.ts:336:15 - error TS2339: Property 'once' does not exist on type '(input?: string | Request, init?: RequestInit) => Promise<Response>'.

    336         fetch.once(JSON.stringify(expReturn));
                      ~~~~
    src/eosjs-jsonrpc.test.ts:370:15 - error TS2339: Property 'once' does not exist on type '(input?: string | Request, init?: RequestInit) => Promise<Response>'.

    370         fetch.once(JSON.stringify(expReturn));
                      ~~~~
    src/eosjs-jsonrpc.test.ts:408:15 - error TS2339: Property 'once' does not exist on type '(input?: string | Request, init?: RequestInit) => Promise<Response>'.

    408         fetch.once(JSON.stringify(expReturn));
                      ~~~~
    src/eosjs-jsonrpc.test.ts:432:15 - error TS2339: Property 'once' does not exist on type '(input?: string | Request, init?: RequestInit) => Promise<Response>'.

    432         fetch.once(JSON.stringify(expReturn));
                      ~~~~
    src/eosjs-jsonrpc.test.ts:467:15 - error TS2339: Property 'once' does not exist on type '(input?: string | Request, init?: RequestInit) => Promise<Response>'.

    467         fetch.once(JSON.stringify(expReturn));
                      ~~~~
    src/eosjs-jsonrpc.test.ts:483:15 - error TS2339: Property 'once' does not exist on type '(input?: string | Request, init?: RequestInit) => Promise<Response>'.

    483         fetch.once(JSON.stringify(expReturn));
                      ~~~~
    src/eosjs-jsonrpc.test.ts:506:15 - error TS2339: Property 'once' does not exist on type '(input?: string | Request, init?: RequestInit) => Promise<Response>'.

    506         fetch.once(JSON.stringify(expReturn));
                      ~~~~
    src/eosjs-jsonrpc.test.ts:529:15 - error TS2339: Property 'once' does not exist on type '(input?: string | Request, init?: RequestInit) => Promise<Response>'.

    529         fetch.once(JSON.stringify(expReturn));
                      ~~~~
    src/eosjs-jsonrpc.test.ts:550:15 - error TS2339: Property 'once' does not exist on type '(input?: string | Request, init?: RequestInit) => Promise<Response>'.

    550         fetch.once(JSON.stringify(expReturn));
                      ~~~~
    src/eosjs-jsonrpc.test.ts:571:15 - error TS2339: Property 'once' does not exist on type '(input?: string | Request, init?: RequestInit) => Promise<Response>'.

    571         fetch.once(JSON.stringify(expReturn));
                      ~~~~
    src/eosjs-jsonrpc.test.ts:590:15 - error TS2339: Property 'once' does not exist on type '(input?: string | Request, init?: RequestInit) => Promise<Response>'.

    590         fetch.once(JSON.stringify(expReturn));
                      ~~~~
    src/eosjs-jsonrpc.test.ts:609:15 - error TS2339: Property 'once' does not exist on type '(input?: string | Request, init?: RequestInit) => Promise<Response>'.

    609         fetch.once(JSON.stringify(expReturn));
                      ~~~~

 RUNS  src/eosjs-jssig.test.ts

 PASS  src/eosjs-jssig.test.tstotal

Test Suites: 2 failed, 1 passed, 3 total
Tests:       2 passed, 2 total
Snapshots:   0 total
Time:        4.566s, estimated 6s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! eosjs@20.0.0-beta1 test: `jest`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the eosjs@20.0.0-beta1 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Version [e.g. 22]:
node:

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jeffreyssmith2nd** [comment]
I'm not seeing this on the latest master, make sure you're up to date with the latest code.

**Comment by blackwatertepes** [comment]
I just got the same issue, when running against master. The following command alleviated the first error...
`npm install @types/text-encoding`

However, all subsequent errors still remain.

**Comment by jeffreyssmith2nd** [comment]
Are you using `npm` or `yarn` to do the initial dependency install? You need to run `yarn install` or just `yarn` before you can run the tests

**Comment by blackwatertepes** [comment]
I was using `npm install`

**Comment by blackwatertepes** [comment]
`yarn && yarn test` seems to run okay. You should probably update the docs.
