### ISSUE TITLE
can't get the same publickey from api.signatureProvider.getAvailableKeys() as cleos

### ISSUE THREAD

**Issue by clockknock** [EOSIO/eosjs#404]
**Version of EOSJS**
^20.0.0-beta1

**Describe the bug**
when i using the `api.signatureProvider.getAvailableKeys()` with default private key `5KPRRKtJmKEcVifeLd8mGGdtKP855HDDQ97sWG1wM4EGCDpyB8m`,it retrurns `PUB_K1_8QPw89hqrzohK6gKTHG8bVCte3thbwceE7rFN25k8GdPhTY43L`,but when i use `cleos` wit h command `cleos wallet private_keys`,i can get :
```
[
    "EOS8QPw89hqrzohK6gKTHG8bVCte3thbwceE7rFN25k8GdPgsBJuu",
    "5KPRRKtJmKEcVifeLd8mGGdtKP855HDDQ97sWG1wM4EGCDpyB8m"
  ]
```
the last few chars from these two string are diffrent.
and i can get right account names from RPC with the cleos publickey, but the publickey from eosjs can not. have i do something wrong?

### public key from eosjs:
PUB_K1_8QPw89hqrzohK6gKTHG8bVCte3thbwceE7rFN25k8GdPhTY43L
<img width="338" alt="from_eosjs" src="https://user-images.githubusercontent.com/17850523/47251701-252b0b80-d46a-11e8-96c2-71ed7050e4ee.png">

### public key from cleos:
EOS8QPw89hqrzohK6gKTHG8bVCte3thbwceE7rFN25k8GdPgsBJuu
<img width="435" alt="from_cleos" src="https://user-images.githubusercontent.com/17850523/47251708-2d834680-d46a-11e8-93e1-aead5c2c220e.png">

### using the key from eosjs to get account names:
<img width="432" alt="js_publickey" src="https://user-images.githubusercontent.com/17850523/47251752-d467e280-d46a-11e8-929c-31052ec9e55c.png">

### using the key from cleos to get account names:
<img width="326" alt="cl_publickey" src="https://user-images.githubusercontent.com/17850523/47251753-d6ca3c80-d46a-11e8-808a-57ede5e93f56.png">

**Comment by tbfleming** [comment]
K1 Public keys have two different ascii representations of the same underlying binary data. The EOS prefix is the prefix for the legacy format. The /v1/ rpc api uses it for backwards compatibility. Future rpc apis won’t produce that format. The PUB_K1_ prefix is the prefix for the current format. The checksum bytes at the end are different. Both the /v1/ api and eosjs2 understand either format on input.

**Comment by clockknock** [comment]
> K1 Public keys have two different ascii representations of the same underlying binary data. The EOS prefix is the prefix for the legacy format. The /v1/ rpc api uses it for backwards compatibility. Future rpc apis won’t produce that format. The PUB_K1_ prefix is the prefix for the current format. The checksum bytes at the end are different. Both the /v1/ api and eosjs2 understand either format on input.

Wow!got it!perhaps the PUB_K1_prefix i used at first time has something wrong,i try it agian and it works, thanks a lot 😄 😄

**Comment by clockknock** [comment]
> K1 Public keys have two different ascii representations of the same underlying binary data. The EOS prefix is the prefix for the legacy format. The /v1/ rpc api uses it for backwards compatibility. Future rpc apis won’t produce that format. The PUB_K1_ prefix is the prefix for the current format. The checksum bytes at the end are different. Both the /v1/ api and eosjs2 understand either format on input.

Wow!got it!The PUB_K1_prefix i used at first time have something wrong perhaps.thank a log!
