### ISSUE TITLE
push/get transaction in beta version

### ISSUE THREAD

**Issue by djKooks** [EOSIO/eosjs#406]
**Version of EOSJS**
`eosjs@beta`

**Desktop (please complete the following information):**
 - OS: MacOS
 - EOSIO Version: 1.4

Hello,
I'm trying of push/get transaction(with hello world example) with eosjs. It seems eos.pushTransaction and eos.getTransaction API has been changed a lot, so couldn't find how to do this.

I make push transaction by
```
const result = await api.transact({
    actions: [{
      account: 'jung',
      name: 'hi',
      authorization: [{
        actor: 'jung',
        permission: 'active',
      }],
      data: {
        user: 'Bob'
      },
    }]
  }, {
    blocksBehind: 3,
    expireSeconds: 30,
  });
```
and it pushed but had some problem.

> Q1. In blockchain log, it returns '.ob', though I send 'Bob'. Do I have to convert user data before send?
 
And, now I'm trying to get this pushed transactions.

> Q2. Is there a guide to make get_transaction by user account or ID?

Also, in this push transaction, I received transaction_id value. But when I used [RPC API](https://developers.eos.io/eosio-nodeos/reference) `get_transaction` with put on this ID, it returns `cannot find`. 

> Q3. Is this ID different with transaction_id?

Thanks.

**Comment by tbfleming** [comment]
Q1: The name type only supports characters a-z (lowercase only), 1-5, and ".". It automatically replaces invalid characters, such as 'B', with '.'

Q2, Q3: `get_transaction` is part of the history plugin, which has to be enabled and configured. The history plugin is deprecated; apps shouldn't depend on it.
