### ISSUE TITLE
Unresolved module bug in react-native project

### ISSUE THREAD

**Issue by djKooks** [EOSIO/eosjs#408]
**Version of EOSJS**
`eosjs@beta`

**Describe the bug**
It seems it only happens in react-native project, for now.
When import the module and initiate, project shows error as:
```
error: bundling failed: Error: Unable to resolve module `assert` from `/path/to/project/node_modules/eosjs-ecc/lib/aes.js`: Module `assert` does not exist in the Haste module map
```
I'm not sure this is the problem of eosjs or issue in react-native. If somebody knows about this, please let me know.

**To Reproduce**
1. Apply eosjs module in react-native default project
2. import module
3. Run project

**Expected behavior**
Works well

**Smartphone (please complete the following information):**
 - Device: Android emulator

**Comment by yang24201** [comment]
I have the same issue, anyone can help?!

**Comment by yang24201** [comment]
@djKooks Have you solved the problem?

**Comment by jeffreyssmith2nd** [comment]
This is a known issue, eosjs-ecc does not support react-native.

**Comment by djKooks** [comment]
@yang24201 no...it seems known issue as in comment.
@jeffreyssmith2nd Is there a plan for fix?

**Comment by marcoLuo** [comment]
> maybe you can choose it in react native. https://github.com/Game-X-Coin/eosjs-rn

eosjs-rn also can not operate correctly

**Comment by shamtroon** [comment]
try this  https://github.com/mvayngrib/rn-nodeify.

**Comment by tbfleming** [comment]
The current develop branch dropped eosjs-ecc and uses the elliptic library instead.
