### ISSUE TITLE
Latest EOSJS (20.0.0-beta2): missing node_modules/eosjs/lib/index.js?

### ISSUE THREAD

**Issue by ChrysmOre** [EOSIO/eosjs#426]
Trying to import latest build of EOSJS but getting error:

    Error: ENOENT: no such file or directory, open '.../node_modules/eosjs/lib/index.js'

previous versions 'work' until I try to access the Rpc.JsonRpc module (gives "cannot read property 'JsonRpc' of undefined")

any ideas? I can see in the eosjs folder in node modules there isn't even a lib folder.

I'm running Debian 8.0 (Jessie)

**Comment by ChrysmOre** [comment]
``Error: ENOENT: no such file or directory, open '.../node_modules/eosjs/lib/index.js'
previous versions 'work' until I try to access the Rpc.JsonRpc module (gives "cannot read property 'JsonRpc' of undefined")

**Comment by c0d3ster** [comment]
The `Rpc` import no longer exists and has been changed to directly reference the JsonRpc class. 
 Please read the documentation and release notes before posting an issue in the future.  

The beta1->beta2 notes outline the change in import syntax to use `import { JsonRpc } from eosjs` then directly call `new JsonRpc`
