### ISSUE TITLE
eosjs pushing transaction: 'expecting string containing name'

### ISSUE THREAD

**Issue by ChrysmOre** [EOSIO/eosjs#429]
Trying to push a transaction with eosjs using transact():

    await api.transact({
      actions: [{
        account: contractName,
        name: action,
        authorization: [{
          actor: ContractNames.CONTRACT_NAME_CFRADMIN,
          permission: 'active',
        }],
        data: dataValue,
      }]
    }, {
      blocksBehind: 3,
      expireSeconds: 30,
    });

but getting back 'Error: Expected string containing name' in the console. I've traced this in the eosjs source code and found the error message in serialize.ts:

    public pushName(s: string) {
        if (typeof s !== "string") {
            throw new Error("Expected string containing name");
        } 

But what, where or why it's not receiving as a string is a mystery to me. I am thinking maybe something to do with the way it's got/processed the abi file is incorrect or something? Everything I've provided that should be a string is a string. I'm not sure how I should go about debugging this? Changes I make to the source file don't seem to take effect, the chrome inspector and react dev tools aren't any help.

**Comment by tbfleming** [comment]
It will be more clear what's happening if you log what you're passing to api.transact:

```
console.log(JSON.stringify({
  actions: [{
    account: contractName,
    name: action,
    authorization: [{
      actor: ContractNames.CONTRACT_NAME_CFRADMIN,
      permission: 'active',
    }],
    data: dataValue,
  }]
}, {
  blocksBehind: 3,
  expireSeconds: 30,
}, null, 4));
```

**Comment by DaLN** [comment]
@ChrysmOre I had the same error, have you ever found your problem ?

**Comment by lachlangreenbank** [comment]
@DaLN Did you manage to fix this? My transactions are working with the same format as others, for some reason just my 'issue' action is throwing this error.  Using the eosio.token contract.

```
async function issueToken() {
            try {
              let resp = await api.transact({ actions: [{
                    account: paramss.contract,
                    name: 'issue',
                    authorization: [{
                      actor: paramss.sender,
                      permission: 'active',
                    }],
                    data: {
                      to: paramss.receiver,
                      quantity: `${(paramss.amount).toPrecision(5)} ${paramss.symbol}`,
                      memo: '',
                    },
                  }]
                }, {
                  blocksBehind: 3,
                  expireSeconds: 30,
                });
              resp = {...resp, paramss}
              console.log(resp);
              res.send(resp)
            } catch(err) {
              console.log(err)
            }
          }
          issueToken()
```
