### ISSUE TITLE
wallet

### ISSUE THREAD

**Issue by Zhucola** [EOSIO/eosjs#434]
**Version of EOSJS**
_which version of eosjs exhibits the issue_

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by c0d3ster** [comment]
wallet... well then, I'm not sure what happened here but closing this out until issue is updated.
