### ISSUE TITLE
How to update account permissions using new API?

### ISSUE THREAD

**Issue by jsnathan** [EOSIO/eosjs#438]
In issues #334 and #305 it is explained how to update account permissions using the eos.updateauth method. I cannot seem to find this method in the new eosjs API. What is the new best practice on how to update account permissions?

**Comment by c0d3ster** [comment]
The old version of eosjs provided some wrappers around common functionality for convenience; however, this led to confusion as to how everything works behind the scenes.  In eosjs v20 you should be creating an instance of the `Api` then using `api.transact(transaction, config)` with the correct transaction format for an updateauth action.  The reference for the structure of the updateauth action (along with the struct for authority) can be found [here](https://developers.eos.io/eosio-nodeos/reference#get_abi) if you input eosio as the account_name

I'm closing this but let us know if you have any further issues with this and we'll address it appropriately.
