### ISSUE TITLE
Feature request: implement wrapper for nodeos' get_table_by_scope

### ISSUE THREAD

**Issue by infohata** [EOSIO/eosjs#440]
From version 1.4 EOS has a feature in both `cleos` and `nodeos` to get table indexed by scope. 
Please implement it into the next release of eosjs. In `cleos` it works this way:
* `cleos get scope {{account}} --t {{table}} -L {{lower_bound}} -U {{upper_bound}} -l {{limit}}`
Nodeos `get_table_by_scope` accepts the mustached parameters from the above via POST/PUT as always

Thank you

**Comment by LucienLau** [comment]
Yes, this feature is very helpful, and now I have to use `cleos` to do some thing.

**Comment by tbfleming** [comment]
Now supported by eosjs's `get_table_by_scope` function
