### ISSUE TITLE
using keosd in eosjs

### ISSUE THREAD

**Issue by summary71** [EOSIO/eosjs#441]
It seems that eosjs examples do not use keosd to retrieve the private keys or to sign a transaction.

`https://eosio.github.io/eosjs/`

It says "Using the default JsSignatureProvider in the browser is not secure and should only be used for development purposes. Use a secure vault outside of the context of the webpage to ensure security when signing transactions in production"

So what is the typical practice to implement "a secure vault" when we develop a web page to access eos chain?

Is it using keosd or a local DB or else?

**Comment by channprj** [comment]
[Browser Extension Storage](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage) is one of the options. It's a naive approach, but I think it is the best for now.

Browser Extension does not need the server for the frontend. You should consider making browser extension If you develop a dApp service.

Check examples below:
- [MetaMask](https://github.com/MetaMask/metamask-extension/blob/1f0cf11af1c94e750bbc4c5238c3ee028350a6c6/app/scripts/lib/local-store.js#L68-L81)
- [Scatter](https://github.com/GetScatter/ScatterWebExtension/blob/9d0f0946f8f53fe56c9a52afbeb55cc72c41f8e4/tests/helpers/chrome.js#L5-L8)
- [Addit Extension](https://github.com/addit-app/addit-extension/blob/master/src/utils/chromeApi.js#L228-L252)
- [MDN Web Docs](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage)

**Comment by tbfleming** [comment]
Related: #538

**Comment by Leask** [comment]
https://github.com/Leask/eosjs-keos/tree/main
