### ISSUE TITLE
Execute action from contract

### ISSUE THREAD

**Issue by DaLN** [EOSIO/eosjs#452]
Hi, i am trying to execute an action from a contract but i can not seem to find how to do that using the latest version of eosjs.

```javascript
const {Api, JsonRpc, RpcError, JsSignatureProvider} = require('eosjs');
const fetch = require('node-fetch');                            
const {TextDecoder, TextEncoder} = require('text-encoding'); 

const privateKey = "key";
const signatureProvider = new JsSignatureProvider([privateKey]);

const rpc = new JsonRpc('host:post', {fetch});
const api = new Api({rpc, signatureProvider, textDecoder: new TextDecoder(), textEncoder: new TextEncoder()});

api.getContract('contractName').then((contract) => {
            contract.actionName(JSON.stringify(parameterItem)).then(result => {
```
Result : Unhandled Rejection: TypeError: contract.actionName is not a function

seems like "actionName" is not a function. What is the proper way of executing an action from a contract deployed on a local blockchain ?

Thanks.

**Comment by DaLN** [comment]
https://github.com/EOSIO/eosjs/issues/61 seems to refer to old way of doing it.

**Comment by jeffreyssmith2nd** [comment]
It looks like you're using v20. There were significant breaking changes introduced and the linked issue does not apply to this version. See the README for how to use v20.

https://github.com/EOSIO/eosjs#sending-a-transaction

**Comment by DaLN** [comment]
Thank you.

**Comment by wujunchuan** [comment]
> It looks like you're using v20. There were significant breaking changes introduced and the linked issue does not apply to this version. See the README for how to use v20.
> 
> https://github.com/EOSIO/eosjs#sending-a-transaction

I have read the README section -  [how to send a transaction](https://github.com/EOSIO/eosjs#sending-a-transaction) with eosjs@20+. It just pushed the action(s) array and then broadcast it to the chain. But I want to keep this old-style like below demo code. How can I do with **eosjs@20+** @jeffreyssmith2nd 

**eosjs@16+**

```js
let contract = await state.eos.contract("eosio");
let res = await contract.transaction(tr => {
  // vote producer by proxy[join yxb]
  tr.voteproducer(
    account.name,
    state.voter
    [],
    auth
  );
  // first, deposit liquid-eos -> eos fund
  tr.deposit(account.name, assert, auth);
  // second, buyrex by eos fund
  tr.buyrex(account.name, assert, auth);
});
```
