### ISSUE TITLE
Including the eosjs in a typescript project breaks tsc build

### ISSUE THREAD

**Issue by mwawrusch** [EOSIO/eosjs#457]
**Version of EOSJS**
20.0.0-beta2 , maybe earlier. Doesn't show with the 16.x versions.

**Describe the bug**
We are including eosjs in a firestore backed node project. When adding 
```
  "eosjs": "20.0.0-beta2",
```
in package.json running tsc on the project directory returns with a code 2, which unfortunately breaks the firestore build process. 

**To Reproduce**
see above.

**Expected behavior**
Return an exit code of 0

**Screenshots**

none

**Desktop (please complete the following information):**
 - OS: Mac Os
 - Node: 8.2.1
 - tsc: 2.8.3, and 3.2.2

**Additional context**

**Comment by jeffreyssmith2nd** [comment]
Can you show the output from your build failure? There were significant API changes in version 20.

**Comment by mwawrusch** [comment]
tsc just returns a code 2. That's the only output I get. I'll look a bit more into this over the weekend and will provide some more feedback.

**Comment by tbfleming** [comment]
Not enough information to reproduce. Current instructions for including eosjs in projects lives in https://github.com/EOSIO/eosjs/blob/master/README.md
