### ISSUE TITLE
Changes to stay in sync with dawn3 (EOSIO/eos master)

### ISSUE THREAD

**Issue by jcalfee** [EOSIO/eosjs#46]

**Comment by jcalfee** [comment]
dependency, Docker is 4 days old:
https://hub.docker.com/r/eosio/eos/tags/

**Comment by jcalfee** [comment]
work-around

`echo 'EOSIO_IMAGE=eosio/eos:20180322' >> eosjs/docker/.env`

**Comment by jcalfee** [comment]
I'm still unable to get the latest docker hub image to produce blocks .. Not sure why.  In the mean time the test and anyone checking out the code from master will run version `eosio/eos:20180322`.

**Comment by chris-allnutt** [comment]
We're currently using eosio/eos:20180328 The startup command in the container has changed, that may be the issue if you're trying to run the container directly, but the current config included should work without modification.

**Comment by jcalfee** [comment]
I just got blocks going in `eosio/eos:20180405` but there is a vague `Unknown struct` error using the wallet command line to create an account.

I'll switch to `eosio/eos:20180328` and see how that goes..

**Comment by jcalfee** [comment]
Published: eosjs@7.1.5 eosjs@dawn3
