### ISSUE TITLE
Failed to process a transfer transaction with nodejs

### ISSUE THREAD

**Issue by henryyyx** [EOSIO/eosjs#47]
api error => http://127.0.0.1:8888/v1/chain/push_transaction {"compression":"none","data":{"expiration":"2018-04-06T22:46:23","region":0,"ref_block_num":3721,"r
ef_block_prefix":2640367696,"packed_bandwidth_words":11,"context_free_cpu_bandwidth":0,"context_free_actions":[],"actions":[{"account":"eosio","name":"transfer"
,"authorization":[{"actor":"tester","permission":"active"}],"data":"000000005c95b1ca00000000007015d6701101000000000004454f530000000000"}]},"signatures":["EOSK9x
B3Vp7fAp7NGNN1TiXaAVRtqTafMuFKTnWDvKHaUV8zqKXk53BjewByE7m8p7hBGSZTPvqc5MhSDRL5AyYDHvtCEdv9m"]} { Error: {"code":500,"message":"Internal Service Error","error":{
"code":3120010,"name":"packed_transaction_type_exception","what":"Invalid packed transaction","details":[{"message":"Missing transaction","file":"abi_serializer
.hpp","line_number":367,"method":"extract"},{"message":"Failed to deserialize variant","file":"abi_serializer.hpp","line_number":444,"method":"from_variant"},{"
message":"Invalid packed transaction","file":"chain_plugin.cpp","line_number":414,"method":"push_transaction"}]}}
    at /home/vagrant/test/node_modules/eosjs-api/lib/apigen.js:98:23
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) status: 500, statusText: 'Internal Server Error' }
{ Error: {"code":500,"message":"Internal Service Error","error":{"code":3120010,"name":"packed_transaction_type_exception","what":"Invalid packed transaction","
details":[{"message":"Missing transaction","file":"abi_serializer.hpp","line_number":367,"method":"extract"},{"message":"Failed to deserialize variant","file":"
abi_serializer.hpp","line_number":444,"method":"from_variant"},{"message":"Invalid packed transaction","file":"chain_plugin.cpp","line_number":414,"method":"pus
h_transaction"}]}}
    at /home/vagrant/test/node_modules/eosjs-api/lib/apigen.js:98:23
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) status: 500, statusText: 'Internal Server Error' }
[push_transaction error] '{"code":500,"message":"Internal Service Error","error":{"code":3120010,"name":"packed_transaction_type_exception","what":"Invalid pack
ed transaction","details":[{"message":"Missing transaction","file":"abi_serializer.hpp","line_number":367,"method":"extract"},{"message":"Failed to deserialize
variant","file":"abi_serializer.hpp","line_number":444,"method":"from_variant"},{"message":"Invalid packed transaction","file":"chain_plugin.cpp","line_number":
414,"method":"push_transaction"}]}}', transaction 'bff8c75a0000890e50d0609d0b00000000010000000000ea3055000000572d3ccdcd01000000005c95b1ca00000000a8ed32322100000
0005c95b1ca00000000007015d6701101000000000004454f530000000000'
{"code":500,"message":"Internal Service Error","error":{"code":3120010,"name":"packed_transaction_type_exception","what":"Invalid packed transaction","details":
[{"message":"Missing transaction","file":"abi_serializer.hpp","line_number":367,"method":"extract"},{"message":"Failed to deserialize variant","file":"abi_seria
lizer.hpp","line_number":444,"method":"from_variant"},{"message":"Invalid packed transaction","file":"chain_plugin.cpp","line_number":414,"method":"push_transac
tion"}]}}
(node:6626) UnhandledPromiseRejectionWarning: {"code":500,"message":"Internal Service Error","error":{"code":3120010,"name":"packed_transaction_type_exception",
"what":"Invalid packed transaction","details":[{"message":"Missing transaction","file":"abi_serializer.hpp","line_number":367,"method":"extract"},{"message":"Fa
iled to deserialize variant","file":"abi_serializer.hpp","line_number":444,"method":"from_variant"},{"message":"Invalid packed transaction","file":"chain_plugin
.cpp","line_number":414,"method":"push_transaction"}]}}
(node:6626) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6626) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.

**Comment by manhvvhtth** [comment]
I think I faced with the same error.

```
{
    "compression": "none",
    "data": {
        "expiration": "2018-04-07T08:28:56",
        "region": 0,
        "ref_block_num": 37941,
        "ref_block_prefix": 1183913515,
        "packed_bandwidth_words": 10,
        "context_free_cpu_bandwidth": 0,
        "context_free_actions": [],
        "actions": [
            {
                "account": "hello",
                "name": "sayhello",
                "authorization": [
                    {
                        "actor": "hello",
                        "permission": "active"
                    }
                ],
                "data": "00000000001aa36a0c5361792048656c6c6f20746f"
            }
        ]
    },
    "signatures": [
        "EOSK9LRpwmrASsasgddiRzedDErZbNGa9atGuF4EgeTLdD11eADEebPGnxFNS6XQQeV8vmeA6dygRwdPFMMSGMwo4yyAJjeBL"
    ]
}
{
    "Error": {
        "code": 500,
        "message": "Internal Service Error",
        "error": {
            "code": 3120010,
            "name": "packed_transaction_type_exception",
            "what": "Invalid packed transaction",
            "details": [
                {
                    "message": "Missing transaction",
                    "file": "abi_serializer.hpp",
                    "line_number": 367,
                    "method": "extract"
                },
                {
                    "message": "Failed to deserialize variant",
                    "file": "abi_serializer.hpp",
                    "line_number": 444,
                    "method": "from_variant"
                },
                {
                    "message": "Invalid packed transaction",
                    "file": "chain_plugin.cpp",
                    "line_number": 414,
                    "method": "push_transaction"
                }
            ]
        }
    }
}
```
Please help.

BTW: Could you please show me steps of signing a transaction.

Thank you,

**Comment by jcalfee** [comment]
Does it work with the eosio/eos:20180328 docker image?

**Comment by henryyyx** [comment]
The root cause is that the structure of packet was changed for the fix to https://github.com/EOSIO/eosjs/issues/25

        const packedTr = {
          compression: 'none',
          data: tr,
          signatures: sigs
        }

**Comment by manhvvhtth** [comment]
> Does it work with the eosio/eos:20180328 docker image?
Yes, it does.

:(, sorry, I get the error while running on pre-release of dawn3.
Could you make eosjs working with dawn3 - release soon. 👍

**Comment by tbfleming** [comment]
I have a pull request to support dawn-v3.0.0: https://github.com/EOSIO/eosjs/pull/49

**Comment by navcsdev** [comment]
@tbfleming I refer you and fix it same as > I have a pull request to support dawn-v3.0.0: #49. 

but I get the error 

```
Error: Required uint16 transaction_header.packed_bandwidth_words transaction.
    at validateInt (/Volumes/DATA/lecle/whose-wallet-be/express-babel/node_modules/eosjs/node_modules/fcbuffer/lib/types.js:765:11)
    at Object.fromObject (/Volumes/DATA/lecle/whose-wallet-be/express-babel/node_modules/eosjs/node_modules/fcbuffer/lib/types.js:497:7)
    at Object.fromObject (/Volumes/DATA/lecle/whose-wallet-be/express-babel/node_modules/eosjs/node_modules/fcbuffer/lib/struct.js:151:34)
    at Object.fromObject (/Volumes/DATA/lecle/whose-wallet-be/express-babel/node_modules/eosjs/node_modules/fcbuffer/lib/fcbuffer.js:261:19)
    at Object.fromObject (/Volumes/DATA/lecle/whose-wallet-be/express-babel/node_modules/eosjs/node_modules/fcbuffer/lib/struct.js:143:31)
    at /Volumes/DATA/lecle/whose-wallet-be/express-babel/node_modules/eosjs/lib/write-api.js:601:34
    at /Volumes/DATA/lecle/whose-wallet-be/express-babel/node_modules/eosjs/lib/write-api.js:780:7
    at /Volumes/DATA/lecle/whose-wallet-be/express-babel/node_modules/eosjs/node_modules/eosjs-api/lib/exported-helpers.js:70:7
    at /Volumes/DATA/lecle/whose-wallet-be/express-babel/node_modules/eosjs/node_modules/eosjs-api/lib/exported-helpers.js:80:7
    at callback (/Volumes/DATA/lecle/whose-wallet-be/express-babel/node_modules/eosjs/node_modules/eosjs-api/lib/process-args.js:70:9)
```

**Comment by qiushaoxi** [comment]
same problem

**Comment by zhangrm** [comment]
the same problem
`"eosjs": "^7.1.5"`

**Comment by navcsdev** [comment]
@zhangrm @qiushaoxi if you need it immediately you can use 
> I have a pull request to support dawn-v3.0.0: #49

I change the code in `node_modules` and it is success 😄

**Comment by zhangrm** [comment]
@navcsdev only change `packedTr.data` to `packedTr.transaction`?  but get other error 
`{
　　"code":401,
　　"message":"UnAuthorized",
　　"error":{
　　　　"code":3030002,
　　　　"name":"tx_missing_sigs",
　　　　"what":"signatures do not satisfy declared authorizations",
　　　　"details":[
　　　　　　{
　　　　　　　　"message":"transaction declares authority '{"actor":"eosio","permission":"active"}', but does not have signatures for it.",
　　　　　　　　"file":"chain_controller.cpp",
　　　　　　　　"line_number":1094,
　　　　　　　　"method":"check_authorization"
　　　　　　},
　　　　　　{
　　　　　　　　"message":"",
　　　　　　　　"file":"chain_controller.cpp",
　　　　　　　　"line_number":328,
　　　　　　　　"method":"_push_transaction"
　　　　　　},
　　　　　　{
　　　　　　　　"message":"",
　　　　　　　　"file":"chain_controller.cpp",
　　　　　　　　"line_number":284,
　　　　　　　　"method":"push_transaction"
　　　　　　}
　　　　]
　　}
}`

**Comment by davidfrothin** [comment]
Still have the same problem with 7.1.6 version

[push_transaction error] '{"code":500,"message":"Internal Service Error","error":{"code":3120010,"name":"packed_transaction_type_exception","what":"Invalid packed transaction","details":[{"message":"Missing transaction","file":"abi_serializer.hpp","line_number":367,"method":"extract"},{"message":"Failed to deserialize variant","file":"abi_serializer.hpp","line_number":444,"method":"from_variant"},{"message":"Invalid packed transaction","file":"chain_plugin.cpp","line_number":414,"method":"push_transaction"}]}}',

**Comment by eq1984** [comment]
@davidfrothin  have a look. your must change your local code.
https://github.com/EOSIO/eosjs/pull/49/files

**Comment by davidfrothin** [comment]
@eq1984 
so I went to my node_modules/eosjs/lib/write-api.js

Then made the change of commenting out those lines and replacing data with transaction. I still get the same error.

**Comment by eq1984** [comment]
@davidfrothin 
restart your nodeos, and add this parameter.
~ nodeos --skip-transaction-signatures
From time-to-time the eosjs and eosd binary format will change between releases so you may need to start eosd with the --skip-transaction-signatures parameter to get your transactions to pass.

**Comment by davidfrothin** [comment]
@eq1984 
Did you use npm install eosjs@7.1.6 to install eosjs?

**Comment by davidfrothin** [comment]
thanks, started with 
~ nodeos --skip-transaction-signatures
and restarted
I see the same error.

I installed eosjs with 
npm install eosjs@7.1.6

However, the code write-api.js starts with
'use strict';

var _slicedToArray = function () { function sliceIterator(arr, i) { var _arr = []; var _n = true; var _d = false; var _e = undefined; try { for (var _i = arr[Symbol.iterator](), _s; !(_n = (_s = _i.next()).done); _n = true) { _arr.push(_s.value); if (i && _arr.length === i) break; } } catch (err) { _d = true; _e = err; } finally { try { if (!_n && _i["return"]) _i["return"](); } finally { if (_d) throw _e; } } return _arr; } return function (arr, i) { if (Array.isArray(arr)) { return arr; } else if (Symbol.iterator in Object(arr)) { return sliceIterator(arr, i); } else { throw new TypeError("Invalid attempt to destructure non-iterable instance"); } }; }();

var _typeof = typeof Symbol === "function" && typeof Symbol.iterator === "symbol" ? function (obj) { return typeof obj; } : function (obj) { return obj && typeof Symbol === "function" && obj.constructor === Symbol && obj !== Symbol.prototype ? "symbol" : typeof obj; };

var assert = require('assert');
var ecc = require('eosjs-ecc');
var Fcbuffer = require('fcbuffer');

However 7.1.6 master and https://raw.githubusercontent.com/tbfleming/cib-eosjs/d73cfd240f21ee44192e71d54c4069dbcf08f836/src/write-api.js starts with

const assert = require('assert')
const ecc = require('eosjs-ecc')
const Fcbuffer = require('fcbuffer')
const createHash = require('create-hash')
const {processArgs} = require('eosjs-api')
const Structs = require('./structs')

module.exports = writeApiGen

**Comment by eq1984** [comment]
@davidfrothin 
yes. i install eosjs
npm install eosjs@dawn3

![image](https://user-images.githubusercontent.com/37569553/38729227-d5f4a59a-3f44-11e8-99d5-8bc9da30de70.png)

![image](https://user-images.githubusercontent.com/37569553/38729178-acce305a-3f44-11e8-81c4-8443dd0cc0f6.png)

**Comment by davidfrothin** [comment]
Thanks for helping to trouble shoot. Some reason our files downloaded are different

when I install 
npm install eosjs@dawn3
then I see node_modules/eosjs/lib/write-api.js starts with 
'use strict';

var _slicedToArray = function () { function sliceIterator(arr, i) { var _arr = []; var _n = true; var _d = false; var _e = undefined; try { for (var _i = arr[Symbol.iterator](), _s; !(_n = (_s = _i.next()).done); _n = true) { _arr.push(_s.value); if (i && _arr.length === i) break; } } catch (err) { _d = true; _e = err; } finally { try { if (!_n && _i["return"]) _i["return"](); } finally { if (_d) throw _e; } } return _arr; } return function (arr, i) { if (Array.isArray(arr)) { return arr; } else if (Symbol.iterator in Object(arr)) { return sliceIterator(arr, i); } else { throw new TypeError("Invalid attempt to destructure non-iterable instance"); } }; }();

var _typeof = typeof Symbol === "function" && typeof Symbol.iterator === "symbol" ? function (obj) { return typeof obj; } : function (obj) { return obj && typeof Symbol === "function" && obj.constructor === Symbol && obj !== Symbol.prototype ? "symbol" : typeof obj; };

var assert = require('assert');
var ecc = require('eosjs-ecc');
var Fcbuffer = require('fcbuffer');
var createHash = require('create-hash');

can you please paste the first few lines of /node_modules/eosjs/lib/write-api.js

**Comment by eq1984** [comment]
[write-api.zip](https://github.com/EOSIO/eosjs/files/1906908/write-api.zip)

**Comment by davidfrothin** [comment]
@eq1984 - thanks for your file. The issue is now resolved. The update worked.

Thanks for your help!

**Comment by davidfrothin** [comment]
Just an update that it was starting nodeos with
nodeos --skip-transaction-signatures
and above file that worked.

--skip-transaction-signatures what does it actually do? Will anyone be able to send transactions?

**Comment by jcalfee** [comment]
--skip-transaction-signatures lets all transactions pass without having a valid signature.. once you start skipping signatures.

**Comment by jcalfee** [comment]
moved to https://github.com/EOSIO/eosjs/issues/52

**Comment by Vyshakhcs1** [comment]
I had the same issue [push_transaction error]. And fixed it by adding modules
const assert = require('assert')
const ecc = require('eosjs-ecc')
const Fcbuffer = require('fcbuffer')
const createHash = require('create-hash')
const {processArgs} = require('eosjs-api')
const Structs = require('./structs')

Cheers (y)

**Comment by jcalfee** [comment]
@Vyshakhcs1 if your importing `eosjs` you don't need to manually import `fcbuffer` or any other `eosjs-*` package.  A pointer to the correct version of each package is under `Eos.Localnet().modules`.

**Comment by frankli1224** [comment]
Anyone can help? I also have this issue in dawn 4
{"code":3010011,"name":"packed_transaction_type_exception","what":"Invalid packed transaction","details":[]}

**Comment by tbfleming** [comment]
dawn 4 is obsolete; 1.0 came out over a month ago.
