### ISSUE TITLE
Can i just sign transcation without JSONRPC?

### ISSUE THREAD

**Issue by skanger** [EOSIO/eosjs#470]
I try to install a EOS  environment  on my CentOS, but it ask ”at least 8GB memory“, it's expensive for me.

I want to execute some transactions, but don't used third-party wallet,  just push my transaction result which is signed on some public api platform, like 'Eospark'.

So, I want to use this library to signed my transaction, but the example tell me that i need to connect a JSON-RPC server,  I have two questions for this

1. Is JSON-RPC server must need  nodeos installed?

2.  Can i just signed my transaction, without JSON-RPC? like in a  offline Chrome?

thanks for your answer.

**Comment by skanger** [comment]
I want get a result without JSON-RPC  like 


{
  "expiration": "2018-12-06T03:47:15",
  "ref_block_num": 64484,
  "ref_block_prefix": 2668208063,
  "max_net_usage_words": 0,
  "max_cpu_usage_ms": 0,
  "delay_sec": 0,
  "context_free_actions": [],
  "actions": [
    {
      "account": "eosio.token",
      "name": "transfer",
      "authorization": [
        {
          "actor": "supereospark",
          "permission": "active"
        }
      ],
      "data": "00afa998aaabaac6a0986aff4b9a3c61102700000000000004454f5300000000057465737431"
    }
  ],
  "transaction_extensions": [],
  "signatures": [
    "SIG_K1_JyxaXuABoAuzzaScAfw9evnQozYL17aBSUud4PEz4sRrRsPn2phwWuo9A1B14pRECoGcFKzF1dJHHvnM4YbUyKMaAt2agb"
  ],
  "context_free_data": []
}

**Comment by robertkowalski** [comment]
hi skanger!

this example uses two keys to sign, but it also uses offlien signing, which is probably what you need:

https://github.com/bitfinexcom/bfx-ext-eos-multisig/blob/master/example-multisig-raw.js
