### ISSUE TITLE
Cannot create account using keys with PUB_ key prefix. EOS prefix works

### ISSUE THREAD

**Issue by ashishchandr70** [EOSIO/eosjs#476]
Hi,

I am using eosjs 16.09 and I am unable to create a new EOS account using the PUB_ prefix for owner and/or active keys. It works from the `cleos create account` command line but not from javascript.

**This works:**

`const Eos = require('eosjs');`

```
let config = {
    chainId: null, // 32 byte (64 char) hex string
    keyProvider: ['5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3'], // WIF string or array of keys..
    httpEndpoint: 'http://127.0.0.1:8888',
    expireInSeconds: 60,
    broadcast: true,
    verbose: false, // API activity
    sign: true
};

let eos = Eos(config);

(async () => {
    try {


        let account = await eos.transaction(tr => {
            tr.newaccount({
                creator: 'eosio',
                name: 'userts3',
                owner: 'EOS6Msog3r7RNftBb1CKW2QvAraBGrduaVb6iS2iVyXwVMPr6TBFe',
                active: 'EOS6Msog3r7RNftBb1CKW2QvAraBGrduaVb6iS2iVyXwVMPr6TBFe'
            });
        });
        console.log(account);
    }
    catch (err) {
        console.log(err);
    }
})();`
```

**_But this does not:_**

```
const Eos = require('eosjs');

let config = {
    chainId: null, // 32 byte (64 char) hex string
    keyProvider: ['5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3'], // WIF string or array of keys..
    httpEndpoint: 'http://127.0.0.1:8888',
    expireInSeconds: 60,
    broadcast: true,
    verbose: false, // API activity
    sign: true,
    keyPrefix:['PUB']
};

let eos = Eos(config);

(async () => {
    try {


        let account = await eos.transaction(tr => {
            tr.newaccount({
                creator: 'eosio',
                name: 'userts3',
                owner: 'PUB_R1_6hdr2AzPziHwqtdChPQzosWEhCb7BLnjzdYAp83Kc5oD1orAy7',
                active: 'PUB_R1_6hdr2AzPziHwqtdChPQzosWEhCb7BLnjzdYAp83Kc5oD1orAy7'
            });
        });
        console.log(account);
    }
    catch (err) {
        console.log(err);
    }
})();
```

> TypeError: A name can be up to 12 characters long permission_level.actor = "PUB_R1_6hdr2AzPziHwqtdChPQzosWEhCb7BLnjzdYAp83Kc5oD1orAy7" permission_level_weight.permission = {"actor":"PUB_R1_6hdr2AzPziHwqtdChPQzosWEhCb7BLnjzdYAp83Kc5oD1orAy7","permission":"active"} authority.accounts = [{"permission":{"actor":"PUB_R1_6hdr2AzPziHwqtdChPQzosWEhCb7BLnjzdYAp83Kc5oD1orAy7","permission":"active"},"weight":1}] newaccount.owner = {"threshold":1,"keys":[],"accounts":[{"permission":{"actor":"PUB_R1_6hdr2AzPziHwqtdChPQzosWEhCb7BLnjzdYAp83Kc5oD1orAy7","permission":"active"},"weight":1}],"waits":[]} action.data = {"creator":"eosio","name":"userts3","owner":{"threshold":1,"keys":[],"accounts":[{"permission":{"actor":"PUB_R1_6hdr2AzPziHwqtdChPQzosWEhCb7BLnjzdYAp83Kc5oD1orAy7","permission":"active"},"weight":1}],"waits":[]},"active":{"threshold":1,"keys":[],"accounts":[{"permission":{"actor":"PUB_R1_6hdr2AzPziHwqtdChPQzosWEhCb7BLnjzdYAp83Kc5oD1orAy7","permission":"active"},"weight":1}],"waits":[]}} transaction.actions = [{"account":"eosio","name":"newaccount","authorization":[{"actor":"eosio","permission":"active"}],"data":{"creator":"eosio","name":"userts3","owner":{"threshold":1,"keys":[],"accounts":[{"permission":{"actor":"PUB_R1_6hdr2AzPziHwqtdChPQzosWEhCb7BLnjzdYAp83Kc5oD1orAy7","permission":"active"},"weight":1}],"waits":[]},"active":{"threshold":1,"keys":[],"accounts":[{"permission":{"actor":"PUB_R1_6hdr2AzPziHwqtdChPQzosWEhCb7BLnjzdYAp83Kc5oD1orAy7","permission":"active"},"weight":1}],"waits":[]}}}]

**Comment by UMU618** [comment]
You should use eosjs 20.x.
