### ISSUE TITLE
default exports cause issues with native environments

### ISSUE THREAD

**Issue by dskvr** [EOSIO/eosjs#480]
**Known issues with default exports**
- Inconsistent implementation/interoperability (between Browser, CommonJS and ESM environments) 
- TS discovery is poor
- Can cause issues in some IDEs, such as autocomplete.
- Can cause issues in some situations when refactoring

**Solution**
Remove default exports, use only named exports.

**Benefits**
- Improved compatibility with native environments
- Maintains ESM compatibility 
- Eliminates issues associated to default exports. 

**Resources**
- [Avoid Default Exports](https://basarat.gitbooks.io/typescript/docs/tips/defaultIsBad.html)
- ["Why we have banned default exports and you should do the same"](https://blog.neufund.org/why-we-have-banned-default-exports-and-you-should-do-the-same-d51fdc2cf2ad?gi=abe564714f32)

**Comment by c0d3ster** [comment]
I agree with this decision, but I want to get confirmation from all stakeholders and the public using beta3 before switching to named exports across the board.  We've already made the JsSignatureProvider named, then default; now we're proposing to move back to named export.  Let's ensure there's no downside (besides some extra brackets in import statements) across all supported environments before implementing this change.  Anyone who sees this issue and response, feel free to provide input.

**Comment by c0d3ster** [comment]
Change will be included in next release
