### ISSUE TITLE
How to use ecc. sign for local signature

### ISSUE THREAD

**Issue by LexLv** [EOSIO/eosjs#482]
![image](https://user-images.githubusercontent.com/15372383/51106334-6d1dbc80-1826-11e9-8c7c-9bc0e0803447.png)

I got the other parameters of the transaction in other ways.
Now I'm going to sign this transaction 
how to use ecc.sign( data, PrivateKey) ? data == transaction ?

**Comment by ajose01** [comment]
You should probably be using the `api.transact` method from `eosjs` vs going down into `eosjs-ecc`. The transaction still needs to be serialized, etc. before signing it.
Here's some examples: https://eosio.github.io/eosjs/guides/2.-Transaction-Examples.html#examples

If for some reason you really want to do this manually, then digging into the source will show you the steps taken before getting to `ecc.sign`:
https://github.com/EOSIO/eosjs/blob/master/src/eosjs-api.ts#L214

**Comment by tbfleming** [comment]
Answered by @ajose01
