### ISSUE TITLE
ecc takes way too much time

### ISSUE THREAD

**Issue by inkWave** [EOSIO/eosjs#483]
I'm new to eosjs , trying to developing a dapp demo , basically just receive a request, get value from request body then send value into eos by using transact demo from documentation . and on eos side, nothing complicated ,simply saved .but  I test that dapp by using webbench , it can only handle 5 request per second with cpu hits 100% . so I look into Flame Graphs , cpu basically consumed by several functions like recoverPubKey, calcPubKeyRecoveryParam , Signature.signHash , Signature.sign , which all in  eosjs-ecc module.
Am I doing something wrong ?
I'm using eosjs 20.0.0-beta2 . 
Really need help , any help will do .Many thx.

**Comment by anonymoustoken** [comment]
the  same problem

**Comment by tbfleming** [comment]
Yes. javascript-based signing algorithms are slow by nature.
