### ISSUE TITLE
getTableRows by secondary (i256) index - formatting for upper/lower_bound

### ISSUE THREAD

**Issue by dmorris99** [EOSIO/eosjs#485]
Hi there,

I'm trying (and failing) to retrieve a single row with eosjs.getTableRows, indexing by a secondary index on a field called email_hash, the index having cpp type of key256. The table definition looks like this:

```
struct [[eosio::table]] users_table {
        name owner;
        std::string email;
        checksum256 email_hash;
        time_point_sec created_at;   
        std::string assets_json;
        std::string data_json;

        uint64_t primary_key() const { return owner.value; }

        key256 by_email_hash() const { return get_email_hash(email_hash); } 
            static key256 get_email_hash(const checksum256& email_hash) {
                const uint64_t *p64 = reinterpret_cast<const uint64_t *>(&email_hash);
                return key256::make_from_word_sequence<uint64_t>(p64[0], p64[1], p64[2], p64[3]);
            }
    };
    typedef eosio::multi_index<"scpusers"_n, users_table,
        eosio::indexed_by<"idx1"_n, eosio::const_mem_fun<users_table, key256, &users_table::by_email_hash>>> users_index;
```

The email_hash field is emplaced with this value: `eosio::sha256(const_cast<char *>(email.c_str()), email.size());` and the index works in cpp, like this: 

```
        auto idx = table.get_index<name("idx1")>(); 
        calc_hash = eosio::sha256(const_cast<char *>(email.c_str()), email.size());
        auto secondary_key_itr = idx.find(users_table::get_email_hash(calc_hash));
        if (secondary_key_itr == idx.end()) { ...
```

The JSON output from an unfiltered query of the table contains values like this for the email_hash field:
` {
                "email_hash": "de58fcdff92ccaece5f73a66ae11784928981734cd214f12a1a8b8fadf722dcb",
                ...
},`

I.e. a hex-encoded 256 bit value, as expected. **The issue comes when trying to query by the secondary index, like this:** (no rows returned):

```
     var i256 = new BigNumber('de58fcdff92ccaece5f73a66ae11784928981734cd214f12a1a8b8fadf722dcb', 16)
        eos.getTableRows({
            ...
            key_type: 'i256',
            index_position: '2',
            lower_bound: i256.plus(-1).toFixed(),
            upper_bound: i256.plus(+1).toFixed(),
        }).then(result => {  ...  })
```

I've tried passing the raw hex string with a leading '0x' to no avail. If I pass straight decimal values '0' and '1000000000000000000000000000000000000000' or similar, I get all rows as expected. 

I guess this is some encoding issue on the parameters, but really am drawing a blank on what else to try.

Any help is much appreciated!

**Comment by dmorris99** [comment]
@tbfleming -- sorry, forgot to mention: this is using eosjs 16.0.9, latest npm package.

**Comment by tbfleming** [comment]
Related: https://github.com/EOSIO/eos/issues/6648

**Comment by wangyilin1987** [comment]
mark
