### ISSUE TITLE
How do I query a table rows by a date range?

### ISSUE THREAD

**Issue by yyyyaaa** [EOSIO/eosjs#488]
Let's say I have a table that has a column `date` of type `uint64_t date;` which saves milliseconds timestamp. Is it possible to query all records in that table in a specific date range? If so, how would I do that with eosjs?
Thank you.

**Comment by aa-paytomat** [comment]
I believe that without table index (that should be defined in smart contract table), you won't be able to do it without full table scan.

**Comment by tbfleming** [comment]
@aa-paytomat is correct
