### ISSUE TITLE
JsSignatureProvider is not a constructor node js issue

### ISSUE THREAD

**Issue by ambrish-dev** [EOSIO/eosjs#497]
I am using below code in node js but it is showing JsSignatureProvider is not a constructor .
I also want to know how to generate defaultPrivateKey in node js for EOS

       const { Api, JsonRpc, RpcError } = require('eosjs');
       const  { JsSignatureProvider } =  require('eosjs/dist/eosjs-jssig');  // development only
	const defaultPrivateKey = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" // useraaaaaaaa
	
	const privateKeys = [defaultPrivateKey];

	const signatureProvider = new JsSignatureProvider(privateKeys);
	const rpc = new JsonRpc('http://127.0.0.1:8888');
	const api = new Api({ rpc, signatureProvider });

Please provide solution . Thanks

**Comment by ambrish-dev** [comment]
I found solution 
const  JsSignatureProvider  =  require('eosjs/dist/eosjs-jssig').default;

**Comment by eluzgin** [comment]
The above code and solution doesn't work for latest eosjs. 
Here is the complete code that works:
>>>
const { Api, JsonRpc, RpcError } = require('eosjs');
const { JsSignatureProvider } = require('eosjs/dist/eosjs-jssig');  // development only
const fetch = require('node-fetch');                                    // node only; not needed in browsers
const { TextEncoder, TextDecoder } = require('util');

const defaultPrivateKey = "XXX";
const privateKeys = [defaultPrivateKey];
const signatureProvider = new JsSignatureProvider(privateKeys);

const rpc = new JsonRpc('http://api.eostribe.io/', { fetch });

const api = new Api({ rpc, signatureProvider, textDecoder: new TextDecoder(), textEncoder: new TextEncoder() });

(async () => {
  const result = await api.transact({
    actions: [{
      account: 'eosio.token',
      name: 'transfer',
      authorization: [{
        actor: 'sendraccount',
        permission: 'active',
      }],
      data: {
        from: 'sendraccount',
        to: 'receiveracct',
        quantity: '0.0001 EOS',
        memo: '',
      },
    }]
  }, {
    blocksBehind: 3,
    expireSeconds: 30,
  });
  console.dir(result);
})();

**Comment by neerajsinghs** [comment]
![Screenshot (23)](https://user-images.githubusercontent.com/104201600/173091108-00868c1f-522e-4198-ab2e-3a885872c5ee.png)

It's Generating error 
unknown block number
