### ISSUE TITLE
EOSJS Edge Missing Imports

### ISSUE THREAD

**Issue by jafri** [EOSIO/eosjs#499]
Running into issues when trying to use eosjs@edge

```
These relative modules were not found:

* ../src/abi.abi.json in ./node_modules/eosjs/dist/eosjs-api.js
* ../src/transaction.abi.json in ./node_modules/eosjs/dist/eosjs-api.js
```

**Comment by jafri** [comment]
Now on `eosjs@20.0.0-f6c2e54.0`

Getting the following error (does not appear on previous eosjs versions):
```
This dependency was not found:

* eosjs in ./src/plugins/eosjs/eosjs.js
```

**Comment by c0d3ster** [comment]
Edge should contain all necessary files now, let us know if you have any other issues
