### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined newaccount.deposit = undefined

### ISSUE THREAD

**Issue by davidfrothin** [EOSIO/eosjs#50]
Trying out below code and it shows the error
TypeError: Cannot read property 'split' of undefined newaccount.deposit = undefined

Running: 
npm install eosjs
Dawn 3 EOS
========== index.js
Eos = require('eosjs') // Eos = require('./src')

eosioprivate = '5JeeZ6atfR...'
eosiopublic = 'EOS5gx8uqfz...'

// Optional configuration..
config = {
  httpEndpoint: 'http://127.0.0.1:8888',
  keyProvider: eosioprivate,
}

eos = Eos.Localnet(config)

eos.newaccount({
  creator: 'eosio',
  name: 'testa',
  owner: eosiopublic,
  active: eosiopublic,
  recovery: 'eosio'
 deposit: 0
})

**Comment by zhangrm** [comment]
remove "deposit:0"

**Comment by davidfrothin** [comment]
Fixed with updating 
npm i eosjs@dawn3

However, have this new issue below
https://github.com/EOSIO/eosjs/issues/47

[push_transaction error] '{"code":500,"message":"Internal Service Error","error":{"code":3120010,"name":"packed_transaction_type_exception","what":"Invalid packed transaction","details":[{"message":"Missing transaction","file":"abi_serializer.hpp","line_number":367,"method":"extract"},{"message":"Failed to deserialize variant","file":"abi_serializer.hpp","line_number":444,"method":"from_variant"},{"message":"Invalid packed transaction","file":"chain_plugin.cpp","line_number":414,"method":"push_transaction"}]}}',

**Comment by jcalfee** [comment]
dawn3x changed the format of push_transaction .. so think your nodeos is not new enough.

You can use `./docker/up.sh` to start and setup the correct version.  In that script, you'll find a root private key.  You'll be fine with eosjs v8.0.0 ..

**Comment by jcalfee** [comment]
I have added a new README for the docker [folder](https://github.com/EOSIO/eosjs/tree/master/docker).
