### ISSUE TITLE
Expecting `/v1/chain/get_table_by_scope` support.

### ISSUE THREAD

**Issue by lanmower** [EOSIO/eosjs#503]
https://github.com/EOSIO/eos/pull/5486

Just adding this one feature to RPC will allow for querying available currencies, listing all users etc etc...

It has been available since September, perhaps its time that eosjs supports this?

**Comment by wuyahuang** [comment]
You can get table by scope by RPC API.

https://developers.eos.io/eosio-nodeos/reference#get_table_by_scope

**Comment by jeffreyssmith2nd** [comment]
PRs are always welcome! If someone would like to dive into this, all that would be needed is adding a function to `eosjs-jsonrpc.ts` that mirrors the above RPC call.

**Comment by wuyahuang** [comment]
@jeffreyssmith2nd

**Comment by jeffreyssmith2nd** [comment]
Handled by #514
