### ISSUE TITLE
import of JsSignatureProvider

### ISSUE THREAD

**Issue by mvolkmann** [EOSIO/eosjs#505]
The README says to do this:

```js
import { JsSignatureProvider } from 'eosjs/dist/eosjs-jssig';
```

but it needs to be this:

```js
import JsSignatureProvider from 'eosjs/dist/eosjs-jssig';

**Comment by c0d3ster** [comment]
This is dependent on your version, and the first option is in fact correct given the @edge release (which currently reflects the develop base branch and our next RC).  I assume you are working from beta3, in which case the second option is the correct import syntax.  Please follow the [issue template](https://github.com/EOSIO/eosjs/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md) in the future, so we don't have to make any assumptions when providing guidance.  Thanks!

**Comment by platoscave** [comment]
+1
I've been looking for days for this. Turns out my app needs the former syntax.

**Comment by c0d3ster** [comment]
You might want to consider upgrading to v20 as it is the most up to date version and all of the documentation references that version.
