### ISSUE TITLE
NPM instructions?

### ISSUE THREAD

**Issue by ekkis** [EOSIO/eosjs#509]
I've searched for eosjs on npm and get a tonne of matches, none of which look official.  the README makes no mention of NPM.  seriously.  can we have instructions for installing this through NPM please?

**Comment by tbfleming** [comment]
It's on the front page of the doc site, which is the first link on the GH page.

**Comment by c0d3ster** [comment]
We have removed the installation instructions on NPM in favor of Yarn for the 20.0.0 RC, but @tbfleming still makes a valid point as to the current location of NPM installation instructions.  [Here](https://www.npmjs.com/package/eosjs) is the direct link to the package on NPM... it is odd that it doesn't come up when you search `eosjs`, but if you let the autocomplete list populate below the search bar it will take you directly there.   

For future reference, Yarn simply pulls from the NPM registry so if the README states `yarn add eosjs` that is equivalent to `npm install eosjs`.  Please let us know if you have any further issues and try to maintain a positive attitude; we're only here to help out.

**Comment by ekkis** [comment]
sorry, not trying to be caustic and thank you for educating me as to the npm/yarn equivalence.  I don't understand why the NPM instructions would have been pulled from the homepage as that implies to the uneducated that it is necessary to install yarn (which I didn't want to have to do and the reason for my disagreeable tone). in any case, there's a large user base for NPM out there and having an extra couple of lines of instructions costs nothing and would save people like me the aggravation

and yes, I did also search for eosjs on npm but only to find 3 pages of modules none of which looked official.  I did find the package to which you have referred me, which also caused great distress as it's clearly been deprecated

the last thing I need is to struggle with code that fails because it's not official and outdated, so if it's not deprecated, can we mark it as such? and if it is, what am I to use in its place?

**Comment by ekkis** [comment]
> It's on the front page of the doc site, which is the first link on the GH page.

ah.  I didn't read the docs since installation instructions are right there on the README

**Comment by jeffreyssmith2nd** [comment]
> I did find the package to which you have referred me, which also caused great distress as it's clearly been deprecated

Unfortunately that's an oddity with npm. Only one very specific version (20.0.0-f6c2e54.0) of the package was marked as deprecated, the package itself is very much alive and active.

**Comment by ekkis** [comment]
it's something that should be fixed.  think of it from my perspective: I'm a brand new developer and the first thing I want to do is install eosjs: a) I can't find it on NPM, b) the README on github makes no mention of NPM, c) the one module that seems like it could be official has been deprecated

this is not promising.  could I be faulted for concluding that the software is immature and not well supported and thus shy away?

**Comment by c0d3ster** [comment]
@ekkis We have manually pushed a `20.0.0-ffffff.0`prerelease so the NPM website will no longer show the deprecated version as the most recent and you can install with `npm install eosjs@edge`.  

As for your second question, you could be faulted for concluding that considering your issue was addressed by 3 people in under 24 hours and considering the public commit history of the project.  This repository has been consistently maintained and updated, and the issue with searching/deprecation on the npm website had only come to light yesterday.  We'll consider adding something regarding NPM installations or our choice to favor Yarn over NPM.

**Comment by ekkis** [comment]
I'm greatly comforted with response time. it's clear this is active and I can rely on the community for support.  so thank you for that, and for addressing the issue with npm

**Comment by ekkis** [comment]
incidentally, "if the README states yarn add eosjs that is equivalent to npm install eosjs" isn't quite true because I just did the install and the code on the README wouldn't run.  I would get "Error: Cannot find module 'eosjs/dist/eosjs-jssig'" -- but installing with `eosjs@edge` worked ok so if the yarn command on the README works, it's pulling @edge and is not exactly equivalent.  unless the code on the README breaks for a yarn install as well
