### ISSUE TITLE
[Firefox]: blocked mixed content while requesting get_table_rows

### ISSUE THREAD

**Issue by bebop-studio** [EOSIO/eosjs#512]
**Version of EOSJS**
^20.0.0-beta3

**Describe the bug**
Firefox blocks mixed content while requesting for data using `get_table_rows`.

**Expected behavior**
Should not error.

**Screenshots**
<img width="1680" alt="screen shot 2019-03-02 at 2 55 26 pm" src="https://user-images.githubusercontent.com/46602391/53679155-6cb88280-3cfb-11e9-93e8-60aef8d1ffd9.png">

**Desktop (please complete the following information):**
 - OS: MacOSX
 - Browser: Firefox latest version

**Comment by tbfleming** [comment]
For security reasons, Firefox doesn't notify JS code of this failure. eosjs can't detect it.

**Comment by bebop-studio** [comment]
@tbfleming thanks for your comment. So what should I do about this problem? Do you have any workaround?

**Comment by tbfleming** [comment]
If you're serving your app using https (highly recommended), then your app should only allow https endpoints.
