### ISSUE TITLE
Access to fetch at 'https://api.eosnewyork.io//v1/chain/get_info' from origin 'ip:port' has been blocked by CORS policy

### ISSUE THREAD

**Issue by cancerts** [EOSIO/eosjs#515]
//eos
const  Eos = require('eosjs');
// Optional configuration..
var config = {
  keyProvider: ['PrivateKeys...'], // 配置私钥字符串
  httpEndpoint: 'https://api.eosnewyork.io/', //DEV开发链url与端口
  chainId: "0b08e71a2f8caaccc2dc13244b788f5eba29462ecd5d5dea1ad8cbe9581e885a", // 通过cleos get info可以获取chainId
  mockTransactions: () => null, // 如果要广播，需要设为null
  transactionHeaders: (expireInSeconds, callback) => {
    callback(null/*error*/, headers) //手动设置交易记录头，该方法中的callback回调函数每次交易都会被调用
  },
  expireInSeconds: 60,
  broadcast: true,
  debug: false,
  sign: true,
  authorization: null // 该参数用于在多签名情况下，识别签名帐号与权限,格式如：account@permission
}
 
var eos = Eos(config)
eos.getInfo({}).then(result => { 
	console.log(result) 
})

**Comment by cancerts** [comment]
:8080/#/Currency:1 Access to fetch at 'https://api.eosnewyork.io//v1/chain/get_info' from origin 'http://' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
always like this

**Comment by jeffreyssmith2nd** [comment]
> Access to fetch at 'https://api.eosnewyork.io//v1/chain/get_info' from origin 'http://' 

You can't access `http` sites when serving your site over `http`. So you need to serve your site over https. For testing, you can disable CORS in your browser using one of many extension on the Chrome/Firefox store.

**Comment by cancerts** [comment]
is solve 
============

used the endpoint 
==================

https://node1.zbeos.com
=================
nice
