### ISSUE TITLE
How to review a multisig proposal using eosjs?

### ISSUE THREAD

**Issue by SwJay** [EOSIO/eosjs#516]
There are 8 subcommands under "cleos multisig", but only 5 actions for eosio.msig where "review" is missing. Now I wonder how can I get the information of a multisig proposal via eosjs?

**Comment by yyh1102** [comment]
I have the same question~ When i get a multisig proposal via eosjs, it's in packed binary format. How can i unpack it?

**Comment by tbfleming** [comment]
Documentation for this is in progress in #588
