### ISSUE TITLE
Public Key reported in exceptions randomly changes on every exception. 

### ISSUE THREAD

**Issue by warrick-eosny** [EOSIO/eosjs#518]
**Version of EOSJS**
20.0.0-ac84c38.0

**Describe the bug**
The public key reported in exception messages is very confusing and changes on every exception. 
I have created a quick video to demonstrate the problem: https://www.youtube.com/watch?v=XxveYIKqKuQ

**To Reproduce**
Clone this repo https://github.com/warrick-eosny/randomkey 
1. npm install
2. npm start
3. Open browser, click the start button and view the console output.
4. Click test button agian. Observice the key reported in the error message.

**Expected behavior**
I would expect the public key reported to be consistent. 

**Screenshots**
See video: https://www.youtube.com/watch?v=XxveYIKqKuQ

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**
The video should provide all context needed.

**Comment by tbfleming** [comment]
Without spending time on the video, I have no idea what error message you're discussing above, or how to reproduce the error. Please include a summary here, including relevant code snippets.

**Comment by warrick-eosny** [comment]
This code snippet is what's being run: https://github.com/warrick-eosny/randomkey/blob/master/src/App.js#L15-L73
This is the signature provider being used: https://github.com/warrick-eosny/randomkey/blob/master/src/signer.ts#L4-L21  (Notice that the response is hard coded)

The error is expected, the fact that the error changes every time is not. 

The 1st time the error is returned: 

```
Error: transaction declares authority '{"actor":"ledgerledg2r","permission":"owner"}', but does not have signatures for it under a provided delay of 0 ms, provided permissions [], provided keys ["EOS84oAhNJvjLnQzAcURrBS7W9a3bdeHgJcdju3w8mnLY95yTx5ax"], and a delay max limit of 3888000000 ms
```

The 2nd time the error is returned: 
```
Error: transaction declares authority '{"actor":"ledgerledg2r","permission":"owner"}', but does not have signatures for it under a provided delay of 0 ms, provided permissions [], provided keys ["EOS5UwZNYm3HVCYwCDdFLjosi885QDCs1EzUQMiAb7rChoatHQ17a"], and a delay max limit of 3888000000 ms
```

Notice how the provided keys XXXX value keeps changing, even though the signature I am returning from the signature provider is hard coded. 

This is not the exact case that I'm debugging but the changing values have caused a lot a confusion.

**Comment by tbfleming** [comment]
This error is from nodeos. Here's what's happening:
* Every time you run it, the transaction and hash are different (the TAPOS fields change)
* Since the signature isn't from that hash, public key recovery produces the wrong key
* Since the hash keeps changing, the key recovery process keeps recovering a different public key

This is unavoidable because of the way ECC key recovery works.

**Comment by warrick-eosny** [comment]
Ah, that does help. Knowing that this can happens when when there is a signature signature doesn't match the hash may help me resolve my other problem. 

I was under the impression that one could reliably tell what key was used to create a signature, even without the hash. Is that not the case?

**Comment by tbfleming** [comment]
It's not the case. The algorithm for recovering the public key relies on both the signature and the hash.

**Comment by warrick-eosny** [comment]
Ok, thank you for the explanation. I'll close this case.

**Comment by n13** [comment]
@tbfleming I had the same problem and came across this issue - it explained a lot.

Mainly removed the mystery from the ever changing "provided" public keys which were not actually provided. I think this is a serious bug with error handling. The error message should make it clear that it's not necessarily the key that's wrong.

Caused a lot of head-scratching.

In my case I was using the wrong chain ID for my local dev install of nodeos / eosio! 

This caused a similar bug to the OP - all tx signing failed, but the error message had random and always changing public keys in it. 

Looked like nodeos was possessed by demons! 

Anyway I found and fixed this on my install, although still wondering how chain IDs come about, who decides on them, and why they're different on a EOS Studio / Docker install vs an eosio build from source install... how about having a nice clean "dev" chain ID...

**Comment by tbfleming** [comment]
The chain ID is produced by hashing the genesis block. That block includes chain creation options. It's intentionally different between chains to help prevent transactions from being applied to the wrong chain. You can force a new chain to match an old one by extracting the genesis block (json format) from the old one and using it to seed the new one using nodeos options.

An Api object instance automatically fetches the chain ID when it first needs it. Don't reuse a single Api object instance across different chains.
