### ISSUE TITLE
Why are issues closed that aren't fixed

### ISSUE THREAD

**Issue by projectoblio** [EOSIO/eosjs#520]
https://github.com/EOSIO/eosjs/issues/519

**Comment by projectoblio** [comment]
Please help

**Comment by c0d3ster** [comment]
Closing this too as it is not a real issue. We are actively addressing the problems you are having in #519

**Comment by projectoblio** [comment]
Thanks. also i am chill now. i would suggest this link from now on: https://www.npmjs.com/package/eosjs . 

It has different instructions from the other two documentation links you linked me to.  it also has more examples.

Good luck with yarn / es6 / babel etc. I know how crazy those can be to get working together

**Comment by c0d3ster** [comment]
@projectoblio I would not recommend that link, as those instructions are for eosjs v16.9 which will soon be deprecated. Those examples also do not translate to eosjs v20.0.0 as it is a complete rewrite of the library, hence the beta versioning.  All of the documentation will be synchronized once we officially upgrade to eosjs v20.0.0, so I would still advise following the instructions on the README of the develop branch in the meantime.  This will prevent you from having to change your code again in a week or two.
