### ISSUE TITLE
Singletons with Eosjs

### ISSUE THREAD

**Issue by thekevinbrown** [EOSIO/eosjs#523]
I have a singleton defined in my contract:

```
struct Settings
  {
    name owner;
    name nominatedOwner;
    name whitelister;
  };

  typedef eosio::singleton<"settings"_n, Settings> settings_table;
```

I saw #369, so I'm doing `getTableRows` like this:

```
getTableRows({
	code: '<name of contract when deployed>',
	scope: '<name of contract when deployed>',
	table: 'settings',
	json: true,
})
```

But that's yielding:
```
 Error: {"code":500,"message":"Internal Service Error","error":{"code":3060003,"name":"contract_table_query_exception","what":"Contract Table Query Exception","details":[{"message":"Table settings is not specified in the ABI","file":"chain_plugin.cpp","line_number":1154,"method":"get_table_type"}]}}
```

How do I use `getTableRows` to query `eosio::singleton` records?

**Comment by tbfleming** [comment]
Make sure your ABI is correct

**Comment by thekevinbrown** [comment]
@tbfleming, the ABI was not correct, due to https://github.com/EOSIO/eosio.cdt/issues/280

However I still don't get any rows back when I run `getTableRows`, just an empty set.

**Comment by thekevinbrown** [comment]
For anyone that finds this later, the constructor doesn't seem to get invoked until you actually call an action on the contract. I seem to have reliable data storage / querying via EOSJS now, so I'll close this and provide a more specific example if I have trouble in the future.

**Comment by ricktobacco** [comment]
no need to do upper/lower bound for singleton?
