### ISSUE TITLE
proxy string non-empty on voteproducer

### ISSUE THREAD

**Issue by slyon** [EOSIO/eosjs#533]
**Version of EOSJS**
eosjs v20.0.0 dist-web

**Describe the bug**
When sending a `voteproducer` transaction using eosjs v20 and the scatter-eosjs2-plugin, the empty proxy string (proxy: "") is translated into 13 dots.
```
const rpc = new eosjs_jsonrpc.JsonRpc('https://'+host)
const api = new eosjs_api.Api({ rpc, signatureProvider:scatter.eosHook(network, null, true) })
const transaction = {
        actions: [{
            account: 'eosio',
            name: 'voteproducer',
            authorization: [{ actor: account.name, permission: account.authority, }],
            data: { producers: ['eosdacserver'], proxy:'', voter: account.name }
        }]
    }
    return api.transact(transaction, { blocksBehind: 3, expireSeconds: 30 })
```

**To Reproduce**
1. Go to <https://eosdac.io/why-vote>
2. Scroll down to the the last section
3. Click on the "Vote using Scatter" button
4. Select an EOS/Scatter account which has already voted for any BPs (not proxy)
5. See error in Scatter transaction confirmation window

**Expected behavior**
The transaction should contain an empty string for the proxy parameter, not 13 dots.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/63956/55890404-effaad00-5bb2-11e9-9683-b1908a44cda3.png)

**Desktop (please complete the following information):**
 - OS: [Linux]
 - Browser [Chrome]
 - Version [73]

**Comment by tbfleming** [comment]
Did scatter-eosjs2-plugin update to the final released version of eosjs v20? If it's on an older version, then that could be the cause.

**Comment by slyon** [comment]
@tbfleming the problem was the same when I was still using eosjs v20.0.0-beta3, which was explicitly supported by `scatterjs-plugin-eosjs2`

**Comment by tbfleming** [comment]
I believe `scatterjs-plugin-eosjs2` uses eosjs internally. It may need to upgrade.

**Comment by piecesnbits** [comment]
I can confirm this was also present with eosjs@beta

**Comment by nsjames** [comment]
Hmm, we don't actually have `eosjs` internally there. It is always passed in by reference so that we never need to update our project when eosjs does. @tbfleming

**Comment by slyon** [comment]
@tbfleming @nsjames When using the same code within the EOS Lynx (iOS) wallet, using the `scatterjs-plugin-lynx` module, we get the following error, which might be related:
![image1](https://user-images.githubusercontent.com/63956/55900059-a3b96800-5bc6-11e9-94f5-560a27966139.png)

**Comment by slyon** [comment]
The related code can be found here: https://github.com/slyon/eosdacio-website/blob/lynx-support/_includes/scatter-vote.html#L59 (see the castVote() function)

**Comment by tbfleming** [comment]
It looks like lynx has a bug. "", ".", "..", "...", "............" are all valid representations of an empty name.

**Comment by slyon** [comment]
Not sure if it is a lynx problem, as I can see the **13 dots** in scatter desktop, too. Scatter desktop executes the transaction successfully, though.

@tbfleming is "............." also a valid representation of an empty name (i.e. 13 dots)?

**Comment by nsjames** [comment]
So for lynx there is actually an eosjs reference which might be causing that. I will update the plugin tonight with the latest version. Perhaps though, I'll do the same as the eosjs plugin and require a reference to eosjs instead which will allow bugs like this not to happen anymore and reduce the dependency on eosjs in the lunch plugin.

**Comment by tbfleming** [comment]
> @tbfleming is "............." also a valid representation of an empty name (i.e. 13 dots)?

yes

**Comment by slyon** [comment]
Today I was testing the voting flow with eosjs@edge (i.e. commit a2c7836), as suggested by @jafri in Telegram ("LynxApps" channel). But this does not change the problem. I can still see the 13 dots in Scatter!

Any other ideas, anybody?

**Comment by nsjames** [comment]
Scatter-js's Lynx plugin now requires injecting the eosjs reference. 
https://github.com/GetScatter/scatter-js/commit/1e424971eed8ba940acebff56a8aa889e206b6f2

```
// eosjs2
import {Api, JsonRpc} from 'eosjs';
ScatterJS.plugins( new ScatterLynx({Api, JsonRpc}) );

//eosjs1 
import Eos from 'eosjs';
ScatterJS.plugins( new ScatterLynx(Eos) );
```

For those with the issue in Lynx please try with that.

**Comment by slyon** [comment]
I am injecting eosjs20 into Scatter like this:
```
    ScatterJS.plugins( new ScatterEOS(), new ScatterLynx({ Api: eosjs_api.Api, JsonRpc: eosjs_jsonrpc.JsonRpc }) )
    ScatterJS.scatter.connect('eosDAC.io').then(function( connected ) {
        if(!connected) {
            console.error('Scatter could not be found.')
            return false
        }
```
But the `connected` variable always is `false` inside EOS Lynx (works fine via Scatter Desktop). What am I doing wrong here?

**Comment by nsjames** [comment]
Do you happen to be setting `window.ScatterJS` or `window.scatter` to null anywhere?

Pretty hard to debug this without logs, can you try adding https://github.com/Tencent/vConsole

**Comment by slyon** [comment]
yes, `window.ScatterJS` is set to `null` (https://github.com/eosdac/eosdacio-website/pull/59/files#diff-4b5c8f1f993539d8a49243ab9f6d7bbeR247), as recommended here: https://get-scatter.com/docs/setting-up-for-web-apps

We have vConsole in place, you can access it via the `?debug=true` parameter on the staging-server:
https://eosdac.slyon.de/why-vote/?debug=true

**Comment by nsjames** [comment]
Try removing the `window.ScatterJS = null` and see if that helps.

**Comment by slyon** [comment]
Thanks @nsjames ! Commenting `window.ScatterJS = null` helps to detect scatter inside EOS Lynx (Android), again! But shouldn't this be avoided, to hinder extensions from catching the Scatter reference, as described here: https://get-scatter.com/docs/setting-up-for-web-apps ?

I need to ask people if Proxy-vote & BP-vote are now working on EOS Lynx (iOS), too, using the staging-code at: https://eosdac.slyon.de/why-vote/?debug=true

**Comment by nsjames** [comment]
Yeah it should be avoided on browsers since there can be externals like other extensions, but it's possible we can manage all of that automatically in ScatterJS soon and remove that requirement for mobile wallets as they don't have externals (all webviews).

**Comment by slyon** [comment]
According to @lukestokes it now crashes the whole EOS Lynx iOS app, when signing the BP-vote transaction... While it works flawlessly on Android.

@ismyhc could you maybe have a look at this? It seems to be related to Lynx/iOS code now... You can test by clicking the "Vote using EOS Lynx" button at the bottom of this page: https://eosdac.slyon.de/why-vote/?debug=true

**Comment by piecesnbits** [comment]
> "............"



> It looks like lynx has a bug. "", ".", "..", "...", "............" are all valid representations of an empty name.

it seems that the eosio contract also recognise 12 dots as an empty accountname. I just tried to create a new account with 12 dots and it asserted with the message "accountname can't be empty"

**Comment by tbfleming** [comment]
"", "...." all mean empty. Accounts must have a non-empty name.

**Comment by tbfleming** [comment]
Doesn't appear to be an eosjs issue

**Comment by mixdev** [comment]
Just noticed that while voting on EOSX.io through Scatter, the dots do not appear.  Any idea how?
<img width="659" alt="Voting" src="https://user-images.githubusercontent.com/38874/65380555-5146b080-dcfb-11e9-8584-35c461ebf584.png">
