### ISSUE TITLE
Authorizations are not inferred when using contract()

### ISSUE THREAD

**Issue by nsjames** [EOSIO/eosjs#54]
It seems that with the latest dawn3 version ( `8.0.0` ) using `contract()` does not gather authorizations into the `actions` array.

For instance this:
```
eos.contract('anything').then(contract => {
    contract.hello(...paramWithRequiredAccount)
});
```
returns 
```
{"code":400,"message":"Bad Request",
"error":{"code":3030033,"name":"tx_no_auths",
"what":"transaction should have at least one required authority",........
```
because the actions array looks like:
```
[{
    account:"anything"
    authorization:[]
    data:"10e874ed4a9aa6b9f00000000..."
    name:"hello"
}]
```

However when explicitly specifying the accounts, this works:
```
eos.contract('anything').then(contract => {
    const options = { authorization: [ `someacc@active` ] };
    contract.hello(...paramWithRequiredAccount, options)
});
```

**Comment by nsjames** [comment]
The secondary ( non contract ) permissions will be hard to tell which need to be added since that requirement exists only within the action itself. Perhaps only the contract's account should be inferred to at least clear the 'should have at least one...' error.

**Comment by jcalfee** [comment]
Until I know of a better way I follow this: If the 1st field in the action's parameters is an name (type: name) that will be the default (account@active).  You are correct, you may have to specify options.

**Comment by nsjames** [comment]
Yeah it might be hard ( impossible even ) to infer which accounts need authorization without referring to the contract's require_auth statements at the moment. Perhaps a `required_keys` action route will be needed for the EOSIO RPC in the future to support implicit authorization gathering.
