### ISSUE TITLE
Caught exception: Error: fetching abi for myaccount: Unsupported abi version

### ISSUE THREAD

**Issue by xupengphp** [EOSIO/eosjs#542]
I deployed a contract, but when I call back the above error, is it because of my contract version, how do I need to update the contract?

**Comment by xupengphp** [comment]
contract

**Comment by tbfleming** [comment]
The easiest approach is to use eosio.cdt 1.6.1 to generate the ABI instead of writing it by hand and instead of using the old deprecated (and buggy) ABI generator.
