### ISSUE TITLE
add jsonToRawAbi function in eosjs-api, to complement rawAbiToJson

### ISSUE THREAD

**Issue by beac0n** [EOSIO/eosjs#543]
As a developer, I would like to be able to encode existing ABIs in JSON format as Uint8Array, 
so that I can use that Uint8Array as encoded ABI inside a transaction.

There already is a `rawAbiToJson(rawAbi: Uint8Array): Abi` function inside eosjs-api.ts.
It would be nice to also have a `jsonTorawAbi(jsonAbi: Abi): Uint8Array` function, which does the opposite.

PR: #544

**Comment by bradlhart** [comment]
Fixed by https://github.com/EOSIO/eosjs/pull/641

Currently available in the release candidate for v21.
