### ISSUE TITLE
call hello_world contract with version eosjs@20

### ISSUE THREAD

**Issue by jecombe** [EOSIO/eosjs#547]
hi !, I want call contract deploy hello world who takes one parameter with eosjs@20, i succeed create account, and send EOS token with eosjs@20. But i have some problems to call my contract deployed on testnet.

my old code:

let EOS = require('eosjs')

eos = EOS({
  chainId: "chainId",
  keyProvider: ['key'],
  httpEndpoint: 'http://jungle2.cryptolions.io:80'
})

eos.contract('name').then((hello) => {
  hello.hi("parameter", { authorization: ['name@active'] }).then((res) => {
    console.log(rep.console);
  })
})

now, i can't find any information about call contract deployed : https://eosio.github.io/eosjs/

**Comment by jeffreyssmith2nd** [comment]
You need to build a transaction and send it using the `api.transact` method. See the guides here https://eosio.github.io/eosjs/#sending-a-transaction and here https://eosio.github.io/eosjs/guides/2.-Transaction-Examples.html#examples

**Comment by jecombe** [comment]
const api = new Api({ rpc, signatureProvider, textDecoder: new TextDecoder(), textEncoder: new TextEncoder() });

  return api.transact({
    actions: [{
        account: "account_name",
        name: 'hi',
        authorization: [{ actor: "account_name", permission: 'active' }],
        data: {
            string: "test",
        },
    }]
}, {
        blocksBehind: 3,
        expireSeconds: 30,
    }).then(result => {
        console.log('at address: ', result.transaction_id);
        return 0;
    }).catch(e => {

        console.log('\nCaught exception: ' + e);
        if (e instanceof RpcError)
            console.log(JSON.stringify(e.json, null, 2));
    });
  }

ok it's good, this is my code, this code works with eosjs@20, thank's !
