### ISSUE TITLE
how do we get the Serialize.SerialBuffer in browser

### ISSUE THREAD

**Issue by dominic-healid** [EOSIO/eosjs#548]
I'm having issues with setabi, please help how to achieve this on browser. I am able to setcode but not with setabi.

**Comment by tbfleming** [comment]
Try something like this:

```
const buffer = new SerialBuffer({
  textEncoder: api.textEncoder,
  textDecoder: api.textDecoder,
});
api.abiTypes.get('abi_def').serialize(buffer, JSON.parse(abi));
const converted = buffer.asUint8Array();
```

**Comment by dominic-healid** [comment]
@tbfleming I need to reference the SerialBuffer, something like an import function. That's what I need to know because I can't use SerailBuffer without referencing, I'm getting undefined error.

**Comment by tbfleming** [comment]
It's in the Serialize module, which is exported from the top level.

**Comment by tbfleming** [comment]
Added to docs label: these probably need to go in the docs. Please keep open until then.

1. How to setabi
2. How to access the eosjs submodules

**Comment by dominic-healid** [comment]
@tbfleming can you please give me some pointers how to access the SerialBuffer? I'm still getting `SerialBuffer is not defined`

Really need some help with been struggling with this for a few days now.

**Comment by tbfleming** [comment]
What toolchain are you using to build your browser app? webpack? browserify? other? none? each method has a different approach to accessing the modules which make up eosjs.

**Comment by dominic-healid** [comment]
webpack, on the dist-web folder I only got, `eosjs-api, eosjs-jssig, eosjs-jsonrpc'

**Comment by tbfleming** [comment]
The dist-web folder isn't designed to work with webpack and restricts the set of available modules.

If you're using webpack with Babel, import modules using the instructions at https://eosio.github.io/eosjs/#es-modules

If you're using webpack without Babel, import modules using the instructions at https://eosio.github.io/eosjs/#commonjs

Either method allows you to import `Serialize`, which contains `SerialBuffer`

**Comment by sanaraufx** [comment]
Cleaning up old issues so we can focus on more recent issues. Please reopen this ticket if needed. Thank you.
