### ISSUE TITLE
Passing an endpoint to JsonRpc with trailing / results in Error: Unknown Endpoint

### ISSUE THREAD

**Issue by poplexity** [EOSIO/eosjs#558]
**Version of EOSJS**
20.0.0-beta3

**Describe the bug**
A trailing / on the endpoint url will cause eosjs to fail with error `Error: Unknown Endpoint`

**To Reproduce**
`npm install eosjs@beta node-fetch`
then run
```
const JsonRpc = require('eosjs').JsonRpc
const fetch = require('node-fetch')

const eos = new JsonRpc('http://testnet.telosusa.io/', { fetch })
eos.get_table_rows({json:true, scope: 'priveosrules', code: 'priveosrules',  table: 'nodes', limit:100}).then((data) => {
  console.log(data)
});
```
Then remove the trailing / on the endpoint and try again.

**Expected behavior**
The trailing / could be checked for and handled for the developer, or at least a more friendly error message

**Desktop (please complete the following information):**
 - OS: OSX 
 - Node: v10.15.1
 - Browser n/a
 - Version n/a

**Comment by c0d3ster** [comment]
This is a bug within nodeos but it is resolved by #562; will reopen if the PR doesn't fully solve the issue.
