### ISSUE TITLE
Issue with fs npm module

### ISSUE THREAD

**Issue by Vyshakhcs1** [EOSIO/eosjs#56]
The fs npm module is stopped their service. They are saying,
**This package name is not currently in use, but was formerly occupied by another package. To avoid malicious use**
So how to read **abi** and **wast** file from node ?

**contractDir = `${process.env.HOME}/eosio/eos/build/contracts/currency`
wast = fs.readFileSync(`${contractDir}/currency.wast`)
abi = fs.readFileSync(`${contractDir}/currency.abi`)**

Please help

**Comment by tbfleming** [comment]
The fs npm package was a joke. Node has a built-in package named fs that does not come from npm. Way too many package authors fell for it.

**Comment by jcalfee** [comment]
Correct, nodejs has a built in file system `fs` package.  If your using docker, you can run `./docker/up.sh` then get the correct version of these contracts as follows:
```
docker cp docker_nodeos_1:/contracts/currency/currency.wast .
docker cp docker_nodeos_1:/contracts/currency/currency.abi .
```

**Comment by chris-allnutt** [comment]
This isn't related to the eosjs lib since we don't use the fs module and are using the built in node fs. Closing this issue for now
