### ISSUE TITLE
Error: transaction declares authority but does not have signatures for it under a provided delay of 0 ms

### ISSUE THREAD

**Issue by thekevinbrown** [EOSIO/eosjs#560]
**Version of EOSJS**
v20.0.0

**Describe the bug**
Trying to sign a contract action on Jungle results in an error message instead of successful transaction, and I can't figure out why.

**To Reproduce**

```typescript
import { JsonRpc, Api } from 'eosjs';
import { JsSignatureProvider } from 'eosjs/dist/eosjs-jssig';
import fetch from 'node-fetch';
import { TextDecoder, TextEncoder } from 'util';

const signatureProvider = new JsSignatureProvider([process.env.EOS_PRIVATE_KEY]);
const rpc = new JsonRpc('https://jungle2.cryptolions.io:443', { fetch: fetch as any });
const eos = new Api({
	rpc,
	chainId: 'e70aaab8997e1dfce58fbfac80cbbb8fecec7b99cf982a9444273cbc64c41473',
	signatureProvider,
	// Same deal here, type mismatch when there really shouldn't be.
	textDecoder: new TextDecoder() as any,
	textEncoder: new TextEncoder() as any,
});

const go = async () => {
	console.log(
		await eos.transact(
			{
				actions: [
					{
						account: 'ginfhubtoken',
						name: 'issue',
						authorization: [
							{
								actor: 'coinagegizmo',
								permission: 'active',
							},
						],
						data: {
							to: 'l3qhfzzkt5xu',
							quantity: '1000000.00000000 GIHUSD',
							memo: 'USD Deposit',
						},
					},
				],
			},
			{ blocksBehind: 3, expireSeconds: 30 }
		)
	);
};

go()
	.then(() => console.log('Finished'))
	.catch(e => {
		throw e;
	});
```

Output:
```
(node:20762) UnhandledPromiseRejectionWarning: Error: transaction declares authority '{"actor":"coinagegizmo","permission":"active"}', but does not have signatures for it under a provided delay of 0 ms, provided permissions [{"actor":"ginfhubtoken","permission":"eosio.code"}], provided keys [], and a delay max limit of 3888000000 ms
    at new RpcError (/Users/kevin/development/global-infrastructure-hub/backend/node_modules/eosjs/dist/eosjs-rpcerror.js:26:28)
    at JsonRpc.<anonymous> (/Users/kevin/development/global-infrastructure-hub/backend/node_modules/eosjs/dist/eosjs-jsonrpc.js:118:35)
    at step (/Users/kevin/development/global-infrastructure-hub/backend/node_modules/eosjs/dist/eosjs-jsonrpc.js:36:23)
    at Object.next (/Users/kevin/development/global-infrastructure-hub/backend/node_modules/eosjs/dist/eosjs-jsonrpc.js:17:53)
    at fulfilled (/Users/kevin/development/global-infrastructure-hub/backend/node_modules/eosjs/dist/eosjs-jsonrpc.js:8:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Expected behavior**
I expected this transaction to succeed.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: OS X 10.14.5
 - Browser: N/A
 - Node: v10.15.3
 - Typescript: 3.3.3333

**Smartphone (please complete the following information):**
N/A

**Comment by thekevinbrown** [comment]
To confirm, there's definitely a private key in `process.env.EOS_PRIVATE_KEY` and it's valid. If I log out what the signature provider has before the transaction runs, it gives me the key back. If I run this:

```typescript
const availableKeys = await eos.signatureProvider.getAvailableKeys();
console.log('Available keys: ', availableKeys);

const requiredKeys = await eos.authorityProvider.getRequiredKeys({
	transaction,
	availableKeys,
});
console.log('Required keys: ', requiredKeys);
```
Then I get the same key twice. Why is it not signing with that key?

**Comment by thekevinbrown** [comment]
The issue was that it was in fact signing with the key, but that the error message is misleading. This error message in general means, "The transaction is trying to do something it's not authorised to do." and has nothing to do with the client signing the transaction or not.

In my case, this was because on Jungle they rolled out a new security requirement which was not very well documented which prevents issuing tokens to someone that isn't the issuer, as the smart contract sort of assumes the identity of the issuer to do the inline transfer.

So, a lot of words to say EOSJS wasn't at fault, but the error message led me to believe it was.

**Comment by shikhars371** [comment]
hello sir im also getting this error , what can be done?

**Comment by thekevinbrown** [comment]
@shikhars371, what are you doing to get the error?

**Comment by shikhars371** [comment]
sorted it out, thanks i was putting owners pk instead of active thanks anyways :)

**Comment by mstars** [comment]
I would like to ask a question, If I want to use active permission for an account to transfer what should I do.

**Comment by CiFrameVladislavB** [comment]
I have the same error with wax.greymass.com. I use the private key from wax.blocks.io, what do I wrong?
