### ISSUE TITLE
Transfer vs transferout

### ISSUE THREAD

**Issue by kiettran307** [EOSIO/eosjs#563]
what is difference between transfer and transferout in action name?
<img width="801" alt="Screen Shot 2019-07-04 at 3 58 02 PM" src="https://user-images.githubusercontent.com/22650079/60653703-c4672600-9e74-11e9-8d5c-b2b0a8c64a4a.png">
<img width="1115" alt="Screen Shot 2019-07-04 at 3 58 10 PM" src="https://user-images.githubusercontent.com/22650079/60653704-c4672600-9e74-11e9-8583-82e300aff903.png">

**Comment by tbfleming** [comment]
This is not an eosjs question. Ask the person who wrote that contract.
