### ISSUE TITLE
API does not use all signatures from JsSignatureProvider

### ISSUE THREAD

**Issue by han-so1omon** [EOSIO/eosjs#564]
I created a program to use 7 private keys. Then I added 4 new keys. The program still only uses the original 7 and seems to filter out the additional 4. What is going on?

```
//Helper File
const privateKeys = [
k1,k2,a1,k3,k4,a2,a3,k5,k6,k7,a4,
]
console.log(privateKeys.length);
// 11

const signatureProvider = new JsSignatureProvider(privateKeys);
// check that all keys are present... ok
const api = new Api({
rpc,
signatureProvider,
textDecoder: ...
textEncoder: ...
})
// check that all keys are present... only original 7 from previous program
let x = await api.signatureProvider.getAvailableKeys(); 
console.log(x.length);
// 7

// Test spec file
// Try to use authorization of one of the new keys
let res = await api.transact({
actions: [{
...
authorization: [{actor: a1, permission: "active"}],
...
}]},
{
blocksBehind: 3,
expireSeconds: 30
});
```

Even when I remove the original 7 keys they are still present in the api::signatureProvider.

Edit: I am only using one action. It requires one of the new accounts. Shown above.

**Comment by tbfleming** [comment]
eosjs only uses the keys necessary to fulfill the set of authorizations. If it included extras, then nodeos would reject the transaction.

**Comment by han-so1omon** [comment]
> eosjs only uses the keys necessary to fulfill the set of authorizations. If it included extras, then nodeos would reject the transaction.

see the edits. the only action requires one of the new accounts.

**Comment by tbfleming** [comment]
I think I might have misunderstood what you were asking. Are any of the keys duplicates?

**Comment by han-so1omon** [comment]
No, they are unique

**Comment by tbfleming** [comment]
Try inserting the following before https://github.com/EOSIO/eosjs/blob/849c03992e6ce3cb4b6a11bf18ab17b62136e5c9/src/eosjs-jssig.ts#L22

```
console.log('insert key', pub, k)
```

Look to see if any of the computed public keys are the same.

**Comment by han-so1omon** [comment]
I output the keys as such:
eosjs-jssig.js::JsSignatureProvider(privateKeys)::67 (file after ts compilation)

```
console.log(pub,k);
```

Only 7 pub-priv key pairs are printed out when the original JsSignatureProvider object is passed to the Api constructor. The original JsSignatureProvider prints 11 pub-priv keypairs.

**Comment by tbfleming** [comment]
I don't understand. Did it log 7 or 11?

**Comment by han-so1omon** [comment]
The signatureProvider object is created again as the Api object is being constructed, so it logs 11 outside of the Api object constructor and 7 inside of the Api object constructor

**Comment by tbfleming** [comment]
It should only be constructed once. Try setting a breakpoint on the constructor so you can find out where it's being constructed a second time.

**Comment by han-so1omon** [comment]
Ok it works now. I will explain the problem. Of course it was small and simple mistake. I have my eosjs stuff defined in a helper file. The api and rpc are exported as globals. I use this style because it is the default from EOSStudio test script template. I then include the helper in my test spec file as well as another utility file. When the helper is included in the test spec file, the api construction is fine.

However, in the utility file I include the eosjs helper file with the original set of private keys. This overwrites the global api and rpc variables. That was a silly mistake. Thank you for the help.
