### ISSUE TITLE
eosjs2 stable: JsSignature provider is not a constructor

### ISSUE THREAD

**Issue by ricktobacco** [EOSIO/eosjs#565]
**eosjs v.**
eosjs 20 stable release (not beta)

**Bug description**
Same ol' JsSignature provider is not a constructor
a la https://github.com/EOSIO/eosjs/issues/474
.default() fix tried to no avail

**Using all the commonJS syntax from current eosjs README and several of my own PKs**

**Desktop (please complete the following information):**
 - OS: Ubuntu 18
 - npm & node.js @ latest

**Comment by tbfleming** [comment]
Please provide sufficient information to reproduce.

**Comment by GreenBusDriver** [comment]
See discussion on #474 after the issue was closed (bottom of thread) for details and what's needed to reproduce.

**Comment by tbfleming** [comment]
No response from submitter

**Comment by HarshGuptaSolulab** [comment]
Facing same error

            finally { if (e_1) throw e_1.error; }
                               ^

Error: Invalid checksum, 9ac14c6b != 7882ed77

Version:
eosjs:20.0.0-beta3
ubuntu:16.04
