### ISSUE TITLE
Reference to eosjs from file created with browserify

### ISSUE THREAD

**Issue by alexej-work** [EOSIO/eosjs#567]
As far as I know eosjs could be found on this CDN: [jsdelivr](https://www.jsdelivr.com/package/npm/eosjs?path=dist)
But when I am trying to reference it in Tampermonkey (even if I am adding require to all .js files) I can't get my application working
Here is how I am trying to do it:

    // @require      https://cdn.jsdelivr.net/npm/eosjs@20.0.0/dist/index.min.js

**Comment by tbfleming** [comment]
We do not support jsdelivr or Tampermonkey. Please see https://github.com/EOSIO/eosjs/blob/master/README.md for the supported ways of including eosjs in projects.
