### ISSUE TITLE
Wrong error message: "unable to find key"

### ISSUE THREAD

**Issue by IhorPeresunko** [EOSIO/eosjs#570]
**Version of EOSJS**  ^20.0.0

**Describe the bug**
An unclear error message that doesn't help to find a problem.

**To Reproduce**
Try to call action *transfer* on 'eosio.token' account with tokens that don't exist on the blockchain.

`   api.transact({
        actions: [{
          account: 'eosio.token',
          name: 'transfer',
          authorization: [{
            actor,
            permission,
          }],
          data: {
            from: account1,
            to: account2,
            quantity: '10 EOA'
          },
        }]
      })`

 (in this example 'EOA' is random symbols).

**Expected behavior**
A clear and concise error description. Like: 'Token doesn't exist on the blockchain'.

**Actual behavior**
Error message: 'assertion failure with message: unable to find key'. Which is not helpful at all. 

Thank you.

**Comment by tbfleming** [comment]
That error message comes from the contract. eosjs can't do anything about it.

**Comment by tbfleming** [comment]
The token contract lives in this repo: https://github.com/EOSIO/eosio.contracts

Maybe create an issue there
