### ISSUE TITLE
Suggest replacing get_block()

### ISSUE THREAD

**Issue by UMU618** [EOSIO/eosjs#581]
get_block() is slow and may overload the server when the refBlock is a big one.

We just need:
- refBlock.timestamp
- refBlock.block_num
- refBlock.ref_block_prefix

https://github.com/EOSIO/eosjs/blob/849c03992e6ce3cb4b6a11bf18ab17b62136e5c9/src/eosjs-api.ts#L227

**Comment by c0d3ster** [comment]
Made some adjustments to the interfaces and the transactionHeader logic in the serializer, then merged it in.
Thanks for the contribution!
