### ISSUE TITLE
Use last irriversable block for transaction headers

### ISSUE THREAD

**Issue by jcalfee** [EOSIO/eosjs#599]
**Version of EOSJS**
v20

**Describe the feature**
In your options, you support: `blocksBehind`, consider adding `lastIrriversableBlock: true`

**Expected behavior**
This will lookup the block num and prefix from the last irreversible block (instead of blocks behind the head block) and use those values in the transaction TAPOS headers.

**Additional context**
The `blocksBehind` option is used to try and avoid casting transactions on short-lived forks (micro-forks).  This is only a guess though, a fork could be longer than 3 blocks (example from the README).  If you instead use the last irreversible block then you'll never try to create a transaction that is pointed to a fork.

**Comment by bradlhart** [comment]
This will be included in a future version of eosjs and is available on edge now.
