### ISSUE TITLE
Testnet is not accepting CORS browser requests

### ISSUE THREAD

**Issue by jcalfee** [EOSIO/eosjs#6]
The latest Eos.Testnet() points to a http://testnet1.eos.io which is not accepting CORS requests yet.  So it works in node but not in the browser.

In the mean time: http://t1readonly.eos.io is setup with CORS.  I'm told it will however silently fail if a large smart contract (setcode) is attempted.

**Comment by jcalfee** [comment]
fyi: the challenge is in the load balancer

**Comment by jcalfee** [comment]
possibly related: https://github.com/EOSIO/eos/pull/376

**Comment by jcalfee** [comment]
`Eos.Testnet({httpEndpoint: 'http://t1readonly.eos.io'})`

**Comment by jcalfee** [comment]
changed default to: http://t1readonly.eos.io

**Comment by cAstraea** [comment]
is there a https endpoint ?

**Comment by jcalfee** [comment]
I'm asking to see if we can get https setup..

**Comment by jcalfee** [comment]
Ok, https is enabled now, you please try:  https://t1readonly.eos.io/
