### ISSUE TITLE
`wasmHexString` used instead of `wasmFilePath` in 

### ISSUE THREAD

**Issue by dskvr** [EOSIO/eosjs#607]
**Version of EOSJS**
**20.0.0**

**Describe the bug**
`wasmHexString` is missing from "The entire code is provided below for reference."

**To Reproduce**
1. Go [here](https://eosio.github.io/eosjs/latest/how-to-guides/how-to-deploy-a-smart-contract#deploying-a-smart-contract)
2. Observe `wasmHexString`
3. Scroll down to "The entire code is provided below for reference."
4. Observe absense of `wasmHexString`

**Expected behavior**
`wasmHexString` instead of `wasmFilePath`

**Screenshots**
<img width="831" alt="Screen Shot 2019-11-16 at 1 13 30 PM" src="https://user-images.githubusercontent.com/299465/68992987-efc23e80-0872-11ea-8378-dbd2589e37dc.png">

**Comment by jeffreyssmith2nd** [comment]
Duplicates #608
