### ISSUE TITLE
How can I call a function that I have defined in the contract from my js ?

### ISSUE THREAD

**Issue by Vyshakhcs1** [EOSIO/eosjs#61]
My target is to make an app that can be html or native. For now let it be web app. I have deployed a hello world contract in my local blockchain network. I have defined a function named "hi". I need to call this function from my web app through js and I'm using **eosjs** in **browserify**. Can anyone guide me through this ? It would be great if anyone can give me a solution here.

**Comment by jcalfee** [comment]
```js
eos.contract('hello').then(hello => {
  hello.hi(..)
})
```

**Comment by PlanetGit** [comment]
> eos

Hi jclafee, Please explain the about eos. I'd like to have the details code. I am using the eosjs@20.0.0-beta3 but I can't find action function. How can i call the action function of eos smart contract in new eosjs version?

**Comment by jecombe** [comment]
eos.contract('hello').then(hello => {
hello.hi(..)
})

do you have this, with version eosjs@20

**Comment by wujunchuan** [comment]
> eos.contract('hello').then(hello => {
> hello.hi(..)
> })
> 
> do you have this, with version eosjs@20

There is only a function name called `getContract` in Api Object with version eosjs@20+.
I don't  understand how can you call the `eos.contract` function

**Comment by jcalfee** [comment]
That is not in 2.0 .. You need to create the json just like a transaction and pass it to `eos.transact`..  You need to figure out how to get your contract's ABI into the library.  @tbfleming do you have an example somewhere that does this?

**Comment by tbfleming** [comment]
It automatically fetches ABIs

**Comment by rahul1083** [comment]
> It automatically fetches ABIs

Can please give me example , how to call contract functions using eos.transact method?

**Comment by jcalfee** [comment]
Just a random search .. 

https://github.com/EOSIO/eosjs/blob/849c03992e6ce3cb4b6a11bf18ab17b62136e5c9/src/tests/web.html#L26

I see they did put an example in the [readme](https://github.com/EOSIO/eosjs#sending-a-transaction) too.

**Comment by rahul1083** [comment]
I am doing same thing see the example
await api.transact(
    {
      actions: [
        {
          account: 'addressbook',
          name: 'upsert',
          type: 'upsert',
          authorization: [
            {
              actor: 'me',
              permission: 'active'
            },
          ],
          data: {       
            key: 'me',
            first_name:'dasfasd',
            last_name: 'jhjkjk',
            street: 'jdkljd',
            city: "1",
            state: 'sdjs'
          },
        },
      ]
    },
    {
      blocksBehind: 3,
      expireSeconds: 30,
    }
  )

but I am getting error 

 Error: missing upsert.user (type=name)

**Comment by bradlhart** [comment]
Looks like you might need to change `key: 'me'` in your data to `user: 'me'`.  Depends on what you called the variable as an argument in your upsert function.
