### ISSUE TITLE
Invalid Packed Transaction

### ISSUE THREAD

**Issue by sbhm2** [EOSIO/eosjs#610]
I am trying to sign and publish a transaction manually. I used api.transact() with **broadcast:false, sign:true**. With this I got serializedTransaction(uint8array) and signatures(array). Then I fed these two in **rpc.push_trasaction()**. But I am getting the error "Invalid Packed transaction".

Again in another attempt I used **broadcast: false, sign:false** in api.transact(). Then I used **ecc.sign()** to sign the serializedTransaction and then I used **rpc.push_transaction()**. But still I am getting "Invalid Packed Transaction".

I hate to publish an issue here, but for signing and publishing I am using the same steps as it is used in api.transact() github page and I don't understand why am I getting this error.

**Comment by bradlhart** [comment]
I was able to send a transaction using `rpc.push_transaction()` that wasn't broadcasted with `api.transact()` successfully.  Could you share more information so I can recreate?
