### ISSUE TITLE
limit err about get_table_rows with Secondary index

### ISSUE THREAD

**Issue by hktomato** [EOSIO/eosjs#611]
I want to get the multi rows of the table with secondary key. I read [https://eosio.github.io/eosjs/latest/how-to-guides/how-to-get-table-information/#query-by-secondary-index](url) and it shows the method with `limit` option. But `limit` option didn't work.

```
const result = await rpc.get_table_rows({ 
            json: true,
            code: 'EOS_CONTRACT_NAME',    // contract who owns the table
            scope: 'EOS_CONTRACT_NAME',   // scope of the table
            table: 'sensors',    // Pi Multi index table name
            table_key: 'id',  // Table secondary key name
            lower_bound: id, // Table secondary key value
            limit: 2,
        });
...
(async ()=>{
        console.log(await ApiService.getSensorDataById('test'));
    })();
```
I wrote the code like this. But It shows me just **1 row**.
Of course The table has 2 rows.
When I try `cleos --url http://127.0.0.1:8888 get table raspberrypi raspberrypi sensors --limit 2 --lower test`, it works very well.

**Comment by cc32d9** [comment]
see https://github.com/EOSIO/eosjs/issues/652

**Comment by bradlhart** [comment]
`table_key` has been deprecated, you can switch to `index_position` and use the position of your secondary key in order of the multi-index definition (1 - primary key, 2 - secondary key, 3 - third, etc)

See https://github.com/EOSIO/eosjs/pull/675
