### ISSUE TITLE
Multi-signed transactions and CPU usage

### ISSUE THREAD

**Issue by jsdev630** [EOSIO/eosjs#618]
Our question related to eosjs 1.6 library.
We have worked on a solution for providing coverage of CPU resources for our customers.
To provide it we have decided to implement a possible approach to solve it with double sign user transactions additionally with our account.
As we know the first account provided in the authorization header is billable for CPU resources required for performing the transaction.
So workaround of the solution looks like this:

On the front-end create a transaction with proper authorization headers [our account, customer account].
Sign transaction by customer (using Scatter) and don't broadcast it.
Send created transaction to the back-end.
Sign the transaction with our account.
Push the transaction.
And overall all works good, but for some part of our customers, the solution doesn't work.
They are getting the following error:
Billed CPU time is greater than maximum billable CPU time for the transaction.

By researching that issue, we have found that it happens because authorization headers getting reverse order for their transactions.
And it only happens if their account name is going before our account name in alphabetical order.
Is that possible that eosjs sorts account names in alphabetical order? And can be there any workaround for that issue?

Library version: 1.6
OS: Windows
Browser: Chrome 78.x

**Comment by tbfleming** [comment]
We don't have personal available to support 1.6.
