### ISSUE TITLE
Typescript defnitions for get_block response (GetBlockResult) incomplete 

### ISSUE THREAD

**Issue by zeelux** [EOSIO/eosjs#619]
**Version of EOSJS**
Latest

**Describe the bug**
The `GetBlockResult` type defined in `eosjs-rpc-interfaces.ts` is missing a large amount of data that is actually returned in this call. In particular the following fields are missing:
- transactions
- new_producers
- header_extensions
- block_extensions

**To Reproduce**
Attempt to use EOSJS in TypeScript application and access data on a transaction in a block. TypeScript will complain that the `transactions` property does not exist so compilations will fail when trying to access it or any of the many sub-properties.

**Expected behavior**
The .d.ts typescript definitions should include ALL properties in the GetBlockResult return type.

**Screenshots**
<img width="422" alt="Screen Shot 2019-12-03 at 9 17 27 AM" src="https://user-images.githubusercontent.com/2394363/70058896-c3662c00-15ad-11ea-9c53-515645f3813e.png">

**Comment by tbfleming** [comment]
Right now it only includes what eosjs needs to function. Most of the information in get_block is worse than useless; it's actually misleading.

**Comment by zeelux** [comment]
This duplicates issue #602
