### ISSUE TITLE
some context is missing?

### ISSUE THREAD

**Issue by dixia** [EOSIO/eosjs#630]
**Version of EOSJS**
20.0

**Describe the bug**
the `yarn build-web` command does not seem working in this page:  https://eosio.github.io/eosjs/latest/basic-usage/browser

Some prerequisite is required? 

**To Reproduce**

Run this command:
`yarn build-web`

**Expected behavior**
command can be execute

**Desktop (please complete the following information):**
 - OS: mac os x brew x yarn v1.21.1

**Additional context**

**Comment by sanaraufx** [comment]
Cleaning up old issues so we can focus on more recent issues. Please reopen this ticket if needed. Thank you.
