### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by dixia** [EOSIO/eosjs#640]
**Version of EOSJS**
20.0

**Describe the bug**
This looks like a dead link: https://eosio.github.io/eosjs/latest/00_introduction
linked from this page: https://eosio.github.io/eosjs/latest/technical-overview

**To Reproduce**
1. Go to https://eosio.github.io/eosjs/latest/technical-overview

**Comment by lparisc** [comment]
Intro page had been renamed to main index file to replace README.md as splash page in docs.
