### ISSUE TITLE
How to access to hyperion history ?

### ISSUE THREAD

**Issue by lansehuiyi6** [EOSIO/eosjs#644]
**Version of EOSJS**
_which version of eosjs exhibits the issue_
"eosjs": "^20.0.2",
**Describe the bug**

For now, most jungle node change to hyperion history from v1 history. So does the eosjs still support Hyperion version?

Because when i try to get access to hyperion node, the follow error will be got.

storeman 2020-01-16 18:13:40,968 syncLogger ERROR getBlockNumberSync from : EOS { FetchError: invalid json response body at https://jungle.hyperion.eosrio.io/v1/chain/get_info reason: Unexpected token < in JSON at position 0
    at Y:\wanchain\crossChain\git\storeman\node_modules\node-fetch\lib\index.js:272:32
    at process._tickCallback (internal/process/next_tick.js:68:7)
  message:
   'invalid json response body at https://jungle.hyperion.eosrio.io/v1/chain/get_info reason: Unexpected token < in JSON at position 0',
  type: 'invalid-json',
  isFetchError: true }

And in file node_modules\eosjs\dist\eosjs-jsonrpc.js, we can find follow, does this mean, this cannot support hyperion version?  :
    /** Raw call to `/v1/chain/get_info` */
    JsonRpc.prototype.get_info = function () {
        return __awaiter(this, void 0, void 0, function () {
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0: return [4 /*yield*/, this.fetch('/v1/chain/get_info', {})];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };

**Comment by tbfleming** [comment]
eosjs doesn't provide wrappers for hyperion. The wrappers it provides for the deprecated history plugin are minimal and easy to reproduce for other APIs. e.g.

```
public async history_get_actions(accountName: string, pos: number = null, offset: number = null) {
    return await this.fetch('/v1/history/get_actions', { account_name: accountName, pos, offset });
}
```

**Comment by lansehuiyi6** [comment]
> eosjs doesn't provide wrappers for hyperion. The wrappers it provides for the deprecated history plugin are minimal and easy to reproduce for other APIs. e.g.
> 
> ```
> public async history_get_actions(accountName: string, pos: number = null, offset: number = null) {
>     return await this.fetch('/v1/history/get_actions', { account_name: accountName, pos, offset });
> }
> ```

Is there any play to support hyperion in future?

**Comment by tbfleming** [comment]
No, eosjs only supports products from b1.
