### ISSUE TITLE
EOSJS : Core-js@2.6.11 Issue

### ISSUE THREAD

**Issue by jamhuery** [EOSIO/eosjs#651]
i try to install eosjs with npm ,, igot some error 

npm WARN deprecated text-encoding@0.7.0: no longer maintained
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.

> core-js@2.6.11 postinstall /home/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

**Comment by jlamarr22** [comment]
Removed these warnings in the above PR (#655).
