### ISSUE TITLE
table_key must be removed from code and docs

### ISSUE THREAD

**Issue by cc32d9** [EOSIO/eosjs#652]
in eosjs 20.x and 21.x, `get_table_rows` uses `table_key` argument, and it's described in the documentation as secondary key name, presumably usable instead of `index_position`.

In fact, chain_plugin does not recognize `table_key`, so the examples don't work, as you can see in several bug reports.

Either `table_key` needs to be removed from eosjs completely, or eosjs needs an additional lookup to get the index names and then pass the corresponding `index_position` in `get_table_rows`.

**Comment by bradlhart** [comment]
We've adjusted code and documentation in the current edge release and those changes will also be included on the v21 release.
