### ISSUE TITLE
[docs] Suggestion / Change Request

### ISSUE THREAD

**Issue by jeremybeal11** [EOSIO/eosjs#662]
File: [docs/index.md](https://github.com/EOSIO/eosjs/blob/develop/docs/index.md)

When I click on [basic usage](https://eosio.github.io/eosjs/latest/basic-usage/03_basic-usage) on the [eosjs/latest](https://eosio.github.io/eosjs/latest/index) page it takes me to a 404 page.

**Comment by jlamarr22** [comment]
Thanks for finding this! This was fixed in the above PRs, so is now available in the latest `edge` version and will be included in v21.
