### ISSUE TITLE
SerialBuffer.pushAsset does not validate symbol

### ISSUE THREAD

**Issue by michaeljyeates** [EOSIO/eosjs#665]
**Version of EOSJS**
21

**Describe the bug**
SerialBuffer.pushAsset will accept invalid symbols in the string supplied

**To Reproduce**
```
const {Serialize} = require('eosjs');

const sb = new Serialize.SerialBuffer({
    textEncoder: new TextEncoder,
    textDecoder: new TextDecoder
});

sb.pushAsset('10.000 EOS blah')

console.log(sb.getAsset())

>> 10.000 EOS bla
```

This should throw an error after validating the symbol

**Comment by jlamarr22** [comment]
Updated in #666 and #667 and will be included in v21.
