### ISSUE TITLE
Connecting to the blockchain from the web application 

### ISSUE THREAD

**Issue by mlawand** [EOSIO/eosjs#67]
Sample Javascript code
```
eos = Eos.Localnet();
eos.getBlock(3).then(result => {console.log(result)});
```

Error : 
api error => http://127.0.0.1:8888/v1/chain/get_block {"block_num_or_id":3} TypeError: NetworkError when attempting to fetch resource. eos.js:23186:7
	fetchMethod/</< http://localhost:5000/js/EOS/eos.js:23186:7

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://127.0.0.1:8888/v1/chain/get_code. (Reason: CORS header ‘Access-Control-Allow-Origin’ does not match ‘true’).

**Comment by regularjack** [comment]
You probably need to add `127.0.0.1` to `access-control-allow-origin` in your `config.ini`.

**Comment by mlawand** [comment]
@regularjack i have tried it and i am still getting the same error.

**Comment by nsjames** [comment]
What's the exact configuration line you added to your config.ini?

**Comment by mlawand** [comment]
@nsjames please find the below.

# The local IP and port to listen for incoming http connections. (eosio::http_plugin)
http-server-address = 127.0.0.1:8888

# Specify the Access-Control-Allow-Origin to be returned on each request. (eosio::http_plugin)
access-control-allow-origin = true

# Specify the Access-Control-Allow-Headers to be returned on each request. (eosio::http_plugin)
access-control-allow-headers = true

# Specify if Access-Control-Allow-Credentials: true should be returned on each request. (eosio::http_plugin)
access-control-allow-credentials = false

and thank you for your youtube videos, it really helped me alot to get started

**Comment by nsjames** [comment]
try `access-control-allow-origin = *`

**Comment by nsjames** [comment]
Great! Close it up ;)

**Comment by tcpaul** [comment]
Im having this same issue, which config.ini did you change?

**Comment by MrToph** [comment]
@tcpaul the one in
Mac OS: ~/Library/Application Support/eosio/nodeos/config
Linux: ~/.local/share/eosio/nodeos/config

**Comment by gpmn** [comment]
access-control-allow-origin = *
why 127.0.0.1 do not work?
it is not safe enough in product environment to enable all source, is there any better way?

**Comment by Dylan-Phoon** [comment]
+1 @gpmn

**Comment by nsjames** [comment]
I don't think 0.0.0.0 is **only** a loopback so it'll be exposed to the general network and might be dangerous if users have keosd open on it. `localhost` can also be spoofed to be externally connectable, so if security is a concern it's always best to use the manually defined `127.0.0.1` loopback.
