### ISSUE TITLE
Consider cross-fetch

### ISSUE THREAD

**Issue by gaboesquivel** [EOSIO/eosjs#680]
latest 'node-fetch' throws type errors consider https://www.npmjs.com/package/cross-fetch 

```
import fetch from 'cross-fetch'
import { JsonRpc } from 'eosjs'

// Instantiate a new JsonRpc object, with the Network Api Uri, and a request object
const rpc = new JsonRpc('https://api.kylin.alohaeos.com', { fetch })
```

**Comment by gaboesquivel** [comment]
hmm I'm still getting the same error with 'cross-fetch', it went away briefly but it was an IDE thing

<img width="910" alt="Screen Shot 2020-02-06 at 12 25 12 PM" src="https://user-images.githubusercontent.com/391270/73966546-d6fa7f80-48db-11ea-8826-c77b6d8a53fc.png">

**Comment by jlamarr22** [comment]
Thank you for finding this!

The fix for this has been merged and is available in the latest version of `edge` and will be available in V21 once it is released.
