### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by rahul1083** [EOSIO/eosjs#688]
Getting error on account creation :-
const defaultPrivateKey = "5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3"; // bob
const signatureProvider = new JsSignatureProvider(['5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3']);
const api = new Api({ rpc, signatureProvider, textDecoder: new TextDecoder(), textEncoder: new TextEncoder() });

const result = await api.transact(
{
account: 'eosio',
name: 'newaccount',
authorization: [{
actor: 'eosio',
permission: 'active',
}],
data: {
creator: 'eosio',
name: 'mynewaccount',
owner: {
threshold: 1,
keys: [{
key: '6FPFZqw5ahYrR9jD96yDbbDNTdKtNqRbze6oTDLntrsANgQKZu',
weight: 1
}],
accounts: [],
waits: []
},
active: {
threshold: 1,
keys: [{
key: '6FPFZqw5ahYrR9jD96yDbbDNTdKtNqRbze6oTDLntrsANgQKZu',
weight: 1
}],
accounts: [],
waits: []
},
},
},
{
blocksBehind: 3,
expireSeconds: 30,
}
);

**Comment by jlamarr22** [comment]
Assuming you already have the account added in you authenticator and your keys are correct, you will need to add an empty collection of `actions`. See below. Please let me know if this fixes your issue and I will put in an update to make this more user-friendly or update the example we have listed at https://github.com/EOSIO/eosjs/blob/develop/docs/how-to-guides/05_how-to-create-an-account.md#newaccount 

```javascript
const result = await api.transact({
    account: 'eosio',
    name: 'newaccount',
    authorization: [{
        actor: 'eosio',
        permission: 'active',
    }],
    data: {
        creator: 'eosio',
        name: 'mynewaccount',
        owner: {
            threshold: 1,
            keys: [{
                key: '6FPFZqw5ahYrR9jD96yDbbDNTdKtNqRbze6oTDLntrsANgQKZu',
                weight: 1
            }],
            accounts: [],
            waits: []
        },
        active: {
            threshold: 1,
            keys: [{
                key: '6FPFZqw5ahYrR9jD96yDbbDNTdKtNqRbze6oTDLntrsANgQKZu',
                weight: 1
            }],
            accounts: [],
            waits: []
        },
    },
    actions: [] // Add this here
}, {
    blocksBehind: 3,
    expireSeconds: 30,
});
```

**Comment by rahul1083** [comment]
Yes this fixed my issue, thank for your help
