### ISSUE TITLE
Fetching data in React Native fails

### ISSUE THREAD

**Issue by ekkis** [EOSIO/eosjs#693]
**Version of EOSJS**
20.0.3

**Describe the bug**
An attemp to fetch data from the blockchain fails under React Native but succeeds under NodeJs with identical code

**To Reproduce**
```js
const {JsonRpc} = require('eosjs')
const fetch = require('isomorphic-unfetch')
const rpc = new JsonRpc('https://jungle.eosphere.io:443', { fetch })
var {rows, more} = await rpc.get_table_rows({
                table, code, scope, json: true
            })
```

**Expected behavior**
the `rows` variable should be populated with an array of the table's contents

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 13.3
 - React Native 0.61.5

**Additional context**
According to this article: https://medium.com/eosio/eosjs-version-20-beta3-react-native-support-and-enhancements-for-signature-providers-9b39f89b574f my version of eosjs should work under react native.  I've looked into EvaCoop's eosjs-react-native but I don't need signing functionality, just the JsonRpc for reading

The code above works from NodeJs but breaks under RN with the following error:

>  WARN  Possible Unhandled Promise Rejection (id: 2):
> SyntaxError: JSON Parse error: Unrecognized token '<'
> parse@[native code]
> tryCallOne@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3244:16
> http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3345:27
> _callTimer@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:30619:17
> _callImmediatesPass@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:30655:19
> callImmediates@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:30874:33
> callImmediates@[native code]
> __callImmediates@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:2654:35
> http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:2431:34
> __guard@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:2637:15
> flushedQueue@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:2430:21
> flushedQueue@[native code]
> invokeCallbackAndReturnFlushedQueue@[native code]

**Comment by bradlhart** [comment]
`JSON Parse error: Unrecognized token '<'` means you got an HTML response from `https://jungle.eosphere.io:443`, is it consistently returning that response?

You could try this code to see what the HTML response is:
```javascript
const fetch = require('isomorphic-unfetch');

try {
  const response = await fetch('https://jungle.eosphere.io:443/v1/chain/get_table_rows', {
    body: JSON.stringify({table, code, scope, json: true}),
    method: 'POST',
  });
  const responseText = await response.text();
  console.log(responseText);
} catch (e) {
  console.log(e);
}
```

**Comment by ekkis** [comment]
so the issue is that if I run it from NodeJs it works fine but under RN it breaks

**Comment by ekkis** [comment]
if I run your code (with a little modification for values in table, code, scope and async function wrap, I get what I expect: JSON

**Comment by ekkis** [comment]
ah.  I was being dense.  I ran your code under RN and received HTML:
```html
<html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>
```
so the service is available from NodeJs but not from RN.  do I need to whitelist or something?

**Comment by bradlhart** [comment]
I don't believe so.  You could try other calls to `https://jungle.eosphere.io` or other API endpoints to troubleshoot though.

**Comment by ekkis** [comment]
I've read that because the code is running in a simulator, it cant' access `localhost`, for example.  so I looked into access issues.  there's an Info.plist where `NSAllowsArbitraryLoads` is set to true, and I've tried fetching other web pages.  that seems to work ok

**Comment by ekkis** [comment]
this is quite weird.  following your advice, I switched to the `http://jungle2.cryptolions.io:8888` endpoint.  if I call it with NodeJs I get the data I expect.  calling it from RN does not fail but brings me back and empty set:
```json
{"rows":[],"more":false,"next_key":""}
```
thoughts?

**Comment by ekkis** [comment]
quick update.  `http://jungle2.cryptolions.io:8888` works fine (I had the wrong table name in the code above, which I've fixed) but `http://jungle.cryptolions.io:8888` still fails.  the failure seems to happen only under React Native.  I've built a React Web test, which succeeds with either endpoint, as does NodeJs

**Comment by bradlhart** [comment]
My only other thought would be that maybe there's something between your phone and the endpoint that isn't between your computer running node and the endpoint.  Something like a proxy, different network with different settings, etc.

Since you are still getting the error from the code I posted above (which is what eosjs performs, except uses `response.json()`) and other endpoints do work correctly, the issue has been confirmed to not be from eosjs.

**Comment by ekkis** [comment]
I think I agree with you that it's not an eosjs issue.  there seems to be something wrong with that particular endpoint, though why requests from my emulator vs. from the console behave differently I don't get.  I'm guessing eosjs is formulating the request differently and the endpoint can tell
