### ISSUE TITLE
Does the action of EOS contract have a return value and how to get the return value    

### ISSUE THREAD

**Issue by songsongMr** [EOSIO/eosjs#70]
1     Does the action of EOS contract have a return value?

code:
eos.contract('iin').then(eosio => {
          eosio.transaction(cur => {
            cur.add({"name": "lele5", "context": "eosio's context", "deposit": 5});      
          }).then(function (val) {
            console.log(val);    //the val is the transaction info,not the return value of  add(action)        
          });
2    if the action of add return some value (for example return a string or a struct ),how can I get the return value.

**Comment by tbfleming** [comment]
1. No

**Comment by jcalfee** [comment]
I think the idea is to store return values in a table for later fetching.  If you need to calcualte return values and it is not worth storing it is probably better to do that offchain so it does not consume blockchain resources.

**Comment by chris-allnutt** [comment]
A contract action will either be queued for inclusion in a block or fail immediately.  In some cases a block may never be included.  The response from the action call will have details such as the transactionId.  You can then query the blockchain using the transaction id to find the final status of the transaction.

**Comment by DaLN** [comment]
> The response from the action call will have details such as the transactionId.

Hi @chris-allnutt , Where can i find more information about how the response from the action call is structured and what it contains exactly ?
