### ISSUE TITLE
Remove unnecessary call to get_block_header_state

### ISSUE THREAD

**Issue by jlamarr22** [EOSIO/eosjs#702]
**Version of EOSJS**
All versions

**Describe the bug**
`generateTapos` throws an error on transaction when calling `get_block_header_state`, but does not actually need to call it.

**To Reproduce**
1. Spin up a new chain
2. Generate a transaction
3. Error in console when `transact` calls `generateTapos`

**Expected behavior**
Should not throw if calling `generateTapos` without a valid `last_irreversible_block_num`.

**Additional context**
Porting this over from https://github.com/EOSIO/eosjs/pull/698
Co-Authored By: @UMU618 umu618@hotmail.com

**Comment by UMU618** [comment]
mark #698

**Comment by jlamarr22** [comment]
Fixed in above PR.
