### ISSUE TITLE
EOSJS issues with fetch() in Safari

### ISSUE THREAD

**Issue by Novusphere** [EOSIO/eosjs#712]
**Version of EOSJS**
Last tested with `"eosjs": "20.0.0"`

**Describe the bug**
fetch() requests fail in Safari. I believe this issue documents the same if not a similar bug: https://github.com/github/fetch/issues/447

**To Reproduce**
Initialize an instance of eosjs with json rpc and fetch being `node-fetch`. Make any rpc request such as `get_info()` and it will fail in the browser. I'm not 100% certain why this occurs, but it seems to be a Safari-only related issue.

**Expected behavior**
`fetch()` should succeed, it works fine in Chrome/Firefox/Edge.

**Additional context**
This can be resolved by supplying your own `fetch()` function in place of `node-fetch` using `axios`. I'm sure there's a solution using `fetch()` but this was the first fix I tried that worked and was pretty simple.

```js
        async function axiosFetch(url, args) {
            let result = undefined;
            if (args.method == 'GET') {
                result = await axios.get(url);	
            }
            else if (args.method == 'POST') {
                const body = args.body;
                result = await axios.post(url, body);
            }
            return {
                ok: true,
                json: async function() {
                    return result.data;
                }
            }
        }
```

This should work fine as eosjs only makes `POST` type requests:

```js
            const f = this.fetchBuiltin;
            response = await f(this.endpoint + path, {
                body: JSON.stringify(body),
                method: 'POST',
            });
```

**Comment by jlamarr22** [comment]
You shouldn't have to use `node-fetch` if you're running in the browser as all modern browsers already include `fetch`. You only need to specify the `fetch` argument if:
1. You're running in nodejs: https://github.com/EOSIO/eosjs#json-rpc (use `node-fetch`)
2. You want to override a browser's default `fetch` behavior

Is your browser on this supported list? https://caniuse.com/#feat=fetch

**Comment by Novusphere** [comment]
I'm aware you *shouldn't have to* but this shouldn't cause issues *if you do* is what I'm pointing out. However, I had a user test with the newest version of Safari and they don't seem to be experiencing any issues so I'm wondering now if the user who reported this problem to me originally was on an older version of Safari. I'll double check with them... Going to close issue for now...
