### ISSUE TITLE
R1 Signatures Incorrect

### ISSUE THREAD

**Issue by jlamarr22** [EOSIO/eosjs#732]
**Version of EOSJS**
All

**Describe the bug**
R1 signatures are not generated properly.

**To Reproduce**
1. Try to sign data with an R1 key. 
1. Try to recover public key from signature. 

**Expected behavior**
1. You may or may not receive an error about high r values. (needs canonical check)
1. You won't receive the correct public key. (needs recovery parameter updates)

**Additional context**
https://github.com/EOSIO/eosjs/pull/731 is where the bug was originally reported. This issue will track progress. New PR will be created to add tests and another update for canonical checking.

**Comment by bradlhart** [comment]
Edge release of the npm package has these changes and the issue should be resolved.
