### ISSUE TITLE
[v21] AES encryption

### ISSUE THREAD

**Issue by jnordberg** [EOSIO/eosjs#735]
eosjs-ecc provided a [very useful helper for AES encryption](https://github.com/EOSIO/eosjs-ecc/blob/a806b93fbbccec8d38c0c02998d204ff2040a6ae/src/aes.js#L56) that's no longer included now that eosjs uses elliptic.js.

Any plans to continue supporting this? IMO it's a great thing to offer since it is really easy to get wrong when rolling your own encryption scheme

Refs #734

**Comment by tbfleming** [comment]
eosjs focuses on communicating with nodeos. AES isn't part of that.
