### ISSUE TITLE
some problems about sign 

### ISSUE THREAD

**Issue by songsongMr** [EOSIO/eosjs#75]
When we use an account to initiate a transaction request.we should do this first, add its active privateKey  in keyProvider then connect to the Eos. Is there other methods to complete the certification.

**Comment by Dylan-Phoon** [comment]
As I understand it, the {keyProvider: "insert_private_key_here"} is not broadcast and signing a transaction is done locally. So example: `eos.transfer(params, {sign:true, broadcast:true})` is secure to do from anywhere. Can someone correct me if I am wrong?

**Comment by jcalfee** [comment]
Private keys are never sent across a network.  Also, the hash that your signing is calculated locally without trusting the server.  Public keys might be sent across the network if you start giving eosjs more then one private key to deal with so eosjs knows which one to sign with.

**Comment by songsongMr** [comment]
thanks for you clear description!
