### ISSUE TITLE
eos.getAccount() not behaving as expected

### ISSUE THREAD

**Issue by Dylan-Phoon** [EOSIO/eosjs#76]
When I run
`eos.getAccount("dylan1").then(function(res){
    console.log(res)
});`

It returns this: 
`{ account_name: 'dylan1',
  permissions: 
   [ { perm_name: 'active', parent: 'owner', required_auth: [Object] },
     { perm_name: 'owner', parent: '', required_auth: [Object] } ] }`

Expected should be:
`{
  "account_name": "name",
  "eos_balance": "uint64",
  "staked_balance": "uint64",
  "unstaking_balance": "uint64",
  "last_unstaking_time": "time",
  "permissions": "vector<permission>",
  "producer": "optional<producer_info>"
}`

As you can see, `"eos_balance": "uint64",
  "staked_balance": "uint64",
  "unstaking_balance": "uint64",
  "last_unstaking_time": "time",` are all missing...

**Comment by jcalfee** [comment]
Eosjs is just pass-through for nodeos .. It is defainately your nodeos version.  How are you connecting to the backend?

**Comment by Dylan-Phoon** [comment]
Hmmm, I seem to have gotten it fixed thanks to some help in the Eos Developer chat by using `getTableRows()`. Apparently the data is no longer accessible with `getAccount()`.

**Comment by ripley** [comment]
@Dylan-Phoon Could you tell which API can get those info for now?

**Comment by plazav** [comment]
@Dylan-Phoon, please share your solution
