### ISSUE TITLE
error 3050003: assertion failure with message: no balance object found 

### ISSUE THREAD

**Issue by adeelnaqvi172** [EOSIO/eosjs#794]
![Screenshot from 2020-09-08 22-48-29](https://user-images.githubusercontent.com/53054023/92510695-af7ae500-f225-11ea-9f25-a7a485c1c227.png)

i am facing this error creating new account using system newaccount please help

>

**Comment by bradlhart** [comment]
Apologies but this does not seem to be related to the eosjs library since you are only using cleos.
