### ISSUE TITLE
What method is used to sign transaction?

### ISSUE THREAD

**Issue by Dylan-Phoon** [EOSIO/eosjs#81]
What method is used to produce a valid signature to be included in the transaction so that it can be pushed to the blockchain? 

So for example in ethereum you can use ethereumjs-tx like this:

```
var Tx = require('ethereumjs-tx')
var privateKey = new Buffer('e331b6d69882b4cb4ea581d88e0b604039a3de5967688d3dcffdd2270c0fd109', 'hex')

var rawTx = {
  nonce: '0x00',
  gasPrice: '0x09184e72a000', 
  gasLimit: '0x2710',
  to: '0x0000000000000000000000000000000000000000', 
  value: '0x00', 
  data: '0x7f7465737432000000000000000000000000000000000000000000000000000000600057'
}

var tx = new Tx(rawTx)
tx.sign(privateKey)

var serializedTx = tx.serialize()
console.log(serializedTx.toString('hex'))
 ```

How would I do this with eosjs? I hate to open an issue here but I have asked everywhere else and haven't been able to get an answer. Really appreciate the help! :)

**Comment by chris-allnutt** [comment]
When you instantiate eosjs you can provide a keyProvider which is the private key.  When you execute a contract action eosjs signs and transmits the action.  You don't have to explicitly sign it.

**Comment by jcalfee** [comment]
Turn broadcast off and send the transaction as usual.  The result of the function call will give you the transaction back along with any signatures..

**Comment by Dylan-Phoon** [comment]
But this still means that you have to do ```var eos = Eos.Localnet()``` or var ```eos = Eos.Testnet```
and then ```eos.transfer(params, {broadcast: false})```

Is there a way to sign the raw transaction produced from ```transfer```? So for example:
```
var rawTx = eos.transfer(params, {broadcast: false, sign: false})
var signedTx = rawTx.<sign_function>(insert_private_key_here)
```

**Comment by cassade** [comment]
I'm interested too. Dedicated method for signing transactions without necessity to connect to the node is extremely useful. I think it's a common scenario to have a connected node for tracking and creating raw transactions, and secure area with offline app for signing transactions.

**Comment by Dylan-Phoon** [comment]
Nevermind... I have figured it out. You have to first serialize the rawtx and then sign.

**Comment by jcalfee** [comment]
The constructors are not connecting to the network..  You can serialize it, you can also try to get a `eos` constructed with broadcast false then pass pass it to eos.transaction ..

I'll review the README next time I am in there with this in mind..

**Comment by jcalfee** [comment]
@cassade https://github.com/eosio/eosjs#offline-or-cold-storage-transaction shows signing a transaction without having to connect to a node.  You have to get a recent block first.

**Comment by jcalfee** [comment]
@markatz https://github.com/EOSIO/eosjs/blob/v16.0.8/src/write-api.js#L498-L510

**Comment by markatz** [comment]
@jcalfee thanks for the help. My javascript knowledge is rather limited though. The code seems to sign the concatenation of the latest blockid with the transaction details. From wireshark dumps with cleos, I think it is the section below but I don't know if it includes the white space or not:
{
    "expiration": "2018-09-17T08:24:04",
    "ref_block_num": 59970,
    "ref_block_prefix": 1935413997,
    "max_net_usage_words": 0,
    "max_cpu_usage_ms": 0,
    "delay_sec": 0,
    "context_free_actions": [],
    "actions": [{
        "account": "eosio.token",
        "name": "transfer",
        "authorization": [{
            "actor": "user2",
            "permission": "active"
          }
        ],
        "data": "00000000007115d600000000807115d601000000000000000447434e00000000046d656d6f"
      }
    ],
    "transaction_extensions": []
  }

**Comment by jcalfee** [comment]
@markatz transactions are serialized in binary before they are signed or stored on the blockchain.  It takes a major effort to do this.  You'll probably need to use a library.  There are ways to do this in c++ to, but if your apps runs on the device your security model is better if you do this on the device.

**Comment by markatz** [comment]
@jcalfee Yes, we are also going through the laborious effort of creating the binargs. Using the RPC API to serialize transactions is dangerous, and unfortunately, the EOS libraries don't seem to be easy to port onto mobile platforms, so we have to take the long route of figuring everything out. I am just finding it hard to determine from the code exactly what gets signed.

Have to get to grips with eosjs and use lots of console.log() calls. Just having problems getting eosjs working properly, probably due to EOS version mismatch. That would be for another question thread though. Thanks for your help.

**Comment by markatz** [comment]
@jcalfee I managed to install eosjs and even performed a transfer successfully, but when I add console.log() functions in write-api,js they get ignored. It seems like if I do npm link or npm install the src files are ignored. Even if I add junk into a source file there is no complaint.

**Comment by jcalfee** [comment]
Run npm build in eosjs-api then npm link should work fine.  That is how I do it..

**Comment by cancerts** [comment]
> What method is used to produce a valid signature to be included in the transaction so that it can be pushed to the blockchain?
> 
> So for example in ethereum you can use ethereumjs-tx like this:
> 
> ```
> var Tx = require('ethereumjs-tx')
> var privateKey = new Buffer('e331b6d69882b4cb4ea581d88e0b604039a3de5967688d3dcffdd2270c0fd109', 'hex')
> 
> var rawTx = {
>   nonce: '0x00',
>   gasPrice: '0x09184e72a000', 
>   gasLimit: '0x2710',
>   to: '0x0000000000000000000000000000000000000000', 
>   value: '0x00', 
>   data: '0x7f7465737432000000000000000000000000000000000000000000000000000000600057'
> }
> 
> var tx = new Tx(rawTx)
> tx.sign(privateKey)
> 
> var serializedTx = tx.serialize()
> console.log(serializedTx.toString('hex'))
> ```
> How would I do this with eosjs? I hate to open an issue here but I have asked everywhere else and haven't been able to get an answer. Really appreciate the help! :)

i also want do that like ethereum,but can't solve it ,can give your methords
