### ISSUE TITLE
The  get_accounts_by_authorizers() jsonrpc call is missing

### ISSUE THREAD

**Issue by feri42** [EOSIO/eosjs#815]
**Version of EOSJS**
21.0.3

**Describe the bug**
The `/v1/chain/get_accounts_by_authorizers` is missing.

**Expected behavior**
To be able to call `jsonrpc.get_accounts_by_authorizers()`

**Comment by bradlhart** [comment]
This endpoint is now available in either eosjs@edge or eosjs@RC and will be released with the next version of eosjs.
