### ISSUE TITLE
(node:11727) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch()

### ISSUE THREAD

**Issue by thekevincoutinho** [EOSIO/eosjs#819]
ERROR

- Screenshot of the error attached. 

Code Below

var EOS = require('eosjs');
var ecc = require('eosjs-ecc');

// Default configuration
var config = {
  chainId: '2a02a0053e5a8cf73a56ba0fda11e4d92e0238a4a2aa74fccf46d5a910746840', // 32 byte (64 char) hex string
  keyProvider: '',
  httpEndpoint: 'https://jungle3.cryptolions.io:443',
  expireInSeconds: 60,
  broadcast: true,
  verbose: false, // API activity
  sign: true
};

var eos = EOS(config);

eos.transaction(tr => {
  
  tr.newaccount({
    creator: kolkata54321,
    name: aiposblock12,
    owner: EOS6uKngYQA61q9Si8p9kj5nWzCBDvrAXeYQ2JYYhQiNddzqaXphp,
    active: EOS6uKngYQA61q9Si8p9kj5nWzCBDvrAXeYQ2JYYhQiNddzqaXphp
  });
  
  tr.buyrambytes({
    payer: payer,
    receiver: newAccountName,
    bytes: 1024 * 3
  });
  
  tr.delegatebw({
    from: kolkata54321,
    receiver: humanbot2020,
    stake_net_quantity: '1.0000 EOS',
    stake_cpu_quantity: '1.0000 EOS',
    transfer: 0
  });
}).then(function (result) {
  console.log(result);
}).catch(function (error) {
  
  if (error) {
    console.log(JSON.parse(error));
  }
});

**Comment by thekevincoutinho** [comment]
@conr2d Can you please help mate?

**Comment by bradlhart** [comment]
Do you happen to have the full error message that was sent back?  The unhandled exception error that javascript sends is just a part of the error message.

Additionally, it seems like you are using an older version of eosjs.  Upgrading to the latest version of eosjs v21.0.3 or at least above v20 could solve your issue.

Your issue also seems very closely related to https://github.com/EOSIO/eosjs/issues/821

**Comment by bradlhart** [comment]
Haven't received a response so closing this ticket as stale.
