### ISSUE TITLE
EOSJS account creation problem 

### ISSUE THREAD

**Issue by achinta3** [EOSIO/eosjs#821]
eos.transaction(tr => {
  tr.newaccount({
    creator: 'kolkata54321',
    name: 'humanbot2020',
    owner: 'EOS6uKngYQA61q9Si8p9kj5nWzCBDvrAXeYQ2JYYhQiNddzqaXphp',
    active: 'EOS6uKngYQA61q9Si8p9kj5nWzCBDvrAXeYQ2JYYhQiNddzqaXphp'
  });
  tr.buyrambytes({
    payer: 'kolkata54321',
    receiver: 'humanbot2020',
    bytes: 8192
  });

  tr.delegatebw({
    from: 'kolkata54321',
    receiver: 'humanbot2020',
    stake_net_quantity: '10.0000 JUNGLE',
    stake_cpu_quantity: '10.0000 JUNGLE',
    transfer: 0
  });
}).then(function (result) {
  console.log(result);
})
.catch(function (error) {
  if (error) {
    console.log(JSON.parse(error));
  }
});

this is my code , 

i am getting error . 

SyntaxError: Unexpected token T in JSON at position 0
    at JSON.parse (<anonymous>)
    at /Users/achintadas/Desktop/untitled folder/api/eosjs-guide/index.js:79:22
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:4716) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4716) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(base) Achintas-MacBook-Pro:eosjs-guide achintadas$

**Comment by bradlhart** [comment]
It seems like the response you are getting from the endpoint is starting with a T character, as opposed to typical JSON format that starts with an opening curly brace `{`.  This might mean that you are getting an error message back from the endpoint directly that is not in JSON format.

The response in your browser's developer console might show the whole response before it's attempted to be parsed.  Try opening the developer console and navigating to the network tab.  The next time you run your operation, a request and response should be sent to and from your endpoint.

It also appears that you are using an older version of eosjs.  Possibly upgrading to the latest v21.0.3 or at least above v20 will resolve your issue.

**Comment by achinta3** [comment]
Thank you for your reply , i have updated the version but the problem not solve. 
i have shared the screenshot, please reply 
thanks . 

![Screenshot 2020-12-23 at 11 25 55 AM](https://user-images.githubusercontent.com/75778116/102964754-6455bb00-4512-11eb-9ade-6a757280779c.png)

**Comment by achinta3** [comment]
Thank you for your reply , 

i have updated the version of EOSJS but i got another error . 

I share the screenshot, please reply. 

Thank you 

![Screenshot 2020-12-23 at 11 39 57 AM](https://user-images.githubusercontent.com/75778116/102965488-edb9bd00-4513-11eb-96e1-209f6b524c04.png)
![Screenshot 2020-12-23 at 11 39 57 AM](https://user-images.githubusercontent.com/75778116/102965499-ef838080-4513-11eb-8dc2-6c4b5d00e996.png)

**Comment by bradlhart** [comment]
There was a shift in how code would be written to construct a transaction.  You can find a lot of information in the eosjs documentation https://developers.eos.io/manuals/eosjs/latest/index and more specifically, https://developers.eos.io/manuals/eosjs/latest/how-to-guides/how-to-submit-a-transaction on how to construct and submit a transaction with the latest eosjs code.

**Comment by bradlhart** [comment]
I assume you have read the documentation and moved forward with the more latest version of eosjs.  Please let us know if there are any other issues.  Closing this ticket for now.
