### ISSUE TITLE
missing abi action: uploadfile action.data transaction.actions

### ISSUE THREAD

**Issue by Joyia012** [EOSIO/eosjs#828]
**Version of EOSJS**
_Using 16.0.9_

**Throws error of Missing abi action**

Hello Everyone,

I am facing some issue regarding missing abi action. I have attached the code below of upload file action.
I am using scatter while Uploading a file.  Also, I have write the function in contract code and used API as well.
All functions are working fine. Just upload file is not working.
**ABI of upload is also generated** 

But I am facing this error. Can anybody help me in that.
Thanks in advance.

**Error Image**

![i](https://user-images.githubusercontent.com/45730441/106706786-04265e80-6612-11eb-8d85-ec7c2083d7c7.png)

**Code**

```eos.transaction(
                    {
                        actions: [
                            {
                                
                                account: 'eosio.token',
                                name: 'uploadfile',
                                authorization: [{
                                    actor: account.name,
                                    permission: 'active'
                                }],
                                data: {
                                    author: account.name,
                                    hash: hash,
                                    price: price,
                                    title: title,
                                    description: description
                                }
                            }
                        ]
                    }
```

**Comment by bradlhart** [comment]
The official `eosio.token` contract abi does not contain a `uploadfile` action.  It might be possible that if this is a locally run chain, that the `eosio.token` account has multiple smart contracts set to it and it might have more actions, but I'd advise retrieving the abi file from the node you are attempting to process against to see if the account has that action.  It doesn't seem like it does considering the error.
