### ISSUE TITLE
check_authorization Error 

### ISSUE THREAD

**Issue by yepp4you** [EOSIO/eosjs#83]
eos : dawn-v4.0.0
eosjs : 10.0.0

In cleos, the account is created well, but in eosjs, the following problem occurs when creating account.

http://localhost:3330/v1/chain/push_transaction {"compression":"none","transaction":{"expiration":"2018-05-14T00:41:47","region":0,"ref_block_num":8406,"ref_block_prefix":3983766411,"max_net_usage_words":0,"max_kcpu_usage":0,"delay_sec":0,"context_free_actions":[],"actions":[{"account":"eosio","name":"newaccount","authorization":[{"actor":"eosio","permission":"active"}],"data":"0000000000ea3055000000012103b89a01000000010002c0ded2bc1f1305fb0faac5e6c03ee3a1924234985427b6167ca569d13df435cf01000001000000010002c0ded2bc1f1305fb0faac5e6c03ee3a1924234985427b6167ca569d13df435cf0100000100000000010000000000ea305500000000a8ed32320100"}]},"signatures":["SIG_K1_Kb8rBwQepJth2tQ4r86o1ZB1UWMbnKCdhXSjuGFiWHAD9YujH6betfQtLaWeqXhQ1WpFL7n7aH7kU2ntg29HDTXb392hjz"]}
api error => { message: 'transaction declares authority \'{"actor":"eosio","permission":"active"}\', but does not have signatures for it under a provided delay of 0 ms',
  file: 'authorization_manager.cpp',
  line_number: 405,
  method: 'check_authorization' } http://localhost:3330/v1/chain/push_transaction {"compression":"none","transaction":{"expiration":"2018-05-14T00:41:47","region":0,"ref_block_num":8406,"ref_block_prefix":3983766411,"max_net_usage_words":0,"max_kcpu_usage":0,"delay_sec":0,"context_free_actions":[],"actions":[{"account":"eosio","name":"newaccount","authorization":[{"actor":"eosio","permission":"active"}],"data":"0000000000ea3055000000012103b89a01000000010002c0ded2bc1f1305fb0faac5e6c03ee3a1924234985427b6167ca569d13df435cf01000001000000010002c0ded2bc1f1305fb0faac5e6c03ee3a1924234985427b6167ca569d13df435cf0100000100000000010000000000ea305500000000a8ed32320100"}]},"signatures":["SIG_K1_Kb8rBwQepJth2tQ4r86o1ZB1UWMbnKCdhXSjuGFiWHAD9YujH6betfQtLaWeqXhQ1WpFL7n7aH7kU2ntg29HDTXb392hjz"]}
{ Error: {"code":500,"message":"Internal Service Error","error":{"code":3090003,"name":"unsatisfied_authorization","what":"provided keys, permissions, and delays do not satisfy declared authorizations","details":[{"message":"transaction declares authority '{\"actor\":\"eosio\",\"permission\":\"active\"}', but does not have signatures for it under a provided delay of 0 ms","file":"authorization_manager.cpp","line_number":405,"method":"check_authorization"}]}}
    at /Users/yepp4you/Work/blockchain/portal/portal_server/node_modules/eosjs-api/lib/apigen.js:102:23
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7) status: 500, statusText: 'Internal Server Error' }
{ Error: {"code":500,"message":"Internal Service Error","error":{"code":3090003,"name":"unsatisfied_authorization","what":"provided keys, permissions, and delays do not satisfy declared authorizations","details":[{"message":"transaction declares authority '{\"actor\":\"eosio\",\"permission\":\"active\"}', but does not have signatures for it under a provided delay of 0 ms","file":"authorization_manager.cpp","line_number":405,"method":"check_authorization"}]}}
    at /Users/yepp4you/Work/blockchain/portal/portal_server/node_modules/eosjs-api/lib/apigen.js:102:23
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7) status: 500, statusText: 'Internal Server Error' }
[push_transaction error] '{"code":500,"message":"Internal Service Error","error":{"code":3090003,"name":"unsatisfied_authorization","what":"provided keys, permissions, and delays do not satisfy declared authorizations","details":[{"message":"transaction declares authority '{\"actor\":\"eosio\",\"permission\":\"active\"}', but does not have signatures for it under a provided delay of 0 ms","file":"authorization_manager.cpp","line_number":405,"method":"check_authorization"}]}}', transaction '4bdbf85a0000d6208b7373ed00000000010000000000ea305500409e9a2264b89a010000000000ea305500000000a8ed32327c0000000000ea3055000000012103b89a01000000010002c0ded2bc1f1305fb0faac5e6c03ee3a1924234985427b6167ca569d13df435cf01000001000000010002c0ded2bc1f1305fb0faac5e6c03ee3a1924234985427b6167ca569d13df435cf0100000100000000010000000000ea305500000000a8ed32320100'
{"code":500,"message":"Internal Service Error","error":{"code":3090003,"name":"unsatisfied_authorization","what":"provided keys, permissions, and delays do not satisfy declared authorizations","details":[{"message":"transaction declares authority '{\"actor\":\"eosio\",\"permission\":\"active\"}', but does not have signatures for it under a provided delay of 0 ms","file":"authorization_manager.cpp","line_number":405,"method":"check_authorization"}]}}
3090003

**Comment by ai-personas** [comment]
Received same kind of error when invoking contract action (even after merging pending pull request)

{"code":500,"message":"Internal Service Error","error":{"code":3090003,"name":"unsatisfied_authorization","what":"provided keys, permissions, and delays do not satisfy declared authorizations","details":[{"message":"transaction declares authority '{\"actor\":\"chmbifyslhqs\",\"permission\":\"active\"}', but does not have signatures for it under a provided delay of 0 ms","file":"authorization_manager.cpp","line_number":405,"method":"check_authorization"}]}}

**Comment by randytorres** [comment]
Same issue here

**Comment by nsjames** [comment]
So right now `eosjs` is still on dawn3, but there is a dawn4 ( `slim` ) branch which is being worked on. I've run some tests on it yesterday and it seems to be working as expected, I think we might just be waiting for it to be merged.

**Comment by ai-personas** [comment]
Received above error in slim branch only. For example, tried below transaction

                eos.transaction({
                    actions: [
                        {
                            account: 'hello',
                            name: 'hi',
                            authorization: [{
                                actor: 'nrisxgbvijwz',
                                permission: 'active'
                            }],
                            data: {
                                user: 'test'
                            }
                        }
                    ]
                })

**Comment by jcalfee** [comment]
I just merged slim into master .. It is getting a lot better but there are still errors..

**Comment by jcalfee** [comment]
eosjs master depends on fcbuffer [master], and eosjs-api [master] ..  There is still an error with the asset.  Once I fix that I can update npmjs..

**Comment by yepp4you** [comment]
If you overwrite the newly changed code in 10.0.0, delete the deposit, and test it, the account will be created.
// eosio_contract_abi.cpp
"newaccount": {
    "base": "",
    "type": "action",
    "fields": {
      "creator": "account_name",
      "name": "account_name",
      "owner": "authority",
      "active": "authority",
      "recovery": "authority"
    }
  },

https://github.com/EOSIO/eosjs/blob/a0b29aff1feda39ed862a2e2cacd5baff498d72b/src/schema/chain_types.json#L134

**Comment by jcalfee** [comment]
I published npm eosjs@dawn4 (version 11) .. This version is compatible with eosio/eos:dawn-v4.0.0 .. There are many changes.  Please let me know if you have questions or find other bugs..

**Comment by navcsdev** [comment]
@jcalfee When I create new account 
```
const eos = eosjs.Localnet({
      keyProvider: ['5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3'],
      binaryen
    });
    
    return eos.newaccount({
      creator: 'eosio',
      name,
      owner: 'EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV',
      active: 'EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV',
    });
```

It is still error same above !

I use `"eosjs": "^11.0.0",` 🙇

**Comment by jcalfee** [comment]
Maybe you have another eosjs-* package installed in your package.json?  Or the nodeosd your using is out of sync.  Your example works for me.

**Comment by AdamBylin** [comment]
"eosjs": "^13.1.0",  

  var config = {
    chainId: null,
    keyProvider: privateKey,
    httpEndpoint: "http://193.93.219.219:8888",
    broadcast: true,
    sign: true,
    expireInSeconds: 30
  }
  var eos = Eos.Testnet(config)

eos.newaccount({
  creator: 'eosio',
  name: 'eosio111',
  owner: 'EOS7JfRN8XTqkMcr71PZgYYL2APs2dDbykiQDpzk4gffPsuVBtWRT',
  active: 'EOS7JfRN8XTqkMcr71PZgYYL2APs2dDbykiQDpzk4gffPsuVBtWRT',
});

It is still error

Error: {"code":500,"message":"Internal Service Error","error":{"code":3090003,"name":"unsatisfied_authorization","what":"provided keys, permissions, and delays do not satisfy declared authorizations","details":[{"message":"transaction declares authority '{\"actor\":\"eosio\",\"permission\":\"active\"}', but does not have signatures for it under a provided delay of 0 ms","file":"authorization_manager.cpp","line_number":405,"method":"check_authorization"}]}}

please help me..

**Comment by jcalfee** [comment]
The most common issue is the chainId .. Look at the chainId in get_info under `http://193.93.219.219:8888/v1/chain/get_info` then include that hex string in `config.chainId` ..

**Comment by AdamBylin** [comment]
var httpConfig = {
  headers: {
    'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
  }
};

REQUST("http://193.93.219.219:8888/v1/chain/get_info", null, (rst) => {
  var Eos = require('eosjs') // Eos = require('./src')
  var getEos = function() {
  	console.log("**************")
  	console.log(rst.chain_id)
  	console.log("**************")
    var headers = {}
    var privateKey = "5JbbVmtkWirLtJuSmjuBjVfXcmEfZFr8Dv6VecGY33aonfjQBkw";
    var config = {
      chainId: rst.chain_id,
      keyProvider: privateKey,
      httpEndpoint: "http://193.93.219.219:8888",
      broadcast: true,
      sign: true,
      expireInSeconds: 30
    }
 
    var eos = Eos.Testnet(config); // Eos.Localnet("https// 127.0.0.1:8888");
    return eos
  }

  var eos = getEos();
  eos.getInfo({}).then(result => {
    console.log("//=====================getInfo")
    console.log(result)
    // var chainId = result.
  })

  eos.newaccount({
    creator: 'eosio',
    name: 'eosio111',
    owner: 'EOS7JfRN8XTqkMcr71PZgYYL2APs2dDbykiQDpzk4gffPsuVBtWRT',
    active: 'EOS7JfRN8XTqkMcr71PZgYYL2APs2dDbykiQDpzk4gffPsuVBtWRT',
  });
}, httpConfig);

i had try  but no work  , still showing the same error.

**Comment by AdamBylin** [comment]
var httpConfig = {
  headers: {
    'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
  }
};
REQUST("http://193.93.219.219:8888/v1/chain/get_info", null, (rst) => {
  var Eos = require('eosjs') // Eos = require('./src')
  var getEos = function() {

    console.log("//================")
    console.log(rst.chain_id)
    console.log("//================")

    var headers = {}
    var privateKey = "5JbbVmtkWirLtJuSmjuBjVfXcmEfZFr8Dv6VecGY33aonfjQBkw";
    var config = {
      chainId: rst.chain_id,
      keyProvider: privateKey,
      httpEndpoint: "http://193.93.219.219:8888",
      broadcast: true,
      sign: true,
      expireInSeconds: 30
    }

    var eos = Eos.Testnet(config); // Eos.Localnet("https// 127.0.0.1:8888");
    return eos
  }
  eos.newaccount({
    creator: 'eosio',
    name: 'eosio111',
    owner: 'EOS7JfRN8XTqkMcr71PZgYYL2APs2dDbykiQDpzk4gffPsuVBtWRT',
    active: 'EOS7JfRN8XTqkMcr71PZgYYL2APs2dDbykiQDpzk4gffPsuVBtWRT',
  });

}, httpConfig);

no work ,  still showing the same error.


//================
main.js?1c90:34 01750cf763fbac963c344639d96ce503eadbf045aa7e4da67813290673112fd7
main.js?1c90:35 //================
apigen.js?f08d:110 POST http://193.93.219.219:8888/v1/chain/push_transaction 500 (Internal Server Error)

apigen.js?f08d:140 api error => {message: "transaction declares authority '{"actor":"eosio","… signatures for it under a provided delay of 0 ms", file: "authorization_manager.cpp", line_number: 405, method: "check_authorization"} http://193.93.219.219:8888/v1/chain/push_transaction {"compression":"none","transaction":{"expiration":"2018-06-02T03:08:40","ref_block_num":26744,"ref_block_prefix":2456908361,"net_usage_words":0,"max_cpu_usage_ms":0,"delay_sec":0,"context_free_actions":[],"actions":[{"account":"eosio","name":"newaccount","authorization":[{"actor":"eosio","permission":"active"}],"data":"0000000000ea30550000002104ea3055010000000100033e47ffbd31bd2b7025e907fc366294b18f7d73ca288bfb9c243c4f640d26630901000000010000000100033e47ffbd31bd2b7025e907fc366294b18f7d73ca288bfb9c243c4f640d26630901000000"}],"transaction_extensions":[]},"signatures":["SIG_K1_Kem3dQr86BV9dUzb1YaNCp1oJVGcJv1fd4pnHbv6M2MD56T5unNHDPqnJurfffRACiRe3pDjst9PBUFzcPcGXh1kMYacb1"]}

**Comment by AdamBylin** [comment]
Should i try to devolop  with  "eosjs ^14.1.0"?   
Any suggestions i can try?
