### ISSUE TITLE
version 20.0.0 eos.js and eos.min.js files

### ISSUE THREAD

**Issue by mark11226** [EOSIO/eosjs#830]
eos.js and eos.min.js are missing. It would be great if someone could add those files. I can't find them anywhere. Ever since version 16.0.9 those two files are gone but I need them for my app.

Can you please include the version 20.0.0 eos.js and eos.min.js files in the released "assets" like you used to ? Or maybe put them again at the same site you used for version 16.0.8 (below link). I want to update my project with the newest 20.0.0 version eos.js and eos.min.js. Thank you !
https://cdn.jsdelivr.net/npm/eosjs@16.0.8/lib/

**Comment by bradlhart** [comment]
eosjs v20.0.0 and above introduced a new dynamic to using eosjs.  With that change, there are multiple files to use eosjs with, such as eosjs-api, eosjs-serialize, etc.  If you would like to use these files in a web context, you need to run either `npm run build-web` or `yarn build-web` to build the files.  Unfortunately there is no CDN available at this time for these files.

Additional context: https://developers.eos.io/manuals/eosjs/latest/basic-usage/browser
