### ISSUE TITLE
npm audit issue with elliptic

### ISSUE THREAD

**Issue by makc** [EOSIO/eosjs#850]
**Version of EOSJS**
^21.0.3

**Describe the bug**
`npm audit` has issues with elliptic, says it was fixed in newer version

**To Reproduce**
run `npm audit`? in my case, this was a project with ual-anchor package, and [they say](https://github.com/greymass/ual-anchor/issues/14) the problem is on your side

**Expected behavior**
0 audit issues

**Screenshots**
![](https://user-images.githubusercontent.com/677686/112086918-7374f500-8b63-11eb-9c04-d3ba2a287c37.png)

**Comment by bradlhart** [comment]
We have addressed this in the edge release of eosjs and there is a PR open to include it to the eosjs v22 release but in the meantime, you might be able to force your install to use elliptic@6.5.4 by using the `resolutions` field in package.json.  We are certain there are no breaking changes on our end in this case if you would like to do that.

You can also choose to use eosjs@edge but it is specifically for the v2.1 of nodeos and there might be type mismatches if you use it with an older version.  See the v22 release candidate notes for more information: https://github.com/EOSIO/eosjs/releases/tag/v22.0.0-rc2

**Comment by makc** [comment]
> resolutions

[they say](https://stackoverflow.com/a/53067345) it only works with yarn, npm does not have it ootb

**Comment by bradlhart** [comment]
This should be resolved with the v21.0.4 patch version.  Please let us know if there are any persistent problems regarding this issue to reopen.
