### ISSUE TITLE
Getting net_usage_words error when using eos.transfer()

### ISSUE THREAD

**Issue by Dylan-Phoon** [EOSIO/eosjs#86]
I run this: `eos.transfer("tester1234", "dylan2", "0 EOS", "", {sign: true, broadcast: true}).then(res=>{ console.log(res)})`

And get this error: `Error: Required varuint32 transaction_header.net_usage_words transaction.`

I'm using slim branch.

**Comment by ai-personas** [comment]
Tried it in master and getting the same kind of error
`Error: Required varuint32 transaction_header.net_usage_words transaction.`

If i override header with below seems its working

```javascript
const headers = {
                    expiration: expiration.toISOString().split('.')[0],
                    region: 0,
                    ref_block_num: ref_block_num,
                    ref_block_prefix: block.ref_block_prefix,
                    // max_net_usage_words: 0,
                    // max_kcpu_usage: 0,
                    net_usage_words: 0,
                    max_cpu_usage_ms: 0,
                    delay_sec: 0,
                    context_free_actions: [],
                    actions: [],
                    signatures: [],
                    transaction_extensions: []
                };
```

**Comment by Dylan-Phoon** [comment]
Hmm maybe you should submit pull request? seems to work for me as well

**Comment by Dylan-Phoon** [comment]
What file is that located in? @ai-personas

**Comment by jcalfee** [comment]
I just published npm eosjs@dawn4 (version 11) .. This version is compatible with eosio/eos:dawn-v4.0.0 ..

**Comment by Dylan-Phoon** [comment]
Awesome! I will try this now... at 4am in the morning lol.
