### ISSUE TITLE
Authorization error when executing a contract action under Dawn 4.0

### ISSUE THREAD

**Issue by keisuke-kanao** [EOSIO/eosjs#87]
I executed eosio.token "issue" action under Dawn 4.0.
Using cleos was successful, but using eosjs 10.0.0 as below failed:
<pre>
Eos = require('eosjs')
const keyProvider = [
  '5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3'  // eosio
];
eos = Eos.Localnet({keyProvider});
// cleos push action eosio.token issue '{"to":"bob", "quantity":"100.0000 EOS", "memo":"issue to bob"}' -p eosio
eos.transaction({
  actions: [
    {
      account: 'eosio.token',
      name: 'issue',
      authorization: [{
        actor: 'eosio',
        permission: 'active'
      }],
      data: {
        to: 'bob',
        quantity: '100.0000 EOS',
        memo: 'issue to bob'
      }
    }
  ]
});
</pre>
 
With an error message:
<pre>
api error => { message: 'transaction declares authority \'{"actor":"eosio","permission":"active"}\', but does not have signatures for it under a provided delay of 0 ms',
  file: 'authorization_manager.cpp',
  line_number: 405,
  method: 'check_authorization' } http://127.0.0.1:8888/v1/chain/push_transaction {"compression":"none","transaction":{"expiration":"2018-05-15T06:45:55","region":0,"ref_block_num":37522,"ref_block_prefix":3593414125,"max_net_usage_words":0,"max_kcpu_usage":0,"delay_sec":0,"context_free_actions":[],"actions":[{"account":"eosio.token","name":"issue","authorization":[{"actor":"eosio","permission":"active"}],"data":"0000000000000e3d40420f000000000004454f53000000000c697373756520746f20626f62"}]},"signatures":["SIG_K1_KisUp8Q9rHayfET6P5Kb81DjcydaTGFosvQd8Grua4oaPNWuNZMEh1CeuJpYNMupYAnPSk7JCWR4jSJ3vNpXMp6ZsP4Gn6"]}
{ Error: {"code":500,"message":"Internal Service Error","error":{"code":3090003,"name":"unsatisfied_authorization","what":"provided keys, permissions, and delays do not satisfy declared authorizations","details":[{"message":"transaction declares authority '{\"actor\":\"eosio\",\"permission\":\"active\"}', but does not have signatures for it under a provided delay of 0 ms","file":"authorization_manager.cpp","line_number":405,"method":"check_authorization"}]}}
    at /home/makoto/eos/contracts/crid_test/node_modules/eosjs-api/lib/apigen.js:102:23
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7) status: 500, statusText: 'Internal Server Error' }
{ Error: {"code":500,"message":"Internal Service Error","error":{"code":3090003,"name":"unsatisfied_authorization","what":"provided keys, permissions, and delays do not satisfy declared authorizations","details":[{"message":"transaction declares authority '{\"actor\":\"eosio\",\"permission\":\"active\"}', but does not have signatures for it under a provided delay of 0 ms","file":"authorization_manager.cpp","line_number":405,"method":"check_authorization"}]}}
    at /home/makoto/eos/contracts/crid_test/node_modules/eosjs-api/lib/apigen.js:102:23
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7) status: 500, statusText: 'Internal Server Error' }
[push_transaction error] '{"code":500,"message":"Internal Service Error","error":{"code":3090003,"name":"unsatisfied_authorization","what":"provided keys, permissions, and delays do not satisfy declared authorizations","details":[{"message":"transaction declares authority '{\"actor\":\"eosio\",\"permission\":\"active\"}', but does not have signatures for it under a provided delay of 0 ms","file":"authorization_manager.cpp","line_number":405,"method":"check_authorization"}]}}', transaction '2382fa5a00009292ed252fd6000000000100a6823403ea30550000000000a53176010000000000ea305500000000a8ed3232250000000000000e3d40420f000000000004454f53000000000c697373756520746f20626f62'
{"code":500,"message":"Internal Service Error","error":{"code":3090003,"name":"unsatisfied_authorization","what":"provided keys, permissions, and delays do not satisfy declared authorizations","details":[{"message":"transaction declares authority '{\"actor\":\"eosio\",\"permission\":\"active\"}', but does not have signatures for it under a provided delay of 0 ms","file":"authorization_manager.cpp","line_number":405,"method":"check_authorization"}]}}
(node:22966) UnhandledPromiseRejectionWarning: {"code":500,"message":"Internal Service Error","error":{"code":3090003,"name":"unsatisfied_authorization","what":"provided keys, permissions, and delays do not satisfy declared authorizations","details":[{"message":"transaction declares authority '{\"actor\":\"eosio\",\"permission\":\"active\"}', but does not have signatures for it under a provided delay of 0 ms","file":"authorization_manager.cpp","line_number":405,"method":"check_authorization"}]}}
(node:22966) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:22966) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
</pre>
Actually, first I tried with a test script and my own contract and got the same error message. The test script worked well under Dawn. 3.0.

If you have any idea to solve this issue, please let me know.,

**Comment by blyse** [comment]
I tried 'newaccount', also same receive that response. 

`con.newaccount({
                    creator: 'blyse',
                    name: name,
                    owner: Eos.modules.ecc.privateToPublic(owner_key.toString()),
                    active: Eos.modules.ecc.privateToPublic(active_key.toString()),
                    recovery: 'blyse'
                })
`

`
{message: "transaction declares authority '{"actor":"blyse","… signatures for it under a provided delay of 0 ms", file: "authorization_manager.cpp", line_number: 405, method: "check_authorization"} http://112.175.23.206:8888/v1/chain/push_transaction {"compression":"none","transaction":{"expiration":"2018-05-15T06:49:26","region":0,"ref_block_num":28366,"ref_block_prefix":2359214972,"max_net_usage_words":0,"max_kcpu_usage":0,"delay_sec":0,"context_free_actions":[],"actions":[{"account":"eosio","name":"newaccount","authorization":[{"actor":"blyse","permission":"active"}],"data":"0000000000857d3c00000000f8787c3c01000000010002a45cd1cf5ce09d1b987281c2d1335f9ba0782ee14e5bd22b51021e9fa73a30e4010000010000000100034230396ef278122fe56a48f305dcd0da6b0126952614552900519d52189360c20100000100000000010000000000857d3c00000000a8ed32320100"}]},"signatures":["SIG_K1_KB1kCNx7AFHQWKGhRiS4tV5SawGXnDZewoq74RrefQjAxfdD9ZN3mw7x2Ky1bS19TXBzLNtdgyRabPCUWcppYR66x8v3gj"]}


Error: {"code":500,"message":"Internal Service Error","error":{"code":3090003,"name":"unsatisfied_authorization","what":"provided keys, permissions, and delays do not satisfy declared authorizations","details":[{"message":"transaction declares authority '{\"actor\":\"blyse\",\"permission\":\"active\"}', but does not have signatures for it under a provided delay of 0 ms","file":"authorization_manager.cpp","line_number":405,"method":"check_authorization"}]}}
`

**Comment by blyse** [comment]
I tried 'newaccount', also same receive that response. 

`
con.newaccount({
	creator: 'blyse',
	name: name,
	owner: Eos.modules.ecc.privateToPublic(owner_key.toString()),
	active: Eos.modules.ecc.privateToPublic(active_key.toString()),
	recovery: 'blyse'
})
`

![image](https://user-images.githubusercontent.com/5298919/40043980-0806d26c-5861-11e8-85c0-100722c3ec58.png)

**Comment by jcalfee** [comment]
There is confusion on my part over the branches .. I have been working on eosio master for the last 4 days and overlooked the dawn4 tag.  Fortunately the dawn4 tag is working better..

**Comment by keisuke-kanao** [comment]
Hi James, what exactly do you mean?
I did "git checkout dawn-v4.0.0" and rebuilt eos, and with eosjs 10.0.0, I still_ have the same issue with the same error message.
What exactly I should do?

**Comment by blyse** [comment]
+1

**Comment by jcalfee** [comment]
I published npm eosjs@dawn4 (version 11) .. This version is compatible with eosio/eos:dawn-v4.0.0 .. There are many changes, let me know if you have questions or find other bugs..

**Comment by keisuke-kanao** [comment]
With eos: dawn-v4.0.0 and eosjs@dawn4 (version 11.0.0), I confirmed that this issue doesn't happen.
