### ISSUE TITLE
[HELP] dawn 4.0 eosio_native and eosio_token

### ISSUE THREAD

**Issue by kristieguo** [EOSIO/eosjs#89]
Hi, in dawn4 version there are eosio_native and eosio_token json schema, but I could not find any eosio.native contract in eos repo. 

1. Is eosio.native the main EOS after block.one publish? 
2. How to set eosio.native contract to test on local node?

**Comment by jcalfee** [comment]
Native does not have an ABI and appear through out the c++ code..  I'm not sure yet how to identify all the native methods.  I suspect they are all here though:

https://github.com/EOSIO/eos/blob/13952d4505d56442a769528bdf6094b52768b2cd/contracts/eosio.system/eosio.system.cpp#L78-L91

**Comment by jcalfee** [comment]
The issue was that eosio.system.abi was very bare for a while so I moved some important actions into this custom file (maybe my name sounded too official).  Since eosio.system.abi is much more full featured now I was able to remove eosio.native ..
