### ISSUE TITLE
eosjs  transaction not working

### ISSUE THREAD

**Issue by alzozov** [EOSIO/eosjs#90]
i have eosjs  talking to local eos testnode and it gives error
eos : DAWN-2018-04-27-ALPHA
eosjs : 10.0.0

 ```
// eosClient.transaction({
                //       actions: [
                //         {
                //           account: "basics",
                //           name: action,
                //           authorization: [{
                //             actor: "basics",
                //             permission: 'active'
                //           }],
                //           data:  data
                //         }
                //       ]
                //   })
```

get error:

error: Invalid packed transaction

`
2514645ms thread-0   chain_api_plugin.cpp:79       operator()           ] Exception encountered while processing chain.push_transaction: {"code":3120010,"name":"packed_transaction_type_exception","message":"Invalid packed transaction","stack":[{"context":{"level":"warn","file":"chain_plugin.cpp","line":432,"method":"push_transaction","hostname":"","thread_name":"thread-0","timestamp":"2018-05-16T07:41:54.645"},"format":"Invalid packed transaction","data":{}},{"context":{"level":"error","file":"signature.cpp","line":18,"method":"parse_base58","hostname":"","thread_name":"thread-0","timestamp":"2018-05-16T07:41:54.645"},"format":"prefix_matches(prefix, base58str): Signature has invalid prefix: ${str}","data":{"str":"SIG_K1_KdXM6tH3vrk1XcBdvCAp9ZfZMmZP5uzE46sgTPVCMhmomZfv4oLbTFWSQ6efmjDVnd4KHUZrvEDNpns9ygGy5XzrABpP3C"}},{"context":{"level":"error","file":"abi_serializer.hpp","line":444,"method":"from_variant","hostname":"","thread_name":"thread-0","timestamp":"2018-05-16T07:41:54.645"},"format":"Failed to deserialize variant","data":{"variant":{"compression":"none","transaction":{"expiration":"2018-05-16T07:42:54","region":0,"ref_block_num":51343,"ref_block_prefix":1803784123,"max_net_usage_words":0,"max_kcpu_usage":0,"delay_sec":0,"context_free_actions":[],"actions":[{"account":"basics","name":"ok","authorization":[],"data":""}]},"signatures":["SIG_K1_KdXM6tH3vrk1XcBdvCAp9ZfZMmZP5uzE46sgTPVCMhmomZfv4oLbTFWSQ6efmjDVnd4KHUZrvEDNpns9ygGy5XzrABpP3C"]}}}]}`

versions of eosjs & eos not match I suppose...
what eosjs version should i use ?

**Comment by jcalfee** [comment]
Try dawn4 or downgrade to eosjs 9..  You can check the README for information like this:

dawn4 | tag: 11.x.x
-- | --
DAWN-2018-04-23-ALPHA | tag: 9.x.x
