### ISSUE TITLE
Getting 'unable to find key' error when sending transaction

### ISSUE THREAD

**Issue by Dylan-Phoon** [EOSIO/eosjs#91]
Here is transfer: `eos.transfer("dylan1", "dylan2", "1 EOS", "", {broadcast: true, sign: true}).then(result=>{console.log(result)});`

Here is error: `error: {"code":10,"name":"assert_exception","what":"Assert Exception","details":[{"message":"condition: assertion failed: unable to find key","file":"wasm_interface.cpp","line_number":910,"method":"eosio_assert"}`

Im using latest version (dawn4)

**Comment by nirdesh365** [comment]
I am having the same issue while transfer the eos , I again started the node and run keosd also give token to both accounts  in which transaction occur .I am not getting any  clue where  is the error ..can some boy help me .

**Comment by nirdesh365** [comment]
I am also getting the same error How can  you people solve this issue .Any suggestion please

**Comment by jcalfee** [comment]
"key" is generic .. so check your account names and symbol name carefully.  Make sure your pushing the transfer to the correct smart contract.  (unrelated, you need decimals here `1.0000 EOS`)

**Comment by nirdesh365** [comment]
I am correctly using precision  points and other actions of my contracts are working fine , But while using transfer it generated the error 
**3092298ms thread-0   main.cpp:2350    main ] Failed with error: Assert Exception (10)
condition: assertion failed: unable to find key**
4 days back it was working fine , than I restart the node and keosd and create two new account and their corresponding wallet . I am using the transfer function  same as eosio.token contract.
Is there  can any issue related to permission ?

**Comment by chris-allnutt** [comment]
Make sure that the chain has that contract deployed to it.  I think unable
to find key is the same error you get if it cannot find an account.  If
your local setup isn't persisting shared mem, or has replay in it's nodeos
startup it will wipe the chain every time you restart.
