### ISSUE TITLE
make keyProvider config async.

### ISSUE THREAD

**Issue by pluswave** [EOSIO/eosjs#93]
Currently, if keyProvider is a function, it is synchronized. I think it will be great if keyProvider is a function which returns a promise. (i.e, for user interaction)

**Comment by nsjames** [comment]
You can use async/await to resolve the promise. I'm not sure if it works with keyProvider but it works with signProvider for sure.

**Comment by jcalfee** [comment]
In the implementation, the return value is sent through `Promose.resolve(keyProvider(...)).then(..` .. This means you can return a Promise and it will wait or you can return a value directly and that will work too.

**Comment by jcalfee** [comment]
Wait, I spoke too soon .. that works with signProvider but not keyProvider.  I'll have a look.

**Comment by jcalfee** [comment]
published eosjs@11.0.1
