### ISSUE TITLE
"Transaction declares authority" error when pushing tx

### ISSUE THREAD

**Issue by Dylan-Phoon** [EOSIO/eosjs#94]
I do: ```eos.pushTransaction({compression: 'none',
		transaction: tr,
		signatures: sigs})```

And get this error: 
```
api error => { message: 'transaction declares authority \'{"actor":"dylan1","permission":"active"}\', but does not have signatures for it under a provided delay of 0 ms',
  file: 'authorization_manager.cpp',
  line_number: 405,
  method: 'check_authorization' }
```

EDIT: Also gives the same error for ```eos.transfer(params)```

**Comment by Dylan-Phoon** [comment]
Hmmm I just reinstalled eosjs (v12.0.0) and still getting the same error when doing ```eos.transfer(params)```

**Comment by jcalfee** [comment]
Why are you calling pushTransaction?  I don't have enough information to see what your doing.

**Comment by Dylan-Phoon** [comment]
I seem to have got it working after I build eos locally, run nodeos and connect instead of connecting to a jungle testnet node. sorry for opening this issue 😅

**Comment by jcalfee** [comment]
Yea, testnets are really tricky with so many moving parts.  I'm really happy to have Docker .. Even that is still a little complicated but it really helps.
