### ISSUE TITLE
"Table stat is not specified in the ABI" when creating an account

### ISSUE THREAD

**Issue by sss-CRS-sss** [EOSIO/eosjs#95]
When i push transactions "create account and buy&delegate.." got error:
`api error => {message: "Table stat is not specified in the ABI", file: "chain_plugin.cpp", line_number: 335, method: "get_table_type"}
v1/chain/get_currency_stats {"code":"eosio","symbol":"EOS"}
`
The parameter must pass **eosio.token**, not **eosio**

**Comment by jcalfee** [comment]
Thanks, I'm investigating .. Which version of nodeosd are you using?

Keep in mind another change in 4.1 was to renamed EOS to SYS which is in eosjs master (version 12.x) ..

**Comment by jcalfee** [comment]
published eosjs@12.0.1

**Comment by sss-CRS-sss** [comment]
eosjs@12.0.1 working, ty!

**Comment by sim31** [comment]
I'm getting a similar error:
```
api error => {message: "Table stat is not specified in the ABI", file: "chain_plugin.cpp", line_number: 335, method: "get_table_type"}file: "chain_plugin.cpp"line_number: 335message: "Table stat is not specified in the ABI"method: "get_table_type"__proto__: Object http://localhost:8888/v1/chain/get_currency_stats {"code":"polleos","symbol":"EOS"}
```
Note that it's trying to access currency stats in polleos contract for some reason, but this contract is not a token contract.

My abi can be found [here](https://github.com/sim31/polleos/blob/master/polleos.abi). And I'm trying to use it like this:
```
polleos.newtokenpoll(pollData.question, pollData.options, pollData.token, opts);
```
Where pollData.token is something like:
```
pollData.token = {
  value:  "4,EOS",
  contract: "eosio.token"
};
```

**Comment by jcalfee** [comment]
A "symbol" is just the precision and 7 letter symbol without specifying any contract.  If you send a symbol to a custom contract like polleos it thinks that polleos has its own token called EOS which is completely different.

Now, I do see I'm missing a type called `extended_symbol`.  I see you tried to create it but that may not work entirely because it needs to programmatically support a string format `SYM@contract`.  So I will add this soon.

I have `extended_asset` which is all this plus a precision and amount: `1.0000 4,SYM@contract` .. Don't think that will help you though.  I'll let you know when this type is ready and published.

**Comment by ItsLeeOwen** [comment]
I'm seeing this error response from getCurrentBalance & getCurrencyStats with a token I've created using the eosio.token contract (https://github.com/EOSIO/eos/tree/master/contracts/eosio.token)

```js
eos.getCurrencyBalance({
  code: "eosio",
  symbol: "TEST",
  account: "tester",
})
```

```json
{  
   "code":500,
   "message":"Internal Service Error",
   "error":{  
      "code":3060003,
      "name":"contract_table_query_exception",
      "what":"Contract Table Query Exception",
      "details":[  
         {  
            "message":"Table accounts is not specified in the ABI",
            "file":"chain_plugin.cpp",
            "line_number":570,
            "method":"get_table_type"
         }
      ]
   }
}
```

**Comment by ItsLeeOwen** [comment]
@jcalfee   Just got a successful response by passing the token account name as the code param value.  Sweet!

```js
eos.getCurrencyBalance({
  code: "test",
  symbol: "TEST",
  account: "tester",
})
```
```json
[
    "75.0000 TEST",
    "100.0000 TEST"
]
```

**Comment by jeffreyssmith2nd** [comment]
@gavinwyf That's the terminology used by the blockchain https://developers.eos.io/eosio-nodeos/reference#get_code

**Comment by CaliosD** [comment]
I wonder what the corresponding code for the newest version looks like... I didn't find it anywhere. =_+

**Comment by AndrewVV** [comment]
This is my worked example:

{
    "code" : "eosio.token",
    "account" : "eosandrewvv1",
    "symbol": "EOS"
}
