### ISSUE TITLE
System contract newaccount params

### ISSUE THREAD

**Issue by eosio-sg** [EOSIO/eosjs#96]
Hi,

Currently, we use js-API to create a new account. But come across the problem 
![image](https://user-images.githubusercontent.com/38582993/40299389-b0f2f714-5d18-11e8-83de-2d2344f86bba.png)
I think It's because the API still use **simple** method without params **--stake-cpu**,  **--stake-net**. So could you help to check issue?

**Comment by eosio-sg** [comment]
###Code
![image](https://user-images.githubusercontent.com/38582993/40299706-b553186a-5d19-11e8-80b1-098b035556ec.png)

###Error
{message: "account qqqqqqqqqqqq has insufficient ram; needs 2996 bytes has 0 bytes", file: "resource_limits.cpp", line_number: 185, method: "verify_account_ram_usage"}

**Comment by jcalfee** [comment]
I still need to update the docs for this change in dawn4.1 .. Here is a woking newaccount transaction:
https://github.com/EOSIO/eosjs/blob/master/src/index.test.js#L231-L249

**Comment by jcalfee** [comment]
published eosjs@12.0.1

**Comment by jcalfee** [comment]
Updated README .. fixed
