### ISSUE TITLE
Please add EOS symbol

### ISSUE THREAD

**Issue by yepp4you** [EOSIO/eosjs#97]
Please add EOS symbol

    'EOS@eosio': { precision: 4 },
    'EOS@eosio.token': { precision: 4 }

https://github.com/EOSIO/eosjs/blob/f18e43fe753a9b35ed09ae8c389fa43324495385/src/asset-cache.js#L9

**Comment by jcalfee** [comment]
published eosjs@12.0.1
related: https://github.com/EOSIO/eosjs/issues/95
