### ISSUE TITLE
Please add listproducers to eosjs

### ISSUE THREAD

**Issue by wuyahuang** [EOSIO/eosjs#98]
![1526907724164](https://user-images.githubusercontent.com/5432044/40308924-5b74b260-5d3a-11e8-9cf8-7958fb79fd22.jpg)

**Comment by jcalfee** [comment]
Fixed, try eosjs 12.0.1
https://github.com/EOSIO/eosjs-api/issues/12

**Comment by wuyahuang** [comment]
![1526913176390](https://user-images.githubusercontent.com/5432044/40313026-11880d16-5d47-11e8-82a3-1658618cfd7b.jpg)

Hello, James, it looks like the rows of getProducers() are encrypted?

**Comment by jcalfee** [comment]
Interesting .. maybe they are serialized.. I'll ask about this thanks.

**Comment by yepp4you** [comment]
There seems to be no problem with dawn-v4.1.0.

It seems that the list_producers_subcommand of cleos of the master branch does not add decrypt code separately, and does not seem to do ecrypt. I will test the master branch later.

**Comment by tbfleming** [comment]
Set ```json=true``` to produce a json result instead of a serialized result. Or, if you want to deserialize on the receiving end, it's the system abi's producer table in serialized form.

**Comment by wuyahuang** [comment]
`eos.getProducers({json:true})`
Great, thanks, it works for me. @tbfleming
